// Code generated by bento ts-compat from generatorReturnTypeIndirectReferenceToGlobalType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() *value.Gen[float64] {
	return value.NewGen[float64](func(_bt0 *value.GenCo[float64]) value.Value {
		a := value.ToNumber(_bt0.Yield(0))
		_ = a
		return value.Number(1)
	})
}
func main() {
}
