// Code generated by bento ts-compat from scannerNonAsciiHorizontalWhitespace.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("\u00a0 function f() {}")
	_ = value.FromGoString("\u00a0 function f() {}")
}
