// Code generated by bento ts-compat from parserComputedPropertyName41.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := value.NewObject().SetKeyed(value.Bool(value.InOperator(value.Number(0), value.NewArrayValue([]value.Value{}))), value.Bool(true))
	_ = v
}
