// Code generated by bento ts-compat from checkJsdocSatisfiesTag15.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Fn7(uuid value.Value) {
}
func main() {
	fn1 := func(uuid value.Value) {
	}
	_ = fn1
	v1 := value.NewArray[value.BStr](value.FromGoString("abc"))
	_ = v1
	v2 := value.NewArray[float64](123)
	_ = v2
	fn2 := func(a value.Value, b value.Value) {
	}
	_ = fn2
	fn3 := func(a value.Value, b value.Value) {
	}
	_ = fn3
	fn4 := func(a value.Value, b value.Value) {
	}
	_ = fn4
	fn5 := func(a value.Value, b value.Value) {
	}
	_ = fn5
	fn6 := func(a value.Value, b value.Value) {
	}
	_ = fn6
}
