// Code generated by bento ts-compat from checkJsdocParamOnVariableDeclaredFunctionExpression.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := func(n value.Value, s value.Value) {
	}
	_ = x
	var y value.Value
	_ = y
	y = value.NewFunc(func(__a []value.Value) value.Value {
		(func(b value.Value) {
		})(value.Arg(__a, 0))
		return value.Undefined
	})
	var (
		one func(value.Value) = func(s value.Value) {
		}
		two func(value.Value) = func(untyped value.Value) {
		}
	)
	_ = one
	_ = two
}
