// Code generated by bento ts-compat from checkJsdocTypedefInParamTag1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.BStr `json:"x"`
}
type ObjAnotherX struct {
	AnotherX value.BStr `json:"anotherX"`
}

func Foo(opts value.Value) {
	_ = opts.Get(value.FromGoString("x"))
}
func Foo1(opts value.Value) {
	_ = opts.Get(value.FromGoString("anotherX"))
}
func Foo2(opts value.Value) {
	_ = opts.Get(value.FromGoString("x"))
}
func main() {
	Foo(value.NewObject().Set(value.FromGoString("x"), value.StringValue(value.FromGoString("abc"))))
	Foo1(value.NewObject().Set(value.FromGoString("anotherX"), value.StringValue(value.FromGoString("world"))))
	Foo2(value.NewObject().Set(value.FromGoString("x"), value.StringValue(value.FromGoString("abc"))))
}
