// Code generated by bento ts-compat from jsdocVariableDeclarationWithTypeAnnotation.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var (
		x value.Value
		y value.Value
	)
	_ = x
	_ = y
}
