// Code generated by bento ts-compat from jsdocTemplateTagNameResolution.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjA struct {
	A float64 `json:"a"`
}

func main() {
	x := &ObjA{A: 1}
	_ = x
	y := value.FromGoString("a")
	_ = y
}
