// Code generated by bento ts-compat from seeTag2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.FromGoString("")
	_ = a
	b := value.FromGoString("")
	_ = b
	c := value.FromGoString("")
	_ = c
	d := value.FromGoString("")
	_ = d
	e := value.FromGoString("")
	_ = e
	f := value.FromGoString("")
	_ = f
	g := value.FromGoString("")
	_ = g
}
