// Code generated by bento ts-compat from typedefScope1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func B1() {
	ok1 := 0.0
	_ = ok1
}
func B2() {
	ok2 := value.FromGoString("hi")
	_ = ok2
}
func main() {
	notOK := 0.0
	_ = notOK
}
