// Code generated by bento ts-compat from typeTagNoErasure.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	test := func(dibbity value.Value) value.Value {
		return dibbity
	}
	test(value.Number(1))
	test(value.StringValue(value.FromGoString("hi")))
}
