// Code generated by bento ts-compat from asyncArrowFunction2_es5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	f := func(await value.Value) {
	}
	_ = f
}
