// Code generated by bento ts-compat from parserKeywordsAsIdentifierName1.ts. DO NOT EDIT.

package main

type ObjBreakConstSuper struct {
	Break float64 `json:"break"`
	Super float64 `json:"super"`
	Const float64 `json:"const"`
}

func main() {
	big_ := &ObjBreakConstSuper{Break: 0, Super: 0, Const: 0}
	_ = big_
}
