// Code generated by bento ts-compat from parserInExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	value.ConsoleLog(value.BoolToString(value.InOperator(value.StringValue(value.FromGoString("a")), value.NewObject().Set(value.FromGoString("a"), value.Bool(true)))))
}
