// Code generated by bento ts-compat from parserObjectType3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X value.Value `json:"x"`
	Y value.Value `json:"y"`
}

func main() {
	var v *ObjXY
	_ = v
}
