// Code generated by bento ts-compat from awaitInheritedPromise_es2017.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

var a *value.Promise[value.BStr]

func F() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
		_ = value.Await(_bt0, a)
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
