// Code generated by bento ts-compat from symbolDeclarationEmit9.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	obj := value.NewObject().SetKeyed(value.SymbolIsConcatSpreadable(), value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	_ = obj
}
