// Code generated by bento ts-compat from symbolDeclarationEmit8.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	obj := value.NewObject().SetKeyed(value.SymbolIsConcatSpreadable(), value.Number(0))
	_ = obj
}
