// Code generated by bento ts-compat from emitArrowFunctionAsIs.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	arrow1 := func(a value.Value) {
	}
	_ = arrow1
	arrow2 := func(a value.Value) {
	}
	_ = arrow2
	arrow3 := func(a value.Value, b value.Value) {
	}
	_ = arrow3
}
