// Code generated by bento ts-compat from classStaticBlock14.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var c_p__1 value.Value = value.Number(1)
var c_p__3 value.Value = value.Number(1)
var c_p__5 value.Value = value.Number(1)

func NewC() *C {
	return &C{}
}
func staticInitC() {
}
func main() {
	staticInitC()
}
