// Code generated by bento ts-compat from parserVariableDeclaration7.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var (
		a value.Value
		b value.Value
	)
	_ = a
	_ = b
}
