// Code generated by bento ts-compat from anyAsFunctionCall.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	a := x.Call()
	_ = a
	b := x.Call(value.StringValue(value.FromGoString("hello")))
	_ = b
	c := x.Call(x)
	_ = c
}
