// Code generated by bento ts-compat from parserRegularExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.NewRegExpLiteral("(#?-?\\d*\\.\\d\\w*%?)|(@?#?[\\w-?]+%?)", "g")
}
