// Code generated by bento ts-compat from stringLiteralTypesWithTemplateStrings02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	abc := value.FromGoString("AB\r\nC")
	_ = abc
	de_NEWLINE_f := value.FromGoString("DE").ConcatN(value.FromGoString("\n"), value.FromGoString("F"))
	_ = de_NEWLINE_f
}
