// Code generated by bento ts-compat from stringLiteralTypesWithTemplateStrings01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	ABC := value.FromGoString("ABC")
	_ = ABC
	DE_NEWLINE_F := value.FromGoString("DE\r\nF")
	_ = DE_NEWLINE_F
	var G_QUOTE_HI value.BStr
	_ = G_QUOTE_HI
	JK_BACKTICK_L := value.FromGoString("JK`L")
	_ = JK_BACKTICK_L
}
