// Code generated by bento ts-compat from propertyAccessNumericLiterals.es6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	value.NumberToString(0xffffffff)
	value.NumberToString(0o01234)
	value.NumberToString(0b01101101)
	value.NumberToString(1234.)
	value.NumberToString(1e0)
}
