// Code generated by bento ts-compat from computedPropertyNamesDeclarationEmit6_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjN_1U2D_1 struct {
	U2D_1 value.Value `json:"-1"`
	N_1   value.Value `json:"1"`
}

func main() {
	v := value.NewObject().SetKeyed(value.Number(-1), value.NewObject()).SetKeyed(value.Number(1), value.NewObject()).SetKeyed(value.Number(float64(^value.ToInt32(1))), value.NewObject()).SetKeyed(value.Bool(!(1 != 0 && 1 == 1)), value.NewObject())
	_ = v
}
