// Code generated by bento ts-compat from computedPropertyNames9_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(x value.Value) value.Value {
	return value.Undefined
}
func main() {
	v := value.NewObject().SetKeyed(F(value.StringValue(value.FromGoString(""))), value.Number(0)).SetKeyed(F(value.Number(0)), value.Number(0)).SetKeyed(F(value.Bool(true)), value.Number(0))
	_ = v
}
