// Code generated by bento ts-compat from computedPropertyNames5_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	var b bool
	v := value.NewObject().SetKeyed(value.Bool(b), value.Number(0)).SetKeyed(value.Bool(true), value.Number(1)).SetKeyed(value.NewArrayValue([]value.Value{}), value.Number(0)).SetKeyed(value.NewObject(), value.Number(0)).SetKeyed(value.Undefined, value.Undefined).SetKeyed(value.Null, value.Null)
	_ = v
}
