// Code generated by bento ts-compat from computedPropertyNames7_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjN_0 struct {
	N_0 float64 `json:"0"`
}

const (
	EMember float64 = 0
)

func main() {
	v := value.NewObject().SetKeyed(value.Number(EMember), value.Number(0))
	_ = v
}
