// Code generated by bento ts-compat from computedPropertyNames31_ES5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Base struct {
}

func NewBase() *Base {
	return &Base{}
}
func (b *Base) Bar() float64 {
	return 0
}

type C struct {
	Base
}

func NewC() *C {
	return &C{Base: *NewBase()}
}
func (c *C) Foo() float64 {
	_ = func() {
		obj := value.NewObject().SetKeyed(value.Number(c.Base.Bar()), value.NewFunc(func(__a []value.Value) value.Value {
			(func() {
			})()
			return value.Undefined
		}))
		_ = obj
	}
	return 0
}
func main() {
}
