// Code generated by bento ts-compat from computedPropertyNames22_ES5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Bar() float64 {
	obj := value.NewObject().SetKeyed(value.Number(c.Bar()), value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	_ = obj
	return 0
}
func main() {
}
