// Code generated by bento ts-compat from computedPropertyNamesContextualType4_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	o := value.NewObject().SetKeyed(value.StringValue(value.Concat(value.FromGoString(""), value.FromGoString("foo"))), value.StringValue(value.FromGoString(""))).SetKeyed(value.StringValue(value.Concat(value.FromGoString(""), value.FromGoString("bar"))), value.Number(0))
	_ = o
}
