// Code generated by bento ts-compat from objectTypesIdentityWithCallSignaturesDifferingParamCounts2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

var a func(value.BStr, value.BStr) value.BStr

func Foo2(x value.Value) {
}
func Foo3(x value.Value) {
}
func Foo4(x value.Value) {
}
func Foo5(x value.Value) {
}
func Foo13(x value.Value) {
}
func Foo14(x value.Value) {
}
func Foo14b(x value.Value) {
}
func Foo15(x value.Value) {
}
func main() {
}
