// Code generated by bento ts-compat from primtiveTypesAreIdentical.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	EA float64 = 0
)

func Foo1(x value.Value) {
}
func Foo2(x value.Value) {
}
func Foo3(x value.Value) {
}
func Foo4(x value.Value) {
}
func Foo5(x value.Value) {
}
func Foo6(x value.Value) {
}
func Foo7(x value.Value) {
}
func main() {
}
