// Code generated by bento ts-compat from emitStatementsBeforeSuperCall.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Base struct {
}

func NewBase() *Base {
	return &Base{}
}

type Sub struct {
	Base
	P     float64 `json:"p"`
	Field float64 `json:"field"`
}

func NewSub(p float64) *Sub {
	s := &Sub{}
	value.ConsoleLog(value.FromGoString("hi"))
	s.Base = *NewBase()
	s.P = p
	s.Field = 0
	return s
}

type Test struct {
	Base
	P    float64 `json:"p"`
	Prop float64 `json:"prop"`
}

func NewTest(p float64) *Test {
	t := &Test{}
	_ = 1
	t.Base = *NewBase()
	t.P = p
	t.Prop = 1
	return t
}
func main() {
}
