// Code generated by bento ts-compat from mappedTypeAsClauses.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjFoo struct {
	Foo value.BStr `json:"foo"`
}
type ObjNameSeats struct {
	Name  value.BStr `json:"name"`
	Seats float64    `json:"seats"`
}

func F(x value.BStr) value.BStr {
	return x
}
func main() {
	e1 := &ObjFoo{Foo: value.FromGoString("hello")}
	_ = e1
	e2 := value.FromGoString("foo")
	_ = e2
	var primitiveCar *ObjNameSeats
	_ = primitiveCar
	var keys value.BStr
	_ = keys
	var carKeys value.BStr
	_ = carKeys
	F(value.FromGoString("a"))
}
