// Code generated by bento ts-compat from classStaticBlock1.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func staticInitC() {
	{
		a := 1.0
		_ = a
	}
}
func main() {
	a := 2.0
	_ = a
	staticInitC()
}
