// Code generated by bento ts-compat from classStaticBlock12.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var c_p_x value.Value = value.Number(1)

func NewC() *C {
	return &C{}
}
func staticInitC() {
	{
		_ = c_p_x
	}
}
func main() {
	staticInitC()
}
