// Code generated by bento ts-compat from classStaticBlock13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var c_p_x value.Value = value.Number(123)

func NewC() *C {
	return &C{}
}
func (c *C) Foo() float64 {
	return value.ToNumber(c_p_x)
}
func staticInitC() {
	{
		value.ConsoleLog(value.ConsoleValue(c_p_x))
	}
}
func main() {
	staticInitC()
}
