// Code generated by bento ts-compat from classStaticBlock2.ts. DO NOT EDIT.

package main

var b float64 = 2

type C struct {
}

func NewC() *C {
	return &C{}
}
func staticInitC() {
	{
		a := 11.0
		_ = a
		_ = b
	}
	{
		a := 11.0
		_ = a
		_ = b
	}
}
func main() {
	a := 1.0
	_ = a
	staticInitC()
}
