// Code generated by bento ts-compat from anyPlusAny1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	x.Set(value.FromGoString("name"), value.StringValue(value.FromGoString("hello")))
	z := value.Add(x, x)
	_ = z
}
