// Code generated by bento ts-compat from argumentsObjectIterator01_ES5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_num_num struct {
	E0 float64
	E1 float64
	E2 float64
}

func DoubleAndReturnAsArray(x float64, y float64, z float64) Tuple_num_num_num {
	_bt0 := value.NewArray[value.Value](value.Number(x), value.Number(y), value.Number(z))
	result := value.NewArray[value.Value]()
	for _, arg := range _bt0.Elems() {
		result.Push(value.Add(arg, arg))
	}
	return func(_a *value.Array[value.Value]) Tuple_num_num_num {
		return Tuple_num_num_num{E0: value.ToNumber(_a.AtI(0)), E1: value.ToNumber(_a.AtI(1)), E2: value.ToNumber(_a.AtI(2))}
	}(result)
}
func main() {
}
