// Code generated by bento ts-compat from arrayLiteral2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var (
		v30 *value.Array[float64] = value.NewArray[float64](1, 2)
		v31 value.Value
	)
	_ = v30
	_ = v31
}
