// Code generated by bento ts-compat from arrowFunctionWithObjectLiteralBody6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjMessageNameStack struct {
	Name    value.BStr            `json:"name"`
	Message value.BStr            `json:"message"`
	Stack   value.Opt[value.BStr] `json:"stack"`
}
type ObjMessageName struct {
	Name    value.BStr `json:"name"`
	Message value.BStr `json:"message"`
}

func main() {
	a := func() *ObjMessageNameStack {
		return &ObjMessageNameStack{Name: value.FromGoString("foo"), Message: value.FromGoString("bar"), Stack: value.None[value.BStr]()}
	}
	_ = a
	b := func() *ObjMessageNameStack {
		return (&ObjMessageNameStack{Name: value.FromGoString("foo"), Message: value.FromGoString("bar"), Stack: value.None[value.BStr]()})
	}
	_ = b
	c := func() *ObjMessageName {
		return (&ObjMessageName{Name: value.FromGoString("foo"), Message: value.FromGoString("bar")})
	}
	_ = c
	d := func() *ObjMessageNameStack {
		return (&ObjMessageNameStack{Name: value.FromGoString("foo"), Message: value.FromGoString("bar"), Stack: value.None[value.BStr]()})
	}
	_ = d
}
