// Code generated by bento ts-compat from arrowFunctionWithObjectLiteralBody4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := func(a value.Value) value.Value {
		return value.NewObject()
	}
	_ = v
}
