// Code generated by bento ts-compat from asiInES6Classes.ts. DO NOT EDIT.

package main

type ObjDone struct {
	Done bool `json:"done"`
}
type Foo struct {
	Defaults *ObjDone `json:"defaults"`
}

func NewFoo() *Foo {
	f := &Foo{}
	f.Defaults = &ObjDone{Done: false}
	return f
}
func (f *Foo) Bar() float64 {
	return 3
}
func main() {
}
