// Code generated by bento ts-compat from assignmentToExpandingArrayType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjFoo struct {
	Foo value.BStr `json:"foo"`
}

func main() {
	x := value.NewArray[value.Value]()
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
	x.Set(0, value.NewObject().Set(value.FromGoString("foo"), value.StringValue(value.FromGoString("hi"))))
}
