// Code generated by bento ts-compat from assignmentToObject.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjToString struct {
	ToString float64 `json:"toString"`
}

func main() {
	a := &ObjToString{ToString: 5}
	b := value.ObjectFromStruct(a)
	_ = b
	c := a
	_ = c
}
