// Code generated by bento ts-compat from autoAsiForStaticsInClassDeclaration.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var cX value.Value
var cY value.Value

func NewC() *C {
	return &C{}
}
func main() {
}
