// Code generated by bento ts-compat from blockScopedBindingsReassignedInLoop5.ts. DO NOT EDIT.

package main

func main() {
	{
		var (
			x float64 = 1
			y float64 = 2
		)
		for ; x < y; x, y = x+1, y-1 {
			a := func() float64 {
				return func() float64 {
					prev := x
					x++
					return prev
				}() + func() float64 {
					prev := y
					y++
					return prev
				}()
			}
			_ = a
			if x == 1 {
				break
			} else {
				y = 5
			}
		}
	}
}
