// Code generated by bento ts-compat from blockScopedBindingsReassignedInLoop4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() value.Opt[float64] {
	{
		var (
			x float64 = 1
			y float64 = 2
		)
		for ; x < y; x, y = x+1, y-1 {
			a := func() float64 {
				return func() float64 {
					prev := x
					x++
					return prev
				}() + func() float64 {
					prev := y
					y++
					return prev
				}()
			}
			_ = a
			if x == 1 {
				return value.Some[float64](1)
			} else {
				y = 5
			}
		}
	}
	return value.None[float64]()
}
func main() {
}
