// Code generated by bento ts-compat from capturedLetConstInLoop11.ts. DO NOT EDIT.

package main

func Foo() func() float64 {
	for {
		a := 0.0
		switch a {
		case 0:
			return func() float64 {
				return a
			}
		}
	}
}
func main() {
	for {
		x := 1.0
		_ = func() float64 {
			return x
		}
	}
}
