// Code generated by bento ts-compat from captureThisInSuperCall.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjTest struct {
	Test func() `json:"test"`
}
type A struct {
}

func NewA(p value.Value) *A {
	return &A{}
}

type B struct {
	A
}

func NewB() *B {
	b := &B{}
	b.A = *NewA(value.NewObject().Set(value.FromGoString("test"), value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
			b.SomeMethod()
		})()
		return value.Undefined
	})))
	return b
}
func (b *B) SomeMethod() {
}
func main() {
}
