// Code generated by bento ts-compat from capturedVarInLoop.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for i := 0.0; i < 10; i++ {
		var (
			str value.BStr = value.FromGoString("x")
			len float64    = str.Length()
		)
		lambda1 := func(y value.Value) {
		}
		lambda2 := func() {
			lambda1(value.Number(len))
		}
		_ = lambda2
	}
}
