// Code generated by bento ts-compat from checkSuperCallBeforeThisAccessing7.ts. DO NOT EDIT.

package main

type Base struct {
}

func NewBase(func_ func() *Base) *Base {
	return &Base{}
}

type Super struct {
	Base
}

func NewSuper() *Super {
	s := &Super{}
	s.Base = *NewBase(func() *Base {
		return &func() *Super {
			return s
		}().Base
	})
	return s
}
func main() {
}
