// Code generated by bento ts-compat from checkJsObjectLiteralIndexSignatures.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	var _sb0 value.StrBuilder
	n := value.MathRandom()
	s := _sb0.Reset().Num(n).Done()
	numericIndex := value.NewObject().SetKeyed(value.Number(n), value.Number(1))
	value.NumberToFixed(value.ToNumber(numericIndex.GetIndex(n)), 0)
	stringIndex := value.NewObject().SetKeyed(value.StringValue(s), value.Number(1))
	value.NumberToFixed(value.ToNumber(stringIndex.Get(s)), 0)
}
