// Code generated by bento ts-compat from classMemberInitializerScoping2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

var x float64 = 1

type C struct {
	P float64 `json:"p"`
}

func NewC(x_ value.BStr) *C {
	return &C{P: x}
}
func main() {
}
