// Code generated by bento ts-compat from classDeclarationCheckUsedBeforeDefinitionInItself.ts. DO NOT EDIT.

package main

type C3 struct {
}

var c3Intance *C3

func NewC3() *C3 {
	return &C3{}
}
func staticInitC3() {
	c3Intance = NewC3()
}
func main() {
	staticInitC3()
}
