// Code generated by bento ts-compat from commentOnArrayElement14.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	array := value.NewArray[float64](1)
	_ = array
}
