// Code generated by bento ts-compat from commentsOnPropertyOfObjectLiteral1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjIdId1Id2Id3Id4 struct {
	Id  func(value.Value) value.Value `json:"id"`
	Id1 value.BStr                    `json:"id1"`
	Id2 func(value.Value) value.Value `json:"id2"`
	Id3 func(value.Value) value.Value `json:"id3"`
	Id4 func(value.Value) value.Value `json:"id4"`
}

func main() {
	resolve := &ObjIdId1Id2Id3Id4{Id: func(details value.Value) value.Value {
		return details.Get(value.FromGoString("id"))
	}, Id1: value.FromGoString("hello"), Id2: func(details value.Value) value.Value {
		return details.Get(value.FromGoString("id"))
	}, Id3: func(details value.Value) value.Value {
		return details.Get(value.FromGoString("id"))
	}, Id4: func(details value.Value) value.Value {
		return details.Get(value.FromGoString("id"))
	}}
	_ = resolve
}
