// Code generated by bento ts-compat from commentOnBinaryOperator1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.Concat(value.FromGoString("some"), value.FromGoString("text"))
	_ = a
	b := value.Concat(value.FromGoString("some"), value.FromGoString("text"))
	_ = b
	c := value.Concat(value.FromGoString("some"), value.FromGoString("text"))
	_ = c
}
