// Code generated by bento ts-compat from commentOnClassMethod1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type WebControls struct {
}

func NewWebControls() *WebControls {
	return &WebControls{}
}
func (w *WebControls) CreateControl() value.Value {
	return value.Undefined
}
func main() {
}
