// Code generated by bento ts-compat from commentOnArrayElement13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	array := value.NewArray[value.Value]()
	_ = array
}
