// Code generated by bento ts-compat from commaOperator1.ts. DO NOT EDIT.

package main

var v1 float64 = (func() float64 {
	_ = func() float64 {
		_ = func() float64 {
			_ = (func() float64 {
				_ = func() float64 {
					_ = 1
					return 2
				}()
				return 3
			}())
			return 4
		}()
		return 5
	}()
	return (func() float64 {
		_ = 6
		return 7
	}())
}())

func F1() float64 {
	a := 1.0
	return func() float64 {
		_ = func() float64 {
			_ = a
			return v1
		}()
		return a
	}()
}
func main() {
}
