// Code generated by bento ts-compat from commentsBeforeFunctionExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjF struct {
	F func(value.Value) float64 `json:"f"`
}

func main() {
	v := &ObjF{F: func(a value.Value) float64 {
		return 0
	}}
	_ = v
}
