// Code generated by bento ts-compat from computerPropertiesInES5ShouldBeTransformed.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjKey struct {
	Key value.Value `json:"key"`
}

func main() {
	b := func(__0 value.Value) value.Value {
		renamed := __0.GetElem(value.StringValue(value.FromGoString("key")))
		return renamed
	}
	_ = b
}
