// Code generated by bento ts-compat from concatTuples.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_num struct {
	E0 float64
	E1 float64
}

func main() {
	ijs := value.NewArray[Tuple_num_num](Tuple_num_num{E0: 1, E1: 2})
	ijs = ijs.Concat(value.NewArray[Tuple_num_num](Tuple_num_num{E0: 3, E1: 4}, Tuple_num_num{E0: 5, E1: 6}))
}
