// Code generated by bento ts-compat from conditionalExpressions2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X float64 `json:"x"`
}
type ObjG struct {
	G float64 `json:"g"`
}
type ObjH struct {
	H float64 `json:"h"`
}
type ObjXOrNullTag uint8

const (
	ObjXOrNullObjX ObjXOrNullTag = iota
	ObjXOrNullNull
)

type ObjXOrNull struct {
	tag  ObjXOrNullTag
	objX *ObjX
}

func ObjXOrNullOfObjX(v *ObjX) ObjXOrNull {
	return ObjXOrNull{tag: ObjXOrNullObjX, objX: v}
}
func ObjXOrNullOfNull() ObjXOrNull {
	return ObjXOrNull{tag: ObjXOrNullNull}
}
func (u ObjXOrNull) JSONArm() any {
	switch u.tag {
	case ObjXOrNullObjX:
		return u.objX
	case ObjXOrNullNull:
		return nil
	}
	return nil
}

type NumOrNullTag uint8

const (
	NumOrNullNum NumOrNullTag = iota
	NumOrNullNull
)

type NumOrNull struct {
	tag NumOrNullTag
	num float64
}

func NumOrNullOfNum(v float64) NumOrNull {
	return NumOrNull{tag: NumOrNullNum, num: v}
}
func NumOrNullOfNull() NumOrNull {
	return NumOrNull{tag: NumOrNullNull}
}
func (u NumOrNull) JSONArm() any {
	switch u.tag {
	case NumOrNullNum:
		return u.num
	case NumOrNullNull:
		return nil
	}
	return nil
}

type ObjGOrNullTag uint8

const (
	ObjGOrNullObjG ObjGOrNullTag = iota
	ObjGOrNullNull
)

type ObjGOrNull struct {
	tag  ObjGOrNullTag
	objG *ObjG
}

func ObjGOrNullOfObjG(v *ObjG) ObjGOrNull {
	return ObjGOrNull{tag: ObjGOrNullObjG, objG: v}
}
func ObjGOrNullOfNull() ObjGOrNull {
	return ObjGOrNull{tag: ObjGOrNullNull}
}
func (u ObjGOrNull) JSONArm() any {
	switch u.tag {
	case ObjGOrNullObjG:
		return u.objG
	case ObjGOrNullNull:
		return nil
	}
	return nil
}

type ObjHOrNullTag uint8

const (
	ObjHOrNullObjH ObjHOrNullTag = iota
	ObjHOrNullNull
)

type ObjHOrNull struct {
	tag  ObjHOrNullTag
	objH *ObjH
}

func ObjHOrNullOfObjH(v *ObjH) ObjHOrNull {
	return ObjHOrNull{tag: ObjHOrNullObjH, objH: v}
}
func ObjHOrNullOfNull() ObjHOrNull {
	return ObjHOrNull{tag: ObjHOrNullNull}
}
func (u ObjHOrNull) JSONArm() any {
	switch u.tag {
	case ObjHOrNullObjH:
		return u.objH
	case ObjHOrNullNull:
		return nil
	}
	return nil
}
func I() ObjXOrNull {
	if true {
		return ObjXOrNullOfObjX(&ObjX{X: 5})
	} else {
		return ObjXOrNullOfNull()
	}
}
func main() {
	var g ObjGOrNull
	_ = g
	var h *value.Array[ObjHOrNull]
	_ = h
	a := func() NumOrNull {
		if false {
			return NumOrNullOfNum(1)
		}
		return NumOrNullOfNull()
	}()
	_ = a
	b := func() value.Opt[float64] {
		if false {
			return value.None[float64]()
		}
		return value.Some[float64](0)
	}()
	_ = b
	var c float64
	if false {
		c = 1
	} else {
		c = 0
	}
	_ = c
	var d bool
	if false {
		d = false
	} else {
		d = true
	}
	_ = d
	var e value.BStr
	if false {
		e = value.FromGoString("foo")
	} else {
		e = value.FromGoString("bar")
	}
	_ = e
	f := func() value.Opt[value.Value] {
		if false {
			return value.Some[value.Value](value.Null)
		}
		return value.None[value.Value]()
	}()
	_ = f
	g = func() ObjGOrNull {
		if true {
			return ObjGOrNullOfObjG(&ObjG{G: 5})
		}
		return ObjGOrNullOfNull()
	}()
	h = value.NewArray[ObjHOrNull](ObjHOrNullOfObjH(&ObjH{H: 5}), ObjHOrNullOfNull())
}
