// Code generated by bento ts-compat from constDeclarations-scopes2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	c := value.FromGoString("string")
	_ = c
	var n float64
	_ = n
	var b bool
	_ = b
	for c := 0.0; c < 10; n = c {
		c := false
		b = c
	}
}
