// Code generated by bento ts-compat from constructorWithSuperAndPrologue.es5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
}

func NewA() *A {
	a := &A{}
	value.ConsoleLog(value.FromGoString("A"))
	return a
}

type B struct {
	A
}

func NewB() *B {
	b := &B{}
	_ = value.FromGoString("ngInject")
	value.ConsoleLog(value.FromGoString("B"))
	b.A = *NewA()
	return b
}
func main() {
	_ = value.FromGoString("use strict")
}
