// Code generated by bento ts-compat from constructorArgs.ts. DO NOT EDIT.

package main

type ObjValue struct {
	Value float64 `json:"value"`
}
type Super struct {
}

func NewSuper(value_ float64) *Super {
	return &Super{}
}

type Sub struct {
	Super
	Options *ObjValue `json:"options"`
}

func NewSub(options *ObjValue) *Sub {
	return &Sub{Super: *NewSuper(options.Value), Options: options}
}
func main() {
}
