// Code generated by bento ts-compat from constDeclarations.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	c1 := false
	_ = c1
	c2 := 23.0
	_ = c2
	var (
		c3 float64     = 0
		c4 value.BStr  = value.FromGoString("")
		c5 value.Value = value.Null
	)
	_ = c3
	_ = c4
	_ = c5
	for c4 := 0.0; c4 < 9; {
		break
	}
	{
		var (
			c5 float64 = 0
			c6 float64 = 0
		)
		for c5 < c6 {
			break
		}
	}
}
