// Code generated by bento ts-compat from constEnumToStringWithComments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x0 := value.NumberToString(100)
	_ = x0
	x1 := value.NumberToString(100)
	_ = x1
	y0 := value.NumberToString(0.5)
	_ = y0
	y1 := value.NumberToString(0.5)
	_ = y1
	z0 := value.NumberToString(2)
	_ = z0
	z1 := value.NumberToString(2)
	_ = z1
	a0 := value.NumberToString(-1)
	_ = a0
	a1 := value.NumberToString(-1)
	_ = a1
	b0 := value.NumberToString(-1.5)
	_ = b0
	b1 := value.NumberToString(-1.5)
	_ = b1
	c0 := value.NumberToString(-1)
	_ = c0
	c1 := value.NumberToString(-1)
	_ = c1
}
