// Code generated by bento ts-compat from controlFlowManyConsecutiveConditionsNoTimeout.ts. DO NOT EDIT.

package main

const (
	ChoiceOne float64 = 0
	ChoiceTwo float64 = 1
)

func main() {
	choice := ChoiceOne
	choiceOne := ChoiceOne
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	if choice == choiceOne {
	}
	for true {
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
		if choice == choiceOne {
		}
	}
}
