// Code generated by bento ts-compat from contextualTyping16.ts. DO NOT EDIT.

package main

type ObjId struct {
	Id float64 `json:"id"`
}

func main() {
	foo := &ObjId{Id: 4}
	_ = foo
	foo = &ObjId{Id: 5}
}
