// Code generated by bento ts-compat from contextualTyping36.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjId struct {
	Id float64 `json:"id"`
}

func main() {
	foo := value.NewArray[*ObjId](&ObjId{Id: 4}, &ObjId{})
	_ = foo
}
