// Code generated by bento ts-compat from contextualTypeOnYield1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	f := func() *value.Gen[func(float64)] {
		return value.NewGen[func(float64)](func(_bt0 *value.GenCo[func(float64)]) value.Value {
			_ = _bt0.Yield(func(num float64) {
				value.ConsoleLog(value.NumberToString(num))
			})
			return value.Undefined
		})
	}
	_ = f
}
