// Code generated by bento ts-compat from contextualTypingOfObjectLiterals.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.BStr `json:"x"`
}

func F(x value.Value) {
}
func main() {
	var obj1 value.Value
	obj2 := &ObjX{X: value.FromGoString("")}
	obj1 = value.NewObject()
	obj1 = value.ObjectFromStruct(obj2)
	F(value.NewObject())
	F(obj1)
	F(value.ObjectFromStruct(obj2))
}
