// Code generated by bento ts-compat from controlFlowPropertyInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

var LANG value.BStr = value.FromGoString("Turbo Pascal")

type BestLanguage struct {
	Name value.BStr `json:"name"`
}

func NewBestLanguage() *BestLanguage {
	return &BestLanguage{Name: LANG}
}
func main() {
}
