// Code generated by bento ts-compat from contextualTyping29.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(param *value.Array[float64]) {
}
func main() {
	Foo(value.NewArray[float64](1, 3))
}
