// Code generated by bento ts-compat from controlFlowDestructuringParameters.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X float64 `json:"x"`
}

func main() {
	value.MapArray[*ObjX, float64](value.NewArray[*ObjX](&ObjX{X: 1}), func(__0 *ObjX) float64 {
		x := __0.X
		return x
	})
}
