// Code generated by bento ts-compat from controlFlowInitializedDestructuringVariables.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.Opt[value.BStr] `json:"a"`
	B value.Opt[float64]    `json:"b"`
}

func main() {
	var obj *ObjAB
	var a value.BStr
	if _bt0 := obj.A; _bt0.IsUndefined() {
		a = value.FromGoString("0")
	} else {
		a = _bt0.Get()
	}
	var b float64
	if _bt1 := obj.B; _bt1.IsUndefined() {
		b = value.StringToNumber(a)
	} else {
		b = _bt1.Get()
	}
	_ = b
}
