// Code generated by bento ts-compat from declarationEmitNonExportedBindingPattern.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjFoo struct {
	Foo *ObjTest `json:"foo"`
}
type ObjTest struct {
	Test float64 `json:"test"`
}
type ObjA struct {
	A *ObjB `json:"a"`
}
type ObjB struct {
	B *ObjC `json:"b"`
}
type ObjC struct {
	C value.BStr `json:"c"`
}

func GetFoo() *ObjFoo {
	return &ObjFoo{Foo: &ObjTest{Test: 42}}
}
func GetNested() *ObjA {
	return &ObjA{A: &ObjB{B: &ObjC{C: value.FromGoString("d")}}}
}
func main() {
	_bt0 := GetFoo()
	foo := _bt0.Foo
	_ = foo
	_bt1 := GetFoo()
	renamed := _bt1.Foo
	_ = renamed
	_bt2 := GetNested()
	_bt3 := _bt2.A
	_bt4 := _bt3.B
	c := _bt4.C
	_ = c
}
