// Code generated by bento ts-compat from declFileTypeofEnum.ts. DO NOT EDIT.

package main

type ObjFridayMondaySaturdaySundayThursdayTuesdayWednesday struct {
	Monday    float64 `json:"monday"`
	Tuesday   float64 `json:"tuesday"`
	Wednesday float64 `json:"wednesday"`
	Thursday  float64 `json:"thursday"`
	Friday    float64 `json:"friday"`
	Saturday  float64 `json:"saturday"`
	Sunday    float64 `json:"sunday"`
}

const (
	DaysMonday    float64 = 0
	DaysTuesday   float64 = 1
	DaysWednesday float64 = 2
	DaysThursday  float64 = 3
	DaysFriday    float64 = 4
	DaysSaturday  float64 = 5
	DaysSunday    float64 = 6
)

func main() {
	weekendDay := DaysSaturday
	_ = weekendDay
	daysOfMonth := &ObjFridayMondaySaturdaySundayThursdayTuesdayWednesday{Monday: DaysMonday, Tuesday: DaysTuesday, Wednesday: DaysWednesday, Thursday: DaysThursday, Friday: DaysFriday, Saturday: DaysSaturday, Sunday: DaysSunday}
	_ = daysOfMonth
	var daysOfYear *ObjFridayMondaySaturdaySundayThursdayTuesdayWednesday
	_ = daysOfYear
}
