// Code generated by bento ts-compat from declarationEmitMergedAliasWithConst.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBlueGreenRed struct {
	Red   value.BStr `json:"Red"`
	Green value.BStr `json:"Green"`
	Blue  value.BStr `json:"Blue"`
}

func main() {
	Color := &ObjBlueGreenRed{Red: value.FromGoString("Red"), Green: value.FromGoString("Green"), Blue: value.FromGoString("Blue")}
	_ = Color
}
