// Code generated by bento ts-compat from declarationEmitBindingPatternWithReservedWord.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAppConfigDefaultName struct {
	App     value.Value           `json:"app"`
	Default value.Value           `json:"default"`
	Config  value.Value           `json:"config"`
	Name    value.Opt[value.BStr] `json:"name"`
}

func main() {
	getLocales := func(__0 *ObjAppConfigDefaultName) value.Value {
		app := __0.App
		_ = app
		name := __0.Name
		_ = name
		defaultLocalesConfig := __0.Default
		var userLocalesConfig value.Value
		if _bt0 := __0.Config; _bt0.IsUndefined() {
			userLocalesConfig = value.NewObject()
		} else {
			userLocalesConfig = _bt0
		}
		_ = userLocalesConfig
		return defaultLocalesConfig
	}
	_ = getLocales
}
