// Code generated by bento ts-compat from declFileRegressionTests.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjWXYZ struct {
	W value.Value `json:"w"`
	X value.BStr  `json:"x"`
	Y func()      `json:"y"`
	Z float64     `json:"z"`
}

func main() {
	n := &ObjWXYZ{W: value.Null, X: value.FromGoString(""), Y: func() {
	}, Z: 32}
	_ = n
}
