// Code generated by bento ts-compat from declarationEmitPropertyNumericStringKey.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjN_404 struct {
	N_404 value.BStr `json:"404"`
}
type ObjN_100 struct {
	N_100 value.BStr `json:"100"`
}

func main() {
	STATUS := &ObjN_404{N_404: value.FromGoString("not found")}
	_ = STATUS
	hundredStr := value.FromGoString("100")
	obj := value.NewObject().SetKeyed(value.StringValue(hundredStr), value.StringValue(value.FromGoString("foo")))
	_ = obj
	hundredNum := 100.0
	obj2 := value.NewObject().SetKeyed(value.Number(hundredNum), value.StringValue(value.FromGoString("bar")))
	_ = obj2
}
