// Code generated by bento ts-compat from declFileTypeAnnotationBuiltInType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() value.BStr {
	return value.FromGoString("")
}
func Foo2() value.BStr {
	return value.FromGoString("")
}
func Foo3() float64 {
	return 10
}
func Foo4() float64 {
	return 10
}
func Foo5() bool {
	return true
}
func Foo6() bool {
	return false
}
func Foo7() {
	return
}
func Foo8() {
	return
}
func Foo9() value.Value {
	return value.Undefined
}
func Foo10() {
	return
}
func main() {
}
