// Code generated by bento ts-compat from declarationEmitTypeAliasWithTypeParameters2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_bool_str_num struct {
	E0 bool
	E1 value.BStr
	E2 float64
}

func main() {
	y := func(x func() Tuple_bool_str_num) float64 {
		return 1
	}
	_ = y
}
