// Code generated by bento ts-compat from declarationEmitDestructuring1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_str_str_str struct {
	E0 value.BStr
	E1 value.BStr
	E2 value.BStr
}
type Tuple_num_arr_arr struct {
	E0 float64
	E1 *value.Array[bool]
	E2 *value.Array[*value.Array[value.BStr]]
}
type ObjA1B1C1 struct {
	A1 float64    `json:"a1"`
	B1 bool       `json:"b1"`
	C1 value.BStr `json:"c1"`
}
type ObjA2B2 struct {
	A2 float64  `json:"a2"`
	B2 *ObjB1C1 `json:"b2"`
}
type ObjB1C1 struct {
	B1 bool       `json:"b1"`
	C1 value.BStr `json:"c1"`
}

func Foo(__0 Tuple_str_str_str) {
	a := __0.E0
	_ = a
	b := __0.E1
	_ = b
	c := __0.E2
	_ = c
}
func Far(__0 Tuple_num_arr_arr) {
	a := __0.E0
	_ = a
	_bt0 := __0.E1
	b := _bt0.AtI(0)
	_ = b
	_bt1 := __0.E2
	_bt2 := _bt1.AtI(0)
	c := _bt2.AtI(0)
	_ = c
}
func Bar(__0 *ObjA1B1C1) {
	a1 := __0.A1
	_ = a1
	b1 := __0.B1
	_ = b1
	c1 := __0.C1
	_ = c1
}
func Baz(__0 *ObjA2B2) {
	a2 := __0.A2
	_ = a2
	_bt3 := __0.B2
	b1 := _bt3.B1
	_ = b1
	c1 := _bt3.C1
	_ = c1
}
func main() {
}
