// Code generated by bento ts-compat from declarationEmitBindingPatternsFunctionExpr.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjName struct {
	Name value.BStr `json:"name"`
}
type ObjValue struct {
	Value value.BStr `json:"value"`
}

func main() {
	notReferenced := func(__0 *ObjName) {
		alias := __0.Name
		_ = alias
	}
	_ = notReferenced
	duplicateIndetifiers := func(__0 *ObjName) {
		alias := __0.Name
		_ = alias
		alias2 := __0.Name
		_ = alias2
	}
	_ = duplicateIndetifiers
	duplicateIndetifiers2 := func(name value.BStr, __1 *ObjName) {
		alias := __1.Name
		_ = alias
	}
	_ = duplicateIndetifiers2
	duplicateIndetifiers3 := func(__0 *ObjName, __1 *ObjName) {
		alias := __0.Name
		_ = alias
		alias2 := __1.Name
		_ = alias2
	}
	_ = duplicateIndetifiers3
	value_ := value.FromGoString("")
	shadowedVariable := func(__0 *ObjValue) value.BStr {
		alias := __0.Value
		_ = alias
		return value_
	}
	_ = shadowedVariable
}
