// Code generated by bento ts-compat from declarationEmitClassMemberNameConflict2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjWorld struct {
	World float64 `json:"World"`
}
type ObjWorld1 struct {
	World1 float64 `json:"World1"`
}

const (
	HelloWorld float64 = 0
)
const (
	Hello1World1 float64 = 0
)

var Bar value.BStr = value.FromGoString("bar")

type Foo struct {
	Bar    value.BStr `json:"Bar"`
	Hello  *ObjWorld  `json:"Hello"`
	Hello2 *ObjWorld1 `json:"Hello2"`
}

func NewFoo() *Foo {
	return &Foo{Bar: Bar, Hello: &ObjWorld{World: HelloWorld}, Hello2: &ObjWorld1{World1: Hello1World1}}
}
func main() {
}
