// Code generated by bento ts-compat from declFileEmitDeclarationOnlyError1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	hello := value.FromGoString("yo!")
	_ = hello
}
