// Code generated by bento ts-compat from declFileEnumUsedAsValue.ts. DO NOT EDIT.

package main

type ObjABC struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
	C float64 `json:"c"`
}

const (
	EA float64 = 0
	EB float64 = 1
	EC float64 = 2
)

func main() {
	x := &ObjABC{A: EA, B: EB, C: EC}
	_ = x
}
