// Code generated by bento ts-compat from declFileForVarList.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var (
		x value.Value
		y value.Value
		z float64 = 1
	)
	_ = x
	_ = y
	_ = z
	var (
		x1 float64 = 1
		y2 float64 = 2
		z2 float64 = 3
	)
	_ = x1
	_ = y2
	_ = z2
}
