// Code generated by bento ts-compat from defaultOfAnyInStrictNullChecks.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() {
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
				s := e.Message()
				_ = s
			}
		}()
	}()
}
func main() {
}
