// Code generated by bento ts-compat from defineVariables_useDefineForClassFields.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var b func() value.Value
	a := func() value.Value {
		return b()
	}
	b = func() value.Value {
		return value.Null
	}
	a()
}
