// Code generated by bento ts-compat from destructuringPropertyAssignmentNameIsNotAssignmentTarget.ts. DO NOT EDIT.

package main

type ObjValue struct {
	Value float64 `json:"value"`
}

func Qux(bar *ObjValue) {
	var foo float64
	_ = foo
	foo = bar.Value
	x := func() *ObjValue {
		return bar
	}
	_ = x
}
func main() {
}
