// Code generated by bento ts-compat from discriminantsAndTypePredicates.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjType struct {
	Type value.BStr `json:"type"`
}
type AOrBTag uint8

const (
	AOrBA AOrBTag = iota
	AOrBB
)

type AOrB struct {
	tag AOrBTag
	a   *ObjType
	b   *ObjType
}

func AOrBOfA(v *ObjType) AOrB {
	return AOrB{tag: AOrBA, a: v}
}
func AOrBOfB(v *ObjType) AOrB {
	return AOrB{tag: AOrBB, b: v}
}
func (u AOrB) JSONArm() any {
	switch u.tag {
	case AOrBA:
		return u.a
	case AOrBB:
		return u.b
	}
	return nil
}
func IsA(x AOrB) bool {
	return x.tag == AOrBA
}
func IsB(x AOrB) bool {
	return x.tag == AOrBB
}
func Foo1(x AOrB) value.Value {
	_ = x
	if IsA(x) {
		return value.ObjectFromStruct(x.a)
	}
	_ = x.a
	if IsB(x) {
		return value.ObjectFromStruct(x.a)
	}
	_ = x
	return value.Undefined
}
func Foo2(x AOrB) value.Value {
	_ = x
	if x.tag == AOrBA {
		return value.ObjectFromStruct(x.a)
	}
	_ = x.a
	if x.tag == AOrBB {
		return value.ObjectFromStruct(x.a)
	}
	_ = x
	return value.Undefined
}
func main() {
}
