// Code generated by bento ts-compat from divergentAccessorsTypes1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarFoo struct {
	Foo value.Value `json:"foo"`
	Bar value.Value `json:"bar"`
}
type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}

type NumOrStrOrBoolTag uint8

const (
	NumOrStrOrBoolNum NumOrStrOrBoolTag = iota
	NumOrStrOrBoolStr
	NumOrStrOrBoolBool
)

type NumOrStrOrBool struct {
	tag NumOrStrOrBoolTag
	num float64
	str value.BStr
	bl  bool
}

func NumOrStrOrBoolOfNum(v float64) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolNum, num: v}
}
func NumOrStrOrBoolOfStr(v value.BStr) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolStr, str: v}
}
func NumOrStrOrBoolOfBool(v bool) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolBool, bl: v}
}
func (u NumOrStrOrBool) JSONArm() any {
	switch u.tag {
	case NumOrStrOrBoolNum:
		return u.num
	case NumOrStrOrBoolStr:
		return u.str
	case NumOrStrOrBoolBool:
		return u.bl
	}
	return nil
}

type Test1 struct {
}

func NewTest1() *Test1 {
	return &Test1{}
}
func (t *Test1) Foo() value.BStr {
	return value.FromGoString("")
}
func (t *Test1) Bar() NumOrStr {
	return NumOrStrOfStr(value.FromGoString(""))
}
func (t *Test1) SetFoo(s NumOrStr) {
	a := s
	_ = a
	b := s
	_ = b
}
func (t *Test1) SetBar(s NumOrStrOrBool) {
}
func main() {
	{
		t := NewTest1()
		t.SetFoo(NumOrStrOfNum(32))
		m := t.Foo()
		_ = m
		t.SetBar(NumOrStrOrBoolOfNum(42))
		n := t.Bar()
		_ = n
		t.SetBar(NumOrStrOrBoolOfBool(false))
		o := t.Bar()
		_ = o
	}
	{
		t := &ObjBarFoo{}
		t.Foo = value.Number(32)
		m := value.ToString(t.Foo)
		_ = m
		t.Bar = value.Number(42)
		n := value.ToNumber(t.Bar)
		_ = n
		t.Bar = value.Bool(false)
		var o value.Value = t.Bar
		_ = o
	}
	{
		t := &ObjBarFoo{}
		t.Foo = value.Number(32)
		m := value.ToString(t.Foo)
		_ = m
		t.Bar = value.Number(42)
		n := value.ToNumber(t.Bar)
		_ = n
		t.Bar = value.Bool(false)
		o := t.Bar
		_ = o
	}
}
