// Code generated by bento ts-compat from doNotEmitDetachedCommentsAtStartOfConstructor.ts. DO NOT EDIT.

package main

type A struct {
}

func NewA() *A {
	a := &A{}
	x := 10.0
	_ = x
	return a
}

type B struct {
}

func NewB() *B {
	b := &B{}
	y := 10.0
	_ = y
	return b
}

type C struct {
}

func NewC() *C {
	c := &C{}
	x := 10.0
	_ = x
	return c
}

type D struct {
}

func NewD() *D {
	d := &D{}
	y := 10.0
	_ = y
	return d
}
func main() {
}
