// Code generated by bento ts-compat from doNotEmitDetachedCommentsAtStartOfLambdaFunction.ts. DO NOT EDIT.

package main

func main() {
	_ = func() float64 {
		return 0
	}
	_ = func() float64 {
		return 0
	}
	_ = func() float64 {
		return 0
	}
	_ = func() float64 {
		return 0
	}
}
