// Code generated by bento ts-compat from doubleUnderscoreMappedTypes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjProperty1__property2 struct {
	Property1   value.BStr `json:"property1"`
	__property2 value.BStr `json:"__property2"`
}
type ObjProperty1__property2_2 struct {
	Property1   value.Opt[value.BStr] `json:"property1"`
	__property2 value.Opt[value.BStr] `json:"__property2"`
}

func main() {
	ok := &ObjProperty1__property2{Property1: value.FromGoString(""), __property2: value.FromGoString("")}
	_ = ok
	k := value.FromGoString("__property2")
	_ = k
	partial := &ObjProperty1__property2_2{Property1: value.Some[value.BStr](value.FromGoString("")), __property2: value.Some[value.BStr](value.FromGoString(""))}
	_ = partial
}
