// Code generated by bento ts-compat from doWhileLoop.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for {
		if !false {
			break
		}
	}
	var n value.Value
	_ = n
}
