// Code generated by bento ts-compat from doWhileUnreachableCode.ts. DO NOT EDIT.

package main

func Test() float64 {
	foo := 0.0
testLoop:
	for {
		foo++
		continue testLoop
		if !func() bool {
			x := 1.0
			_ = x
			return false
		}() {
			break
		}
	}
	return foo
}
func main() {
}
