// Code generated by bento ts-compat from emitOneLineVariableDeclarationRemoveCommentsFalse.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}
type ObjHoge struct {
	Hoge bool `json:"hoge"`
}

func main() {
	a := &ObjEmpty{}
	_ = a
	b := value.NewObject()
	_ = b
	c := &ObjHoge{Hoge: true}
	_ = c
	d := value.NewObject()
	e := value.NewObject()
	f := d.Call(e)
	_ = f
	g := d.Call(e)
	_ = g
}
