// Code generated by bento ts-compat from emitSuperCallBeforeEmitParameterPropertyDeclaration1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	Blub float64 `json:"blub"`
}

func NewA() *A {
	return &A{Blub: 6}
}

type B struct {
	A
	X float64 `json:"x"`
}

func NewB(x float64) *B {
	b := &B{}
	_ = value.FromGoString("use strict")
	_ = value.FromGoString("someStringForEgngInject")
	b.A = *NewA()
	b.X = x
	return b
}
func main() {
}
