// Code generated by bento ts-compat from emptyExpr.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.NewArray[value.Value](value.NewObject())
}
