// Code generated by bento ts-compat from enumLiteralsSubtypeReduction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	EE0    float64 = 0
	EE1    float64 = 1
	EE2    float64 = 2
	EE3    float64 = 3
	EE4    float64 = 4
	EE5    float64 = 5
	EE6    float64 = 6
	EE7    float64 = 7
	EE8    float64 = 8
	EE9    float64 = 9
	EE10   float64 = 10
	EE11   float64 = 11
	EE12   float64 = 12
	EE13   float64 = 13
	EE14   float64 = 14
	EE15   float64 = 15
	EE16   float64 = 16
	EE17   float64 = 17
	EE18   float64 = 18
	EE19   float64 = 19
	EE20   float64 = 20
	EE21   float64 = 21
	EE22   float64 = 22
	EE23   float64 = 23
	EE24   float64 = 24
	EE25   float64 = 25
	EE26   float64 = 26
	EE27   float64 = 27
	EE28   float64 = 28
	EE29   float64 = 29
	EE30   float64 = 30
	EE31   float64 = 31
	EE32   float64 = 32
	EE33   float64 = 33
	EE34   float64 = 34
	EE35   float64 = 35
	EE36   float64 = 36
	EE37   float64 = 37
	EE38   float64 = 38
	EE39   float64 = 39
	EE40   float64 = 40
	EE41   float64 = 41
	EE42   float64 = 42
	EE43   float64 = 43
	EE44   float64 = 44
	EE45   float64 = 45
	EE46   float64 = 46
	EE47   float64 = 47
	EE48   float64 = 48
	EE49   float64 = 49
	EE50   float64 = 50
	EE51   float64 = 51
	EE52   float64 = 52
	EE53   float64 = 53
	EE54   float64 = 54
	EE55   float64 = 55
	EE56   float64 = 56
	EE57   float64 = 57
	EE58   float64 = 58
	EE59   float64 = 59
	EE60   float64 = 60
	EE61   float64 = 61
	EE62   float64 = 62
	EE63   float64 = 63
	EE64   float64 = 64
	EE65   float64 = 65
	EE66   float64 = 66
	EE67   float64 = 67
	EE68   float64 = 68
	EE69   float64 = 69
	EE70   float64 = 70
	EE71   float64 = 71
	EE72   float64 = 72
	EE73   float64 = 73
	EE74   float64 = 74
	EE75   float64 = 75
	EE76   float64 = 76
	EE77   float64 = 77
	EE78   float64 = 78
	EE79   float64 = 79
	EE80   float64 = 80
	EE81   float64 = 81
	EE82   float64 = 82
	EE83   float64 = 83
	EE84   float64 = 84
	EE85   float64 = 85
	EE86   float64 = 86
	EE87   float64 = 87
	EE88   float64 = 88
	EE89   float64 = 89
	EE90   float64 = 90
	EE91   float64 = 91
	EE92   float64 = 92
	EE93   float64 = 93
	EE94   float64 = 94
	EE95   float64 = 95
	EE96   float64 = 96
	EE97   float64 = 97
	EE98   float64 = 98
	EE99   float64 = 99
	EE100  float64 = 100
	EE101  float64 = 101
	EE102  float64 = 102
	EE103  float64 = 103
	EE104  float64 = 104
	EE105  float64 = 105
	EE106  float64 = 106
	EE107  float64 = 107
	EE108  float64 = 108
	EE109  float64 = 109
	EE110  float64 = 110
	EE111  float64 = 111
	EE112  float64 = 112
	EE113  float64 = 113
	EE114  float64 = 114
	EE115  float64 = 115
	EE116  float64 = 116
	EE117  float64 = 117
	EE118  float64 = 118
	EE119  float64 = 119
	EE120  float64 = 120
	EE121  float64 = 121
	EE122  float64 = 122
	EE123  float64 = 123
	EE124  float64 = 124
	EE125  float64 = 125
	EE126  float64 = 126
	EE127  float64 = 127
	EE128  float64 = 128
	EE129  float64 = 129
	EE130  float64 = 130
	EE131  float64 = 131
	EE132  float64 = 132
	EE133  float64 = 133
	EE134  float64 = 134
	EE135  float64 = 135
	EE136  float64 = 136
	EE137  float64 = 137
	EE138  float64 = 138
	EE139  float64 = 139
	EE140  float64 = 140
	EE141  float64 = 141
	EE142  float64 = 142
	EE143  float64 = 143
	EE144  float64 = 144
	EE145  float64 = 145
	EE146  float64 = 146
	EE147  float64 = 147
	EE148  float64 = 148
	EE149  float64 = 149
	EE150  float64 = 150
	EE151  float64 = 151
	EE152  float64 = 152
	EE153  float64 = 153
	EE154  float64 = 154
	EE155  float64 = 155
	EE156  float64 = 156
	EE157  float64 = 157
	EE158  float64 = 158
	EE159  float64 = 159
	EE160  float64 = 160
	EE161  float64 = 161
	EE162  float64 = 162
	EE163  float64 = 163
	EE164  float64 = 164
	EE165  float64 = 165
	EE166  float64 = 166
	EE167  float64 = 167
	EE168  float64 = 168
	EE169  float64 = 169
	EE170  float64 = 170
	EE171  float64 = 171
	EE172  float64 = 172
	EE173  float64 = 173
	EE174  float64 = 174
	EE175  float64 = 175
	EE176  float64 = 176
	EE177  float64 = 177
	EE178  float64 = 178
	EE179  float64 = 179
	EE180  float64 = 180
	EE181  float64 = 181
	EE182  float64 = 182
	EE183  float64 = 183
	EE184  float64 = 184
	EE185  float64 = 185
	EE186  float64 = 186
	EE187  float64 = 187
	EE188  float64 = 188
	EE189  float64 = 189
	EE190  float64 = 190
	EE191  float64 = 191
	EE192  float64 = 192
	EE193  float64 = 193
	EE194  float64 = 194
	EE195  float64 = 195
	EE196  float64 = 196
	EE197  float64 = 197
	EE198  float64 = 198
	EE199  float64 = 199
	EE200  float64 = 200
	EE201  float64 = 201
	EE202  float64 = 202
	EE203  float64 = 203
	EE204  float64 = 204
	EE205  float64 = 205
	EE206  float64 = 206
	EE207  float64 = 207
	EE208  float64 = 208
	EE209  float64 = 209
	EE210  float64 = 210
	EE211  float64 = 211
	EE212  float64 = 212
	EE213  float64 = 213
	EE214  float64 = 214
	EE215  float64 = 215
	EE216  float64 = 216
	EE217  float64 = 217
	EE218  float64 = 218
	EE219  float64 = 219
	EE220  float64 = 220
	EE221  float64 = 221
	EE222  float64 = 222
	EE223  float64 = 223
	EE224  float64 = 224
	EE225  float64 = 225
	EE226  float64 = 226
	EE227  float64 = 227
	EE228  float64 = 228
	EE229  float64 = 229
	EE230  float64 = 230
	EE231  float64 = 231
	EE232  float64 = 232
	EE233  float64 = 233
	EE234  float64 = 234
	EE235  float64 = 235
	EE236  float64 = 236
	EE237  float64 = 237
	EE238  float64 = 238
	EE239  float64 = 239
	EE240  float64 = 240
	EE241  float64 = 241
	EE242  float64 = 242
	EE243  float64 = 243
	EE244  float64 = 244
	EE245  float64 = 245
	EE246  float64 = 246
	EE247  float64 = 247
	EE248  float64 = 248
	EE249  float64 = 249
	EE250  float64 = 250
	EE251  float64 = 251
	EE252  float64 = 252
	EE253  float64 = 253
	EE254  float64 = 254
	EE255  float64 = 255
	EE256  float64 = 256
	EE257  float64 = 257
	EE258  float64 = 258
	EE259  float64 = 259
	EE260  float64 = 260
	EE261  float64 = 261
	EE262  float64 = 262
	EE263  float64 = 263
	EE264  float64 = 264
	EE265  float64 = 265
	EE266  float64 = 266
	EE267  float64 = 267
	EE268  float64 = 268
	EE269  float64 = 269
	EE270  float64 = 270
	EE271  float64 = 271
	EE272  float64 = 272
	EE273  float64 = 273
	EE274  float64 = 274
	EE275  float64 = 275
	EE276  float64 = 276
	EE277  float64 = 277
	EE278  float64 = 278
	EE279  float64 = 279
	EE280  float64 = 280
	EE281  float64 = 281
	EE282  float64 = 282
	EE283  float64 = 283
	EE284  float64 = 284
	EE285  float64 = 285
	EE286  float64 = 286
	EE287  float64 = 287
	EE288  float64 = 288
	EE289  float64 = 289
	EE290  float64 = 290
	EE291  float64 = 291
	EE292  float64 = 292
	EE293  float64 = 293
	EE294  float64 = 294
	EE295  float64 = 295
	EE296  float64 = 296
	EE297  float64 = 297
	EE298  float64 = 298
	EE299  float64 = 299
	EE300  float64 = 300
	EE301  float64 = 301
	EE302  float64 = 302
	EE303  float64 = 303
	EE304  float64 = 304
	EE305  float64 = 305
	EE306  float64 = 306
	EE307  float64 = 307
	EE308  float64 = 308
	EE309  float64 = 309
	EE310  float64 = 310
	EE311  float64 = 311
	EE312  float64 = 312
	EE313  float64 = 313
	EE314  float64 = 314
	EE315  float64 = 315
	EE316  float64 = 316
	EE317  float64 = 317
	EE318  float64 = 318
	EE319  float64 = 319
	EE320  float64 = 320
	EE321  float64 = 321
	EE322  float64 = 322
	EE323  float64 = 323
	EE324  float64 = 324
	EE325  float64 = 325
	EE326  float64 = 326
	EE327  float64 = 327
	EE328  float64 = 328
	EE329  float64 = 329
	EE330  float64 = 330
	EE331  float64 = 331
	EE332  float64 = 332
	EE333  float64 = 333
	EE334  float64 = 334
	EE335  float64 = 335
	EE336  float64 = 336
	EE337  float64 = 337
	EE338  float64 = 338
	EE339  float64 = 339
	EE340  float64 = 340
	EE341  float64 = 341
	EE342  float64 = 342
	EE343  float64 = 343
	EE344  float64 = 344
	EE345  float64 = 345
	EE346  float64 = 346
	EE347  float64 = 347
	EE348  float64 = 348
	EE349  float64 = 349
	EE350  float64 = 350
	EE351  float64 = 351
	EE352  float64 = 352
	EE353  float64 = 353
	EE354  float64 = 354
	EE355  float64 = 355
	EE356  float64 = 356
	EE357  float64 = 357
	EE358  float64 = 358
	EE359  float64 = 359
	EE360  float64 = 360
	EE361  float64 = 361
	EE362  float64 = 362
	EE363  float64 = 363
	EE364  float64 = 364
	EE365  float64 = 365
	EE366  float64 = 366
	EE367  float64 = 367
	EE368  float64 = 368
	EE369  float64 = 369
	EE370  float64 = 370
	EE371  float64 = 371
	EE372  float64 = 372
	EE373  float64 = 373
	EE374  float64 = 374
	EE375  float64 = 375
	EE376  float64 = 376
	EE377  float64 = 377
	EE378  float64 = 378
	EE379  float64 = 379
	EE380  float64 = 380
	EE381  float64 = 381
	EE382  float64 = 382
	EE383  float64 = 383
	EE384  float64 = 384
	EE385  float64 = 385
	EE386  float64 = 386
	EE387  float64 = 387
	EE388  float64 = 388
	EE389  float64 = 389
	EE390  float64 = 390
	EE391  float64 = 391
	EE392  float64 = 392
	EE393  float64 = 393
	EE394  float64 = 394
	EE395  float64 = 395
	EE396  float64 = 396
	EE397  float64 = 397
	EE398  float64 = 398
	EE399  float64 = 399
	EE400  float64 = 400
	EE401  float64 = 401
	EE402  float64 = 402
	EE403  float64 = 403
	EE404  float64 = 404
	EE405  float64 = 405
	EE406  float64 = 406
	EE407  float64 = 407
	EE408  float64 = 408
	EE409  float64 = 409
	EE410  float64 = 410
	EE411  float64 = 411
	EE412  float64 = 412
	EE413  float64 = 413
	EE414  float64 = 414
	EE415  float64 = 415
	EE416  float64 = 416
	EE417  float64 = 417
	EE418  float64 = 418
	EE419  float64 = 419
	EE420  float64 = 420
	EE421  float64 = 421
	EE422  float64 = 422
	EE423  float64 = 423
	EE424  float64 = 424
	EE425  float64 = 425
	EE426  float64 = 426
	EE427  float64 = 427
	EE428  float64 = 428
	EE429  float64 = 429
	EE430  float64 = 430
	EE431  float64 = 431
	EE432  float64 = 432
	EE433  float64 = 433
	EE434  float64 = 434
	EE435  float64 = 435
	EE436  float64 = 436
	EE437  float64 = 437
	EE438  float64 = 438
	EE439  float64 = 439
	EE440  float64 = 440
	EE441  float64 = 441
	EE442  float64 = 442
	EE443  float64 = 443
	EE444  float64 = 444
	EE445  float64 = 445
	EE446  float64 = 446
	EE447  float64 = 447
	EE448  float64 = 448
	EE449  float64 = 449
	EE450  float64 = 450
	EE451  float64 = 451
	EE452  float64 = 452
	EE453  float64 = 453
	EE454  float64 = 454
	EE455  float64 = 455
	EE456  float64 = 456
	EE457  float64 = 457
	EE458  float64 = 458
	EE459  float64 = 459
	EE460  float64 = 460
	EE461  float64 = 461
	EE462  float64 = 462
	EE463  float64 = 463
	EE464  float64 = 464
	EE465  float64 = 465
	EE466  float64 = 466
	EE467  float64 = 467
	EE468  float64 = 468
	EE469  float64 = 469
	EE470  float64 = 470
	EE471  float64 = 471
	EE472  float64 = 472
	EE473  float64 = 473
	EE474  float64 = 474
	EE475  float64 = 475
	EE476  float64 = 476
	EE477  float64 = 477
	EE478  float64 = 478
	EE479  float64 = 479
	EE480  float64 = 480
	EE481  float64 = 481
	EE482  float64 = 482
	EE483  float64 = 483
	EE484  float64 = 484
	EE485  float64 = 485
	EE486  float64 = 486
	EE487  float64 = 487
	EE488  float64 = 488
	EE489  float64 = 489
	EE490  float64 = 490
	EE491  float64 = 491
	EE492  float64 = 492
	EE493  float64 = 493
	EE494  float64 = 494
	EE495  float64 = 495
	EE496  float64 = 496
	EE497  float64 = 497
	EE498  float64 = 498
	EE499  float64 = 499
	EE500  float64 = 500
	EE501  float64 = 501
	EE502  float64 = 502
	EE503  float64 = 503
	EE504  float64 = 504
	EE505  float64 = 505
	EE506  float64 = 506
	EE507  float64 = 507
	EE508  float64 = 508
	EE509  float64 = 509
	EE510  float64 = 510
	EE511  float64 = 511
	EE512  float64 = 512
	EE513  float64 = 513
	EE514  float64 = 514
	EE515  float64 = 515
	EE516  float64 = 516
	EE517  float64 = 517
	EE518  float64 = 518
	EE519  float64 = 519
	EE520  float64 = 520
	EE521  float64 = 521
	EE522  float64 = 522
	EE523  float64 = 523
	EE524  float64 = 524
	EE525  float64 = 525
	EE526  float64 = 526
	EE527  float64 = 527
	EE528  float64 = 528
	EE529  float64 = 529
	EE530  float64 = 530
	EE531  float64 = 531
	EE532  float64 = 532
	EE533  float64 = 533
	EE534  float64 = 534
	EE535  float64 = 535
	EE536  float64 = 536
	EE537  float64 = 537
	EE538  float64 = 538
	EE539  float64 = 539
	EE540  float64 = 540
	EE541  float64 = 541
	EE542  float64 = 542
	EE543  float64 = 543
	EE544  float64 = 544
	EE545  float64 = 545
	EE546  float64 = 546
	EE547  float64 = 547
	EE548  float64 = 548
	EE549  float64 = 549
	EE550  float64 = 550
	EE551  float64 = 551
	EE552  float64 = 552
	EE553  float64 = 553
	EE554  float64 = 554
	EE555  float64 = 555
	EE556  float64 = 556
	EE557  float64 = 557
	EE558  float64 = 558
	EE559  float64 = 559
	EE560  float64 = 560
	EE561  float64 = 561
	EE562  float64 = 562
	EE563  float64 = 563
	EE564  float64 = 564
	EE565  float64 = 565
	EE566  float64 = 566
	EE567  float64 = 567
	EE568  float64 = 568
	EE569  float64 = 569
	EE570  float64 = 570
	EE571  float64 = 571
	EE572  float64 = 572
	EE573  float64 = 573
	EE574  float64 = 574
	EE575  float64 = 575
	EE576  float64 = 576
	EE577  float64 = 577
	EE578  float64 = 578
	EE579  float64 = 579
	EE580  float64 = 580
	EE581  float64 = 581
	EE582  float64 = 582
	EE583  float64 = 583
	EE584  float64 = 584
	EE585  float64 = 585
	EE586  float64 = 586
	EE587  float64 = 587
	EE588  float64 = 588
	EE589  float64 = 589
	EE590  float64 = 590
	EE591  float64 = 591
	EE592  float64 = 592
	EE593  float64 = 593
	EE594  float64 = 594
	EE595  float64 = 595
	EE596  float64 = 596
	EE597  float64 = 597
	EE598  float64 = 598
	EE599  float64 = 599
	EE600  float64 = 600
	EE601  float64 = 601
	EE602  float64 = 602
	EE603  float64 = 603
	EE604  float64 = 604
	EE605  float64 = 605
	EE606  float64 = 606
	EE607  float64 = 607
	EE608  float64 = 608
	EE609  float64 = 609
	EE610  float64 = 610
	EE611  float64 = 611
	EE612  float64 = 612
	EE613  float64 = 613
	EE614  float64 = 614
	EE615  float64 = 615
	EE616  float64 = 616
	EE617  float64 = 617
	EE618  float64 = 618
	EE619  float64 = 619
	EE620  float64 = 620
	EE621  float64 = 621
	EE622  float64 = 622
	EE623  float64 = 623
	EE624  float64 = 624
	EE625  float64 = 625
	EE626  float64 = 626
	EE627  float64 = 627
	EE628  float64 = 628
	EE629  float64 = 629
	EE630  float64 = 630
	EE631  float64 = 631
	EE632  float64 = 632
	EE633  float64 = 633
	EE634  float64 = 634
	EE635  float64 = 635
	EE636  float64 = 636
	EE637  float64 = 637
	EE638  float64 = 638
	EE639  float64 = 639
	EE640  float64 = 640
	EE641  float64 = 641
	EE642  float64 = 642
	EE643  float64 = 643
	EE644  float64 = 644
	EE645  float64 = 645
	EE646  float64 = 646
	EE647  float64 = 647
	EE648  float64 = 648
	EE649  float64 = 649
	EE650  float64 = 650
	EE651  float64 = 651
	EE652  float64 = 652
	EE653  float64 = 653
	EE654  float64 = 654
	EE655  float64 = 655
	EE656  float64 = 656
	EE657  float64 = 657
	EE658  float64 = 658
	EE659  float64 = 659
	EE660  float64 = 660
	EE661  float64 = 661
	EE662  float64 = 662
	EE663  float64 = 663
	EE664  float64 = 664
	EE665  float64 = 665
	EE666  float64 = 666
	EE667  float64 = 667
	EE668  float64 = 668
	EE669  float64 = 669
	EE670  float64 = 670
	EE671  float64 = 671
	EE672  float64 = 672
	EE673  float64 = 673
	EE674  float64 = 674
	EE675  float64 = 675
	EE676  float64 = 676
	EE677  float64 = 677
	EE678  float64 = 678
	EE679  float64 = 679
	EE680  float64 = 680
	EE681  float64 = 681
	EE682  float64 = 682
	EE683  float64 = 683
	EE684  float64 = 684
	EE685  float64 = 685
	EE686  float64 = 686
	EE687  float64 = 687
	EE688  float64 = 688
	EE689  float64 = 689
	EE690  float64 = 690
	EE691  float64 = 691
	EE692  float64 = 692
	EE693  float64 = 693
	EE694  float64 = 694
	EE695  float64 = 695
	EE696  float64 = 696
	EE697  float64 = 697
	EE698  float64 = 698
	EE699  float64 = 699
	EE700  float64 = 700
	EE701  float64 = 701
	EE702  float64 = 702
	EE703  float64 = 703
	EE704  float64 = 704
	EE705  float64 = 705
	EE706  float64 = 706
	EE707  float64 = 707
	EE708  float64 = 708
	EE709  float64 = 709
	EE710  float64 = 710
	EE711  float64 = 711
	EE712  float64 = 712
	EE713  float64 = 713
	EE714  float64 = 714
	EE715  float64 = 715
	EE716  float64 = 716
	EE717  float64 = 717
	EE718  float64 = 718
	EE719  float64 = 719
	EE720  float64 = 720
	EE721  float64 = 721
	EE722  float64 = 722
	EE723  float64 = 723
	EE724  float64 = 724
	EE725  float64 = 725
	EE726  float64 = 726
	EE727  float64 = 727
	EE728  float64 = 728
	EE729  float64 = 729
	EE730  float64 = 730
	EE731  float64 = 731
	EE732  float64 = 732
	EE733  float64 = 733
	EE734  float64 = 734
	EE735  float64 = 735
	EE736  float64 = 736
	EE737  float64 = 737
	EE738  float64 = 738
	EE739  float64 = 739
	EE740  float64 = 740
	EE741  float64 = 741
	EE742  float64 = 742
	EE743  float64 = 743
	EE744  float64 = 744
	EE745  float64 = 745
	EE746  float64 = 746
	EE747  float64 = 747
	EE748  float64 = 748
	EE749  float64 = 749
	EE750  float64 = 750
	EE751  float64 = 751
	EE752  float64 = 752
	EE753  float64 = 753
	EE754  float64 = 754
	EE755  float64 = 755
	EE756  float64 = 756
	EE757  float64 = 757
	EE758  float64 = 758
	EE759  float64 = 759
	EE760  float64 = 760
	EE761  float64 = 761
	EE762  float64 = 762
	EE763  float64 = 763
	EE764  float64 = 764
	EE765  float64 = 765
	EE766  float64 = 766
	EE767  float64 = 767
	EE768  float64 = 768
	EE769  float64 = 769
	EE770  float64 = 770
	EE771  float64 = 771
	EE772  float64 = 772
	EE773  float64 = 773
	EE774  float64 = 774
	EE775  float64 = 775
	EE776  float64 = 776
	EE777  float64 = 777
	EE778  float64 = 778
	EE779  float64 = 779
	EE780  float64 = 780
	EE781  float64 = 781
	EE782  float64 = 782
	EE783  float64 = 783
	EE784  float64 = 784
	EE785  float64 = 785
	EE786  float64 = 786
	EE787  float64 = 787
	EE788  float64 = 788
	EE789  float64 = 789
	EE790  float64 = 790
	EE791  float64 = 791
	EE792  float64 = 792
	EE793  float64 = 793
	EE794  float64 = 794
	EE795  float64 = 795
	EE796  float64 = 796
	EE797  float64 = 797
	EE798  float64 = 798
	EE799  float64 = 799
	EE800  float64 = 800
	EE801  float64 = 801
	EE802  float64 = 802
	EE803  float64 = 803
	EE804  float64 = 804
	EE805  float64 = 805
	EE806  float64 = 806
	EE807  float64 = 807
	EE808  float64 = 808
	EE809  float64 = 809
	EE810  float64 = 810
	EE811  float64 = 811
	EE812  float64 = 812
	EE813  float64 = 813
	EE814  float64 = 814
	EE815  float64 = 815
	EE816  float64 = 816
	EE817  float64 = 817
	EE818  float64 = 818
	EE819  float64 = 819
	EE820  float64 = 820
	EE821  float64 = 821
	EE822  float64 = 822
	EE823  float64 = 823
	EE824  float64 = 824
	EE825  float64 = 825
	EE826  float64 = 826
	EE827  float64 = 827
	EE828  float64 = 828
	EE829  float64 = 829
	EE830  float64 = 830
	EE831  float64 = 831
	EE832  float64 = 832
	EE833  float64 = 833
	EE834  float64 = 834
	EE835  float64 = 835
	EE836  float64 = 836
	EE837  float64 = 837
	EE838  float64 = 838
	EE839  float64 = 839
	EE840  float64 = 840
	EE841  float64 = 841
	EE842  float64 = 842
	EE843  float64 = 843
	EE844  float64 = 844
	EE845  float64 = 845
	EE846  float64 = 846
	EE847  float64 = 847
	EE848  float64 = 848
	EE849  float64 = 849
	EE850  float64 = 850
	EE851  float64 = 851
	EE852  float64 = 852
	EE853  float64 = 853
	EE854  float64 = 854
	EE855  float64 = 855
	EE856  float64 = 856
	EE857  float64 = 857
	EE858  float64 = 858
	EE859  float64 = 859
	EE860  float64 = 860
	EE861  float64 = 861
	EE862  float64 = 862
	EE863  float64 = 863
	EE864  float64 = 864
	EE865  float64 = 865
	EE866  float64 = 866
	EE867  float64 = 867
	EE868  float64 = 868
	EE869  float64 = 869
	EE870  float64 = 870
	EE871  float64 = 871
	EE872  float64 = 872
	EE873  float64 = 873
	EE874  float64 = 874
	EE875  float64 = 875
	EE876  float64 = 876
	EE877  float64 = 877
	EE878  float64 = 878
	EE879  float64 = 879
	EE880  float64 = 880
	EE881  float64 = 881
	EE882  float64 = 882
	EE883  float64 = 883
	EE884  float64 = 884
	EE885  float64 = 885
	EE886  float64 = 886
	EE887  float64 = 887
	EE888  float64 = 888
	EE889  float64 = 889
	EE890  float64 = 890
	EE891  float64 = 891
	EE892  float64 = 892
	EE893  float64 = 893
	EE894  float64 = 894
	EE895  float64 = 895
	EE896  float64 = 896
	EE897  float64 = 897
	EE898  float64 = 898
	EE899  float64 = 899
	EE900  float64 = 900
	EE901  float64 = 901
	EE902  float64 = 902
	EE903  float64 = 903
	EE904  float64 = 904
	EE905  float64 = 905
	EE906  float64 = 906
	EE907  float64 = 907
	EE908  float64 = 908
	EE909  float64 = 909
	EE910  float64 = 910
	EE911  float64 = 911
	EE912  float64 = 912
	EE913  float64 = 913
	EE914  float64 = 914
	EE915  float64 = 915
	EE916  float64 = 916
	EE917  float64 = 917
	EE918  float64 = 918
	EE919  float64 = 919
	EE920  float64 = 920
	EE921  float64 = 921
	EE922  float64 = 922
	EE923  float64 = 923
	EE924  float64 = 924
	EE925  float64 = 925
	EE926  float64 = 926
	EE927  float64 = 927
	EE928  float64 = 928
	EE929  float64 = 929
	EE930  float64 = 930
	EE931  float64 = 931
	EE932  float64 = 932
	EE933  float64 = 933
	EE934  float64 = 934
	EE935  float64 = 935
	EE936  float64 = 936
	EE937  float64 = 937
	EE938  float64 = 938
	EE939  float64 = 939
	EE940  float64 = 940
	EE941  float64 = 941
	EE942  float64 = 942
	EE943  float64 = 943
	EE944  float64 = 944
	EE945  float64 = 945
	EE946  float64 = 946
	EE947  float64 = 947
	EE948  float64 = 948
	EE949  float64 = 949
	EE950  float64 = 950
	EE951  float64 = 951
	EE952  float64 = 952
	EE953  float64 = 953
	EE954  float64 = 954
	EE955  float64 = 955
	EE956  float64 = 956
	EE957  float64 = 957
	EE958  float64 = 958
	EE959  float64 = 959
	EE960  float64 = 960
	EE961  float64 = 961
	EE962  float64 = 962
	EE963  float64 = 963
	EE964  float64 = 964
	EE965  float64 = 965
	EE966  float64 = 966
	EE967  float64 = 967
	EE968  float64 = 968
	EE969  float64 = 969
	EE970  float64 = 970
	EE971  float64 = 971
	EE972  float64 = 972
	EE973  float64 = 973
	EE974  float64 = 974
	EE975  float64 = 975
	EE976  float64 = 976
	EE977  float64 = 977
	EE978  float64 = 978
	EE979  float64 = 979
	EE980  float64 = 980
	EE981  float64 = 981
	EE982  float64 = 982
	EE983  float64 = 983
	EE984  float64 = 984
	EE985  float64 = 985
	EE986  float64 = 986
	EE987  float64 = 987
	EE988  float64 = 988
	EE989  float64 = 989
	EE990  float64 = 990
	EE991  float64 = 991
	EE992  float64 = 992
	EE993  float64 = 993
	EE994  float64 = 994
	EE995  float64 = 995
	EE996  float64 = 996
	EE997  float64 = 997
	EE998  float64 = 998
	EE999  float64 = 999
	EE1000 float64 = 1000
	EE1001 float64 = 1001
	EE1002 float64 = 1002
	EE1003 float64 = 1003
	EE1004 float64 = 1004
	EE1005 float64 = 1005
	EE1006 float64 = 1006
	EE1007 float64 = 1007
	EE1008 float64 = 1008
	EE1009 float64 = 1009
	EE1010 float64 = 1010
	EE1011 float64 = 1011
	EE1012 float64 = 1012
	EE1013 float64 = 1013
	EE1014 float64 = 1014
	EE1015 float64 = 1015
	EE1016 float64 = 1016
	EE1017 float64 = 1017
	EE1018 float64 = 1018
	EE1019 float64 = 1019
	EE1020 float64 = 1020
	EE1021 float64 = 1021
	EE1022 float64 = 1022
	EE1023 float64 = 1023
)

func Run(a float64) value.Opt[*value.Array[float64]] {
	switch a {
	case 0:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE0, EE1))
	case 2:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE2, EE3))
	case 4:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE4, EE5))
	case 6:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE6, EE7))
	case 8:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE8, EE9))
	case 10:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE10, EE11))
	case 12:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE12, EE13))
	case 14:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE14, EE15))
	case 16:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE16, EE17))
	case 18:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE18, EE19))
	case 20:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE20, EE21))
	case 22:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE22, EE23))
	case 24:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE24, EE25))
	case 26:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE26, EE27))
	case 28:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE28, EE29))
	case 30:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE30, EE31))
	case 32:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE32, EE33))
	case 34:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE34, EE35))
	case 36:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE36, EE37))
	case 38:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE38, EE39))
	case 40:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE40, EE41))
	case 42:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE42, EE43))
	case 44:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE44, EE45))
	case 46:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE46, EE47))
	case 48:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE48, EE49))
	case 50:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE50, EE51))
	case 52:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE52, EE53))
	case 54:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE54, EE55))
	case 56:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE56, EE57))
	case 58:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE58, EE59))
	case 60:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE60, EE61))
	case 62:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE62, EE63))
	case 64:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE64, EE65))
	case 66:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE66, EE67))
	case 68:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE68, EE69))
	case 70:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE70, EE71))
	case 72:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE72, EE73))
	case 74:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE74, EE75))
	case 76:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE76, EE77))
	case 78:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE78, EE79))
	case 80:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE80, EE81))
	case 82:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE82, EE83))
	case 84:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE84, EE85))
	case 86:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE86, EE87))
	case 88:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE88, EE89))
	case 90:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE90, EE91))
	case 92:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE92, EE93))
	case 94:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE94, EE95))
	case 96:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE96, EE97))
	case 98:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE98, EE99))
	case 100:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE100, EE101))
	case 102:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE102, EE103))
	case 104:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE104, EE105))
	case 106:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE106, EE107))
	case 108:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE108, EE109))
	case 110:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE110, EE111))
	case 112:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE112, EE113))
	case 114:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE114, EE115))
	case 116:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE116, EE117))
	case 118:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE118, EE119))
	case 120:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE120, EE121))
	case 122:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE122, EE123))
	case 124:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE124, EE125))
	case 126:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE126, EE127))
	case 128:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE128, EE129))
	case 130:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE130, EE131))
	case 132:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE132, EE133))
	case 134:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE134, EE135))
	case 136:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE136, EE137))
	case 138:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE138, EE139))
	case 140:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE140, EE141))
	case 142:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE142, EE143))
	case 144:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE144, EE145))
	case 146:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE146, EE147))
	case 148:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE148, EE149))
	case 150:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE150, EE151))
	case 152:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE152, EE153))
	case 154:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE154, EE155))
	case 156:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE156, EE157))
	case 158:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE158, EE159))
	case 160:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE160, EE161))
	case 162:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE162, EE163))
	case 164:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE164, EE165))
	case 166:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE166, EE167))
	case 168:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE168, EE169))
	case 170:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE170, EE171))
	case 172:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE172, EE173))
	case 174:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE174, EE175))
	case 176:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE176, EE177))
	case 178:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE178, EE179))
	case 180:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE180, EE181))
	case 182:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE182, EE183))
	case 184:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE184, EE185))
	case 186:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE186, EE187))
	case 188:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE188, EE189))
	case 190:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE190, EE191))
	case 192:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE192, EE193))
	case 194:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE194, EE195))
	case 196:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE196, EE197))
	case 198:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE198, EE199))
	case 200:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE200, EE201))
	case 202:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE202, EE203))
	case 204:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE204, EE205))
	case 206:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE206, EE207))
	case 208:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE208, EE209))
	case 210:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE210, EE211))
	case 212:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE212, EE213))
	case 214:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE214, EE215))
	case 216:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE216, EE217))
	case 218:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE218, EE219))
	case 220:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE220, EE221))
	case 222:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE222, EE223))
	case 224:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE224, EE225))
	case 226:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE226, EE227))
	case 228:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE228, EE229))
	case 230:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE230, EE231))
	case 232:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE232, EE233))
	case 234:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE234, EE235))
	case 236:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE236, EE237))
	case 238:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE238, EE239))
	case 240:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE240, EE241))
	case 242:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE242, EE243))
	case 244:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE244, EE245))
	case 246:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE246, EE247))
	case 248:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE248, EE249))
	case 250:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE250, EE251))
	case 252:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE252, EE253))
	case 254:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE254, EE255))
	case 256:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE256, EE257))
	case 258:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE258, EE259))
	case 260:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE260, EE261))
	case 262:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE262, EE263))
	case 264:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE264, EE265))
	case 266:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE266, EE267))
	case 268:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE268, EE269))
	case 270:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE270, EE271))
	case 272:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE272, EE273))
	case 274:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE274, EE275))
	case 276:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE276, EE277))
	case 278:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE278, EE279))
	case 280:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE280, EE281))
	case 282:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE282, EE283))
	case 284:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE284, EE285))
	case 286:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE286, EE287))
	case 288:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE288, EE289))
	case 290:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE290, EE291))
	case 292:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE292, EE293))
	case 294:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE294, EE295))
	case 296:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE296, EE297))
	case 298:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE298, EE299))
	case 300:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE300, EE301))
	case 302:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE302, EE303))
	case 304:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE304, EE305))
	case 306:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE306, EE307))
	case 308:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE308, EE309))
	case 310:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE310, EE311))
	case 312:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE312, EE313))
	case 314:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE314, EE315))
	case 316:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE316, EE317))
	case 318:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE318, EE319))
	case 320:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE320, EE321))
	case 322:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE322, EE323))
	case 324:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE324, EE325))
	case 326:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE326, EE327))
	case 328:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE328, EE329))
	case 330:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE330, EE331))
	case 332:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE332, EE333))
	case 334:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE334, EE335))
	case 336:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE336, EE337))
	case 338:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE338, EE339))
	case 340:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE340, EE341))
	case 342:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE342, EE343))
	case 344:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE344, EE345))
	case 346:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE346, EE347))
	case 348:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE348, EE349))
	case 350:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE350, EE351))
	case 352:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE352, EE353))
	case 354:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE354, EE355))
	case 356:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE356, EE357))
	case 358:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE358, EE359))
	case 360:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE360, EE361))
	case 362:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE362, EE363))
	case 364:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE364, EE365))
	case 366:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE366, EE367))
	case 368:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE368, EE369))
	case 370:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE370, EE371))
	case 372:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE372, EE373))
	case 374:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE374, EE375))
	case 376:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE376, EE377))
	case 378:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE378, EE379))
	case 380:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE380, EE381))
	case 382:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE382, EE383))
	case 384:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE384, EE385))
	case 386:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE386, EE387))
	case 388:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE388, EE389))
	case 390:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE390, EE391))
	case 392:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE392, EE393))
	case 394:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE394, EE395))
	case 396:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE396, EE397))
	case 398:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE398, EE399))
	case 400:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE400, EE401))
	case 402:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE402, EE403))
	case 404:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE404, EE405))
	case 406:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE406, EE407))
	case 408:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE408, EE409))
	case 410:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE410, EE411))
	case 412:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE412, EE413))
	case 414:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE414, EE415))
	case 416:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE416, EE417))
	case 418:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE418, EE419))
	case 420:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE420, EE421))
	case 422:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE422, EE423))
	case 424:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE424, EE425))
	case 426:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE426, EE427))
	case 428:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE428, EE429))
	case 430:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE430, EE431))
	case 432:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE432, EE433))
	case 434:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE434, EE435))
	case 436:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE436, EE437))
	case 438:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE438, EE439))
	case 440:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE440, EE441))
	case 442:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE442, EE443))
	case 444:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE444, EE445))
	case 446:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE446, EE447))
	case 448:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE448, EE449))
	case 450:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE450, EE451))
	case 452:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE452, EE453))
	case 454:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE454, EE455))
	case 456:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE456, EE457))
	case 458:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE458, EE459))
	case 460:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE460, EE461))
	case 462:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE462, EE463))
	case 464:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE464, EE465))
	case 466:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE466, EE467))
	case 468:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE468, EE469))
	case 470:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE470, EE471))
	case 472:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE472, EE473))
	case 474:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE474, EE475))
	case 476:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE476, EE477))
	case 478:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE478, EE479))
	case 480:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE480, EE481))
	case 482:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE482, EE483))
	case 484:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE484, EE485))
	case 486:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE486, EE487))
	case 488:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE488, EE489))
	case 490:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE490, EE491))
	case 492:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE492, EE493))
	case 494:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE494, EE495))
	case 496:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE496, EE497))
	case 498:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE498, EE499))
	case 500:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE500, EE501))
	case 502:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE502, EE503))
	case 504:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE504, EE505))
	case 506:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE506, EE507))
	case 508:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE508, EE509))
	case 510:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE510, EE511))
	case 512:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE512, EE513))
	case 514:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE514, EE515))
	case 516:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE516, EE517))
	case 518:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE518, EE519))
	case 520:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE520, EE521))
	case 522:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE522, EE523))
	case 524:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE524, EE525))
	case 526:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE526, EE527))
	case 528:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE528, EE529))
	case 530:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE530, EE531))
	case 532:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE532, EE533))
	case 534:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE534, EE535))
	case 536:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE536, EE537))
	case 538:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE538, EE539))
	case 540:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE540, EE541))
	case 542:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE542, EE543))
	case 544:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE544, EE545))
	case 546:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE546, EE547))
	case 548:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE548, EE549))
	case 550:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE550, EE551))
	case 552:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE552, EE553))
	case 554:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE554, EE555))
	case 556:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE556, EE557))
	case 558:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE558, EE559))
	case 560:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE560, EE561))
	case 562:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE562, EE563))
	case 564:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE564, EE565))
	case 566:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE566, EE567))
	case 568:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE568, EE569))
	case 570:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE570, EE571))
	case 572:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE572, EE573))
	case 574:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE574, EE575))
	case 576:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE576, EE577))
	case 578:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE578, EE579))
	case 580:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE580, EE581))
	case 582:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE582, EE583))
	case 584:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE584, EE585))
	case 586:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE586, EE587))
	case 588:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE588, EE589))
	case 590:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE590, EE591))
	case 592:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE592, EE593))
	case 594:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE594, EE595))
	case 596:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE596, EE597))
	case 598:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE598, EE599))
	case 600:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE600, EE601))
	case 602:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE602, EE603))
	case 604:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE604, EE605))
	case 606:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE606, EE607))
	case 608:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE608, EE609))
	case 610:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE610, EE611))
	case 612:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE612, EE613))
	case 614:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE614, EE615))
	case 616:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE616, EE617))
	case 618:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE618, EE619))
	case 620:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE620, EE621))
	case 622:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE622, EE623))
	case 624:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE624, EE625))
	case 626:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE626, EE627))
	case 628:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE628, EE629))
	case 630:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE630, EE631))
	case 632:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE632, EE633))
	case 634:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE634, EE635))
	case 636:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE636, EE637))
	case 638:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE638, EE639))
	case 640:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE640, EE641))
	case 642:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE642, EE643))
	case 644:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE644, EE645))
	case 646:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE646, EE647))
	case 648:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE648, EE649))
	case 650:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE650, EE651))
	case 652:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE652, EE653))
	case 654:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE654, EE655))
	case 656:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE656, EE657))
	case 658:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE658, EE659))
	case 660:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE660, EE661))
	case 662:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE662, EE663))
	case 664:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE664, EE665))
	case 666:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE666, EE667))
	case 668:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE668, EE669))
	case 670:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE670, EE671))
	case 672:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE672, EE673))
	case 674:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE674, EE675))
	case 676:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE676, EE677))
	case 678:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE678, EE679))
	case 680:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE680, EE681))
	case 682:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE682, EE683))
	case 684:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE684, EE685))
	case 686:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE686, EE687))
	case 688:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE688, EE689))
	case 690:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE690, EE691))
	case 692:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE692, EE693))
	case 694:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE694, EE695))
	case 696:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE696, EE697))
	case 698:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE698, EE699))
	case 700:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE700, EE701))
	case 702:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE702, EE703))
	case 704:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE704, EE705))
	case 706:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE706, EE707))
	case 708:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE708, EE709))
	case 710:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE710, EE711))
	case 712:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE712, EE713))
	case 714:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE714, EE715))
	case 716:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE716, EE717))
	case 718:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE718, EE719))
	case 720:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE720, EE721))
	case 722:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE722, EE723))
	case 724:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE724, EE725))
	case 726:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE726, EE727))
	case 728:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE728, EE729))
	case 730:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE730, EE731))
	case 732:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE732, EE733))
	case 734:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE734, EE735))
	case 736:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE736, EE737))
	case 738:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE738, EE739))
	case 740:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE740, EE741))
	case 742:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE742, EE743))
	case 744:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE744, EE745))
	case 746:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE746, EE747))
	case 748:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE748, EE749))
	case 750:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE750, EE751))
	case 752:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE752, EE753))
	case 754:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE754, EE755))
	case 756:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE756, EE757))
	case 758:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE758, EE759))
	case 760:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE760, EE761))
	case 762:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE762, EE763))
	case 764:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE764, EE765))
	case 766:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE766, EE767))
	case 768:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE768, EE769))
	case 770:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE770, EE771))
	case 772:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE772, EE773))
	case 774:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE774, EE775))
	case 776:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE776, EE777))
	case 778:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE778, EE779))
	case 780:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE780, EE781))
	case 782:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE782, EE783))
	case 784:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE784, EE785))
	case 786:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE786, EE787))
	case 788:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE788, EE789))
	case 790:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE790, EE791))
	case 792:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE792, EE793))
	case 794:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE794, EE795))
	case 796:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE796, EE797))
	case 798:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE798, EE799))
	case 800:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE800, EE801))
	case 802:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE802, EE803))
	case 804:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE804, EE805))
	case 806:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE806, EE807))
	case 808:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE808, EE809))
	case 810:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE810, EE811))
	case 812:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE812, EE813))
	case 814:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE814, EE815))
	case 816:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE816, EE817))
	case 818:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE818, EE819))
	case 820:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE820, EE821))
	case 822:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE822, EE823))
	case 824:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE824, EE825))
	case 826:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE826, EE827))
	case 828:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE828, EE829))
	case 830:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE830, EE831))
	case 832:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE832, EE833))
	case 834:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE834, EE835))
	case 836:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE836, EE837))
	case 838:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE838, EE839))
	case 840:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE840, EE841))
	case 842:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE842, EE843))
	case 844:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE844, EE845))
	case 846:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE846, EE847))
	case 848:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE848, EE849))
	case 850:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE850, EE851))
	case 852:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE852, EE853))
	case 854:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE854, EE855))
	case 856:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE856, EE857))
	case 858:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE858, EE859))
	case 860:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE860, EE861))
	case 862:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE862, EE863))
	case 864:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE864, EE865))
	case 866:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE866, EE867))
	case 868:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE868, EE869))
	case 870:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE870, EE871))
	case 872:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE872, EE873))
	case 874:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE874, EE875))
	case 876:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE876, EE877))
	case 878:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE878, EE879))
	case 880:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE880, EE881))
	case 882:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE882, EE883))
	case 884:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE884, EE885))
	case 886:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE886, EE887))
	case 888:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE888, EE889))
	case 890:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE890, EE891))
	case 892:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE892, EE893))
	case 894:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE894, EE895))
	case 896:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE896, EE897))
	case 898:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE898, EE899))
	case 900:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE900, EE901))
	case 902:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE902, EE903))
	case 904:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE904, EE905))
	case 906:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE906, EE907))
	case 908:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE908, EE909))
	case 910:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE910, EE911))
	case 912:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE912, EE913))
	case 914:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE914, EE915))
	case 916:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE916, EE917))
	case 918:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE918, EE919))
	case 920:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE920, EE921))
	case 922:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE922, EE923))
	case 924:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE924, EE925))
	case 926:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE926, EE927))
	case 928:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE928, EE929))
	case 930:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE930, EE931))
	case 932:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE932, EE933))
	case 934:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE934, EE935))
	case 936:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE936, EE937))
	case 938:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE938, EE939))
	case 940:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE940, EE941))
	case 942:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE942, EE943))
	case 944:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE944, EE945))
	case 946:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE946, EE947))
	case 948:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE948, EE949))
	case 950:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE950, EE951))
	case 952:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE952, EE953))
	case 954:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE954, EE955))
	case 956:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE956, EE957))
	case 958:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE958, EE959))
	case 960:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE960, EE961))
	case 962:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE962, EE963))
	case 964:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE964, EE965))
	case 966:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE966, EE967))
	case 968:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE968, EE969))
	case 970:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE970, EE971))
	case 972:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE972, EE973))
	case 974:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE974, EE975))
	case 976:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE976, EE977))
	case 978:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE978, EE979))
	case 980:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE980, EE981))
	case 982:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE982, EE983))
	case 984:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE984, EE985))
	case 986:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE986, EE987))
	case 988:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE988, EE989))
	case 990:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE990, EE991))
	case 992:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE992, EE993))
	case 994:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE994, EE995))
	case 996:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE996, EE997))
	case 998:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE998, EE999))
	case 1000:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1000, EE1001))
	case 1002:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1002, EE1003))
	case 1004:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1004, EE1005))
	case 1006:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1006, EE1007))
	case 1008:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1008, EE1009))
	case 1010:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1010, EE1011))
	case 1012:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1012, EE1013))
	case 1014:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1014, EE1015))
	case 1016:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1016, EE1017))
	case 1018:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1018, EE1019))
	case 1020:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1020, EE1021))
	case 1022:
		return value.Some[*value.Array[float64]](value.NewArray[float64](EE1022, EE1023))
	}
	return value.None[*value.Array[float64]]()
}
func main() {
}
