// Code generated by bento ts-compat from enumInitializersWithExponents.ts. DO NOT EDIT.

package main

const (
	EA float64 = 1000
	EB float64 = 10000000000000000000000000
	EC float64 = 0.001
	ED float64 = 0.000000001
	EE float64 = 1
	EF float64 = 10000000000000000000000000
)

func main() {
}
