// Code generated by bento ts-compat from es2017basicAsync.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type AsyncClass struct {
	AsyncPropFunc      func() *value.Promise[value.Unit] `json:"asyncPropFunc"`
	AsyncPropNamedFunc func() *value.Promise[value.Unit] `json:"asyncPropNamedFunc"`
	AsyncPropArrowFunc func() *value.Promise[value.Unit] `json:"asyncPropArrowFunc"`
}

func NewAsyncClass() *AsyncClass {
	a := &AsyncClass{}
	a.AsyncPropFunc = func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt7 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt7, 2)
		})
	}
	a.AsyncPropNamedFunc = func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt8 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt8, 2)
		})
	}
	a.AsyncPropArrowFunc = func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt9 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt9, 2)
		})
	}
	return a
}
func (a *AsyncClass) AsyncMethod() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt10 *value.AsyncCo) {
		_ = value.AwaitValue[float64](_bt10, 2)
	})
}
func AsyncFunc() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
		_ = value.AwaitValue[float64](_bt0, 0)
	})
}
func AsyncIIFE() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt1 *value.AsyncCo) {
		_ = value.AwaitValue[float64](_bt1, 0)
		_ = value.Await(_bt1, (func() *value.Promise[value.Unit] {
			return value.RunAsyncVoid(func(_bt2 *value.AsyncCo) {
				_ = value.AwaitValue[float64](_bt2, 1)
			})
		})())
		_ = value.Await(_bt1, (func() *value.Promise[value.Unit] {
			return value.RunAsyncVoid(func(_bt3 *value.AsyncCo) {
				_ = value.AwaitValue[float64](_bt3, 1)
			})
		})())
		_ = value.Await(_bt1, (func() *value.Promise[value.Unit] {
			return value.RunAsyncVoid(func(_bt4 *value.AsyncCo) {
				_ = value.AwaitValue[float64](_bt4, 1)
			})
		})())
	})
}
func main() {
	_ = func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt5 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt5, 0)
		})
	}
	asyncArrowFunc := func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt6 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt6, 0)
		})
	}
	_ = asyncArrowFunc
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
