// Code generated by bento ts-compat from es5-asyncFunctionLongObjectLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjABCDE struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
	C float64 `json:"c"`
	D float64 `json:"d"`
	E float64 `json:"e"`
}
type ObjABCDEFGHIJ struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
	C float64 `json:"c"`
	D float64 `json:"d"`
	E float64 `json:"e"`
	F float64 `json:"f"`
	G float64 `json:"g"`
	H float64 `json:"h"`
	I float64 `json:"i"`
	J float64 `json:"j"`
}

func main() {
	fooShort := func() *value.Promise[*ObjABCDE] {
		return value.RunAsync[*ObjABCDE](func(_bt0 *value.AsyncCo) *ObjABCDE {
			return &ObjABCDE{A: value.Await(_bt0, value.Resolved[float64](0)), B: value.Await(_bt0, value.Resolved[float64](1)), C: value.Await(_bt0, value.Resolved[float64](2)), D: value.Await(_bt0, value.Resolved[float64](3)), E: value.Await(_bt0, value.Resolved[float64](4))}
		})
	}
	_ = fooShort
	fooLong := func() *value.Promise[*ObjABCDEFGHIJ] {
		return value.RunAsync[*ObjABCDEFGHIJ](func(_bt1 *value.AsyncCo) *ObjABCDEFGHIJ {
			return &ObjABCDEFGHIJ{A: value.Await(_bt1, value.Resolved[float64](0)), B: value.Await(_bt1, value.Resolved[float64](1)), C: value.Await(_bt1, value.Resolved[float64](2)), D: value.Await(_bt1, value.Resolved[float64](3)), E: value.Await(_bt1, value.Resolved[float64](4)), F: value.Await(_bt1, value.Resolved[float64](5)), G: value.Await(_bt1, value.Resolved[float64](6)), H: value.Await(_bt1, value.Resolved[float64](7)), I: value.Await(_bt1, value.Resolved[float64](8)), J: value.Await(_bt1, value.Resolved[float64](9))}
		})
	}
	_ = fooLong
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
