// Code generated by bento ts-compat from escapedReservedCompilerNamedIdentifier.ts. DO NOT EDIT.

package main

type Obj__proto__ struct {
	__proto__ float64 `json:"__proto__"`
}
type Obj___proto__ struct {
	___proto__ float64 `json:"___proto__"`
}
type Obj_proto__ struct {
	_proto__ float64 `json:"_proto__"`
}

func main() {
	__proto__ := 10.0
	_ = __proto__
	o := &Obj__proto__{__proto__: 0}
	b := o.__proto__
	_ = b
	o1 := &Obj__proto__{__proto__: 0}
	b1 := o1.__proto__
	_ = b1
	___proto__ := 10.0
	_ = ___proto__
	o2 := &Obj___proto__{___proto__: 0}
	b2 := o2.___proto__
	_ = b2
	o3 := &Obj___proto__{___proto__: 0}
	b3 := o3.___proto__
	_ = b3
	_proto__ := 10.0
	_ = _proto__
	o4 := &Obj_proto__{_proto__: 0}
	b4 := o4._proto__
	_ = b4
	o5 := &Obj_proto__{_proto__: 0}
	b5 := o5._proto__
	_ = b5
}
