// Code generated by bento ts-compat from exportObjectRest.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X value.BStr `json:"x"`
	Y value.BStr `json:"y"`
}
type ObjY struct {
	Y value.BStr `json:"y"`
}

func main() {
	_bt0 := &ObjXY{X: value.FromGoString("x"), Y: value.FromGoString("y")}
	x := _bt0.X
	_ = x
	rest := &ObjY{Y: _bt0.Y}
	_ = rest
}
