// Code generated by bento ts-compat from extendedUnicodeEscapeSequenceIdentifiers.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := 12.0
	aa := 12.0
	value.ConsoleLog(value.NumberToString(a + aa))
}
