// Code generated by bento ts-compat from forInStatement1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var expr value.Value
	for range expr.ForInKeys().Elems() {
	}
}
