// Code generated by bento ts-compat from functionDeclarationWithResolutionOfTypeOfSameName01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
	_ = value.NewFunc(func(__a []value.Value) value.Value {
		(F)()
		return value.Undefined
	})
}
func main() {
}
