// Code generated by bento ts-compat from functionWithDefaultParameterWithNoStatements10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a *value.Array[float64]) {
}
func Bar(a *value.Array[float64]) {
}
func main() {
}
