// Code generated by bento ts-compat from functionCall3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() *value.Array[value.Value] {
	return value.NewArray[value.Value](value.Number(1))
}
func main() {
	x := Foo()
	_ = x
}
