// Code generated by bento ts-compat from functionExpressionWithResolutionOfTypeOfSameName01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := func() func() {
		var f func()
		f = func() {
			_ = value.NewFunc(func(__a []value.Value) value.Value {
				(f)()
				return value.Undefined
			})
		}
		return f
	}()
	_ = x
}
