// Code generated by bento ts-compat from functionWithDefaultParameterWithNoStatements13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a *value.Array[float64]) {
}
func Bar(a *value.Array[float64]) {
}
func main() {
	var v *value.Array[value.Value]
	_ = v
}
