// Code generated by bento ts-compat from functionCall1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() value.Value {
	return value.StringValue(value.FromGoString(""))
}
func main() {
	x := Foo()
	_ = x
}
