// Code generated by bento ts-compat from functionOnlyHasThrow.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Clone() float64 {
	value.Throw(value.NewError(value.FromGoString("To be implemented")))
	panic("unreachable")
}
func main() {
	defer value.ReportUncaught()
}
