// Code generated by bento ts-compat from functionWithAnyReturnTypeAndNoReturnExpression.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() value.Value {
	return value.Undefined
}
func main() {
	f2 := func() value.Value {
		func() {
		}()
		return value.Undefined
	}
	_ = f2
	f3 := func() value.Value {
		return value.Undefined
	}
	_ = f3
}
