// Code generated by bento ts-compat from functionDeclarationWithArgumentOfTypeFunctionTypeArray.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(args *value.Array[func(value.Value) float64]) float64 {
	return args.Len()
}
func main() {
}
