// Code generated by bento ts-compat from functionWithThrowButNoReturn1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Fn() float64 {
	value.Throw(value.NewError(value.FromGoString("NYI")))
	var t value.Value
	_ = t
	panic("unreachable")
}
func main() {
	defer value.ReportUncaught()
}
