// Code generated by bento ts-compat from functionOverloads26.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(bar value.Value) value.Value {
	return value.StringValue(value.FromGoString(""))
}
func main() {
	x := value.ToNumber(Foo(value.StringValue(value.FromGoString("baz"))))
	_ = x
}
