// Code generated by bento ts-compat from functionOverloads28.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(bar value.Value) value.Value {
	return value.StringValue(value.FromGoString(""))
}
func main() {
	var t value.Value
	x := value.ToNumber(Foo(t))
	_ = x
}
