// Code generated by bento ts-compat from functionExpressionWithResolutionOfTypeOfSameName02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := func() {
		var x value.Value
		_ = x
	}
	_ = x
}
