// Code generated by bento ts-compat from functionOverloads30.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(bar value.Value) value.Value {
	return bar
}
func main() {
	x := value.ToString(Foo(value.StringValue(value.FromGoString("bar"))))
	_ = x
}
