// Code generated by bento ts-compat from functionWithDefaultParameterWithNoStatements9.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a func(*value.Array[value.Value])) {
}
func Bar(a func(*value.Array[value.Value])) {
}
func main() {
}
