// Code generated by bento ts-compat from functionCall4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() value.Value {
	return value.StringValue(value.FromGoString(""))
}
func Bar() func() value.Value {
	return Foo
}
func main() {
	x := Bar()
	_ = x
}
