// Code generated by bento ts-compat from functionWithDefaultParameterWithNoStatements3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a value.BStr) {
}
func Bar(a value.BStr) {
}
func main() {
}
