// Code generated by bento ts-compat from genericArrayPropertyAssignment.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjLength struct {
	Length float64 `json:"length"`
}

func IsEmpty(list *ObjLength) bool {
	return list.Length == 0
}
func main() {
	IsEmpty(&ObjLength{Length: value.NewArray[value.Value]().Len()})
}
