// Code generated by bento ts-compat from genericArray1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	lengths := value.MapArray[value.BStr, float64](value.NewArray[value.BStr](value.FromGoString("a"), value.FromGoString("b"), value.FromGoString("c")), func(x value.BStr) float64 {
		return x.Length()
	})
	_ = lengths
}
