// Code generated by bento ts-compat from idInProp.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
	var t func(value.Value) value.Value
	_ = t
}
func main() {
}
