// Code generated by bento ts-compat from implicitAnyDeclareFunctionWithoutFormalType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.Value) {
}
func Bar(x float64, y value.Value) {
}
func Func2(a value.Value, b value.Value, c value.Value) {
}
func Func3(args *value.Array[value.Value]) {
}
func Func4(z value.Value, w value.Value) {
}
func NoError1(x float64, y float64) {
}
func NoError2(x float64, y value.BStr) {
}
func main() {
}
