// Code generated by bento ts-compat from implicitAnyFunctionReturnNullOrUndefined.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) NullWidenFuncOfC() value.Value {
	return value.Null
}
func (c *C) UnderfinedWidenFuncOfC() {
	return
}
func NullWidenFunction() value.Value {
	return value.Null
}
func UndefinedWidenFunction() {
	return
}
func Foo1() value.Value {
	return value.Null
}
func Bar1() value.Value {
	return value.Undefined
}
func FooBar() float64 {
	return 1
}
func FooFoo() float64 {
	return 5
}
func main() {
	NullWidenFunction()
	UndefinedWidenFunction()
}
