// Code generated by bento ts-compat from indexer2.ts. DO NOT EDIT.

package main

type ObjHasOwnProperty struct {
	HasOwnProperty func(float64) bool `json:"hasOwnProperty"`
}

func main() {
	directChildrenMap := &ObjHasOwnProperty{}
	_ = directChildrenMap
}
