// Code generated by bento ts-compat from inferredFunctionReturnTypeIsEmptyType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func Foo() NumOrStr {
	if true {
		return NumOrStrOfNum(42)
	} else {
		return NumOrStrOfStr(value.FromGoString("42"))
	}
}
func main() {
}
