// Code generated by bento ts-compat from inheritanceMemberFuncOverridingMethod.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"unsafe"
)

type aVTable struct {
	x func(self *A) value.BStr
}
type A struct {
	vtable *aVTable
}

var aBaseVTable = aVTable{x: (*A).xImpl}

func NewA() *A {
	self := &A{}
	self.vtable = &aBaseVTable
	return self
}
func (self *A) X() value.BStr {
	return self.vtable.x(self)
}
func (self *A) xImpl() value.BStr {
	return value.FromGoString("10")
}

type B struct {
	A
}

var bVTable = aVTable{x: func(self *A) value.BStr {
	return (*B)(unsafe.Pointer(self)).xImpl()
}}

func NewB() *B {
	self := &B{}
	self.vtable = &bVTable
	return self
}
func (self *B) xImpl() value.BStr {
	return value.FromGoString("20")
}
func main() {
}
