// Code generated by bento ts-compat from inlineSourceMap.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := 0.0
	value.ConsoleLog(value.NumberToString(x))
}
