// Code generated by bento ts-compat from interfaceWithCommaSeparators.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarBaz struct {
	Bar func()      `json:"bar"`
	Baz value.Value `json:"baz"`
}

func main() {
	var v *ObjBarBaz
	_ = v
}
