// Code generated by bento ts-compat from isolatedDeclarationErrorsFunctionDeclarations.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjA struct {
	A float64 `json:"a"`
}
type Tuple_num struct {
	E0 float64
}

func NoReturn() {
}
func NoParamAnnotation(p value.Value) {
}
func NoParamAnnotationDefault(p float64) {
}
func NoParamAnnotationBadDefault(p float64, p2 *ObjA, p3 Tuple_num) {
}
func NoParamAnnotationBadDefault2(p *ObjA) {
}
func main() {
}
