// Code generated by bento ts-compat from jsFileCompilationOptionalClassElementSyntaxOfClass.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	Bar value.Opt[float64] `json:"bar"`
}

func NewC() *C {
	return &C{Bar: value.Some[float64](1)}
}
func (c *C) Foo() {
}
func main() {
}
