// Code generated by bento ts-compat from letDeclarations.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var l1 value.Value
	_ = l1
	var l2 float64
	_ = l2
	var (
		l3 value.Value
		l4 value.Value
		l5 value.BStr
		l6 value.Value
	)
	_ = l3
	_ = l4
	_ = l5
	_ = l6
	l7 := false
	_ = l7
	l8 := 23.0
	_ = l8
	var (
		l9  float64     = 0
		l10 value.BStr  = value.FromGoString("")
		l11 value.Value = value.Null
	)
	_ = l9
	_ = l10
	_ = l11
	for range value.NewObject().ForInKeys().Elems() {
	}
	for l12 := 0.0; l12 < 9; l12++ {
	}
}
