// Code generated by bento ts-compat from letInNonStrictMode.ts. DO NOT EDIT.

package main

type Tuple_num struct {
	E0 float64
}
type ObjA struct {
	A float64 `json:"a"`
}

func main() {
	_bt0 := Tuple_num{E0: 1}
	x := _bt0.E0
	_ = x
	_bt1 := &ObjA{A: 1}
	y := _bt1.A
	_ = y
}
