// Code generated by bento ts-compat from mapOnTupleTypes02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_num struct {
	E0 float64
	E1 float64
}

func Increment(point Tuple_num_num) *value.Array[float64] {
	return value.MapArray[float64, float64](value.NewArray[float64](point.E0, point.E1), func(d float64) float64 {
		return d + 1
	})
}
func main() {
}
