// Code generated by bento ts-compat from mapOnTupleTypes01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num struct {
	E0 float64
}
type Tuple_num_num struct {
	E0 float64
	E1 float64
}
type Tuple_str_str struct {
	E0 value.BStr
	E1 value.BStr
}
type Tuple_num_str struct {
	E0 float64
	E1 value.BStr
}
type Tuple_num_num_num struct {
	E0 float64
	E1 float64
	E2 float64
}
type Tuple_num_num_num_num struct {
	E0 float64
	E1 float64
	E2 float64
	E3 float64
}
type Tuple_num_num_num_num_num struct {
	E0 float64
	E1 float64
	E2 float64
	E3 float64
	E4 float64
}
type Tuple_num_num_num_num_num_num struct {
	E0 float64
	E1 float64
	E2 float64
	E3 float64
	E4 float64
	E5 float64
}
type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func main() {
	mapOnLooseArrayLiteral := value.NewArray[float64](1, 2, 3, 4).Map(func(n float64) float64 {
		return n * n
	})
	_ = mapOnLooseArrayLiteral
	numTuple := Tuple_num{E0: 1}
	a := value.MapArray[float64, float64](value.NewArray[float64](numTuple.E0), func(x float64) float64 {
		return x * x
	})
	_ = a
	numNum := Tuple_num_num{E0: 100, E1: 100}
	strStr := Tuple_str_str{E0: value.FromGoString("hello"), E1: value.FromGoString("hello")}
	numStr := Tuple_num_str{E0: 100, E1: value.FromGoString("hello")}
	b := value.MapArray[float64, float64](value.NewArray[float64](numNum.E0, numNum.E1), func(n float64) float64 {
		return n * n
	})
	_ = b
	c := value.MapArray[value.BStr, float64](value.NewArray[value.BStr](strStr.E0, strStr.E1), func(s value.BStr) float64 {
		return s.CharCodeAt(0)
	})
	_ = c
	d := value.MapArray[NumOrStr, NumOrStr](value.NewArray[NumOrStr](NumOrStrOfNum(numStr.E0), NumOrStrOfStr(numStr.E1)), func(x NumOrStr) NumOrStr {
		return x
	})
	_ = d
	numNumNum := Tuple_num_num_num{E0: 1, E1: 2, E2: 3}
	e := value.MapArray[float64, float64](value.NewArray[float64](numNumNum.E0, numNumNum.E1, numNumNum.E2), func(n float64) float64 {
		return n * n
	})
	_ = e
	numNumNumNum := Tuple_num_num_num_num{E0: 1, E1: 2, E2: 3, E3: 4}
	f := value.MapArray[float64, float64](value.NewArray[float64](numNumNumNum.E0, numNumNumNum.E1, numNumNumNum.E2, numNumNumNum.E3), func(n float64) float64 {
		return n * n
	})
	_ = f
	numNumNumNumNum := Tuple_num_num_num_num_num{E0: 1, E1: 2, E2: 3, E3: 4, E4: 5}
	g := value.MapArray[float64, float64](value.NewArray[float64](numNumNumNumNum.E0, numNumNumNumNum.E1, numNumNumNumNum.E2, numNumNumNumNum.E3, numNumNumNumNum.E4), func(n float64) float64 {
		return n * n
	})
	_ = g
	numNumNumNumNumNum := Tuple_num_num_num_num_num_num{E0: 1, E1: 2, E2: 3, E3: 4, E4: 5, E5: 6}
	_ = numNumNumNumNumNum
	h := value.MapArray[float64, float64](value.NewArray[float64](numNumNumNumNum.E0, numNumNumNumNum.E1, numNumNumNumNum.E2, numNumNumNumNum.E3, numNumNumNumNum.E4), func(n float64) float64 {
		return n * n
	})
	_ = h
}
