// Code generated by bento ts-compat from modularizeLibrary_UsingES5LibAndES6FeatureLibs.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func IdGen() *value.Gen[float64] {
	return value.NewGen[float64](func(_bt0 *value.GenCo[float64]) value.Value {
		i := 10.0
		for i < 20 {
			_ = _bt0.Yield(i + 2)
		}
		return value.Undefined
	})
}
func main() {
	s := value.NewSymbolNoDesc()
	_ = s
	t := value.NewObject()
	p := value.NewProxy(t, value.NewObject())
	_ = p
	value.ReflectOwnKeys(value.NewObject())
}
