// Code generated by bento ts-compat from multiCallOverloads.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Load(f func(value.Opt[value.BStr])) {
}
func main() {
	f1 := func(z value.Opt[value.BStr]) {
	}
	f2 := func(z value.Opt[value.BStr]) {
	}
	Load(f1)
	Load(f2)
	Load(func(_ value.Opt[value.BStr]) {
	})
	Load(func(z value.Opt[value.BStr]) {
	})
}
