// Code generated by bento ts-compat from nestedIndexer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Then(x value.Value) {
	var match value.Value
	_ = match
}
func main() {
}
