// Code generated by bento ts-compat from nestedGenerics.ts. DO NOT EDIT.

package main

type ObjT struct {
	T *ObjT_2 `json:"t"`
}
type ObjT_2 struct {
	T float64 `json:"t"`
}

func main() {
	var f *ObjT
	_ = f
}
