// Code generated by bento ts-compat from nestedIndexer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func Then(x value.Value) {
	var match *ObjEmpty
	_ = match
}
func main() {
}
