// Code generated by bento ts-compat from nestedBlockScopedBindings10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	{
		var x value.Value
		_ = x
		x = value.Number(1)
	}
	switch 1 {
	case 1:
		var y value.Value
		_ = y
		y = value.Number(1)
	}
}
