// Code generated by bento ts-compat from nestedBlockScopedBindings7.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	{
		var x value.Value
		for false {
			_ = func() value.Value {
				return x
			}
		}
	}
	{
		var y value.Value
		_ = y
		for false {
			y = value.Number(1)
		}
	}
}
