// Code generated by bento ts-compat from noCollisionThisExpressionAndLocalVarInMethod.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjDoStuff struct {
	DoStuff func(value.Value) func() value.Value `json:"doStuff"`
}
type A struct {
}

func NewA() *A {
	return &A{}
}
func (self *A) Method1() *ObjDoStuff {
	return &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			_this := 2.0
			return callback.Call(value.Number(_this))
		}
	}}
}
func (self *A) Method2() *ObjDoStuff {
	_this := 2.0
	return &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			return callback.Call(value.Number(_this))
		}
	}}
}
func main() {
	_this := 2.0
	_ = _this
}
