// Code generated by bento ts-compat from noCollisionThisExpressionAndClassInGlobal.ts. DO NOT EDIT.

package main

type _this struct {
}

func New_this() *_this {
	return &_this{}
}

type _thisClass struct {
}

var _thisClassValue = _thisClass{}

func main() {
	f := func() _thisClass {
		return _thisClassValue
	}
	_ = f
}
