// Code generated by bento ts-compat from noCrashOnNoLib.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
	e := value.NewArray[value.Value]()
	_ = e
	for true {
		e = value.ArrayFrom(append([]value.Value{}, (e).Elems()...))
	}
}
func main() {
}
