// Code generated by bento ts-compat from noImplicitAnyInContextuallyTypesFunctionParamter.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	regexMatchList := value.NewArray[value.BStr](value.FromGoString(""), value.FromGoString(""))
	regexMatchList.ForEach(func(_bt0 value.BStr) {
		func(match value.BStr) value.BStr {
			return value.FromGoString("").Replace(match, value.FromGoString(""))
		}(_bt0)
	})
}
