// Code generated by bento ts-compat from nonstrictTemplateWithNotOctalPrintsAsIs.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	d2 := value.FromGoString("\\0041")
	_ = d2
}
