// Code generated by bento ts-compat from noSubstitutionTemplateStringLiteralTypes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("foo")
	_ = x
}
