// Code generated by bento ts-compat from objectLiteral2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
}

func main() {
	var (
		v30 *ObjAB = &ObjAB{A: 1, B: 2}
		v31 value.Value
	)
	_ = v30
	_ = v31
}
