// Code generated by bento ts-compat from objectLiteralIndexerNoImplicitAny.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjP struct {
	P value.Value `json:"p"`
}

func main() {
	x := value.NewObject().Set(value.FromGoString("p"), value.Null)
	_ = x
}
