// Code generated by bento ts-compat from parameterDestructuringObjectLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjHeaders struct {
	Headers value.Value `json:"headers"`
}
type ObjFoo struct {
	Foo float64 `json:"foo"`
}

func main() {
	fn1 := func(options *ObjHeaders) {
	}
	fn1(&ObjHeaders{Headers: value.NewObject().Set(value.FromGoString("foo"), value.Number(1))})
	fn2 := func(__0 *ObjHeaders) {
		var headers value.Value
		if _bt0 := __0.Headers; _bt0.IsUndefined() {
			headers = value.NewObject()
		} else {
			headers = _bt0
		}
		_ = headers
	}
	fn2(&ObjHeaders{Headers: value.NewObject().Set(value.FromGoString("foo"), value.Number(1))})
}
