// Code generated by bento ts-compat from parenthesizedAsyncArrowFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foo := (func(bar value.Value) *value.Promise[value.Value] {
		return value.Async(func() value.Value {
			return bar
		})
	})
	_ = foo
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
