// Code generated by bento ts-compat from parseObjectLiteralsWithoutTypes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarFoo struct {
	Foo value.Value `json:"foo"`
	Bar value.Value `json:"bar"`
}
type ObjBarFoo_2 struct {
	Foo float64     `json:"foo"`
	Bar value.Value `json:"bar"`
}
type ObjBarFoo_3 struct {
	Foo value.Value `json:"foo"`
	Bar float64     `json:"bar"`
}

func main() {
	var x *ObjBarFoo
	_ = x
	var y *ObjBarFoo_2
	_ = y
	var z *ObjBarFoo_3
	_ = z
}
