// Code generated by bento ts-compat from partialTypeNarrowedToByTypeGuard.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func IsUser(obj value.Value) bool {
	return true
}
func GetUserName(obj value.Value) value.Opt[value.BStr] {
	if IsUser(obj) {
		return value.ToOptString(obj.Get(value.FromGoString("name")))
	}
	return value.Some[value.BStr](value.FromGoString(""))
}
func main() {
}
