// Code generated by bento ts-compat from potentiallyUnassignedVariableInCatch.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var foo value.Value
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				value.Caught(rec)
				_ = foo
			}
		}()
		if value.MathRandom() > 0.5 {
			foo = value.Number(1234)
		}
	}()
}
