// Code generated by bento ts-compat from propertyAccess6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var foo value.Value
	foo.Set(value.FromGoString("bar"), value.Number(4))
}
