// Code generated by bento ts-compat from quotedPropertyName1.ts. DO NOT EDIT.

package main

type Test1 struct {
	Prop1 float64 `json:"prop1"`
}

func NewTest1() *Test1 {
	return &Test1{Prop1: 0}
}
func main() {
}
