// Code generated by bento ts-compat from quotedFunctionName1.ts. DO NOT EDIT.

package main

type Test1 struct {
}

func NewTest1() *Test1 {
	return &Test1{}
}
func (t *Test1) Prop1() {
}
func main() {
}
