// Code generated by bento ts-compat from reachabilityChecks3.ts. DO NOT EDIT.

package main

func main() {
	x := 1.0
	for true {
		if x == 100 {
			break
		} else {
			x++
		}
	}
	{
		_ = 100
	}
	y := func() {
		_ = 1
	}
	_ = y
}
