// Code generated by bento ts-compat from reachabilityChecksIgnored.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func A() {
	value.Throw(value.NewError(value.FromGoString("")))
	value.ConsoleLog(value.FromGoString("unreachable"))
}
func B() {
	value.Throw(value.NewError(value.FromGoString("")))
	value.ConsoleLog(value.FromGoString("unreachable"))
}
func main() {
	defer value.ReportUncaught()
}
