// Code generated by bento ts-compat from recursiveReturns.ts. DO NOT EDIT.

package main

func R1() {
	R1()
	return
}
func R2() {
	R2()
}
func R3(n float64) {
	if n == 0 {
	} else {
		R3(func() float64 {
			prev := n
			n--
			return prev
		}())
	}
}
func main() {
}
