// Code generated by bento ts-compat from requiredInitializedParameter4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C1 struct {
}

func NewC1() *C1 {
	return &C1{}
}
func (c *C1) Method(a float64, b value.Value) {
}
func main() {
}
