// Code generated by bento ts-compat from reservedWords.ts. DO NOT EDIT.

package main

type ObjBreakDebuggerFunctionIf struct {
	If       float64 `json:"if"`
	Debugger float64 `json:"debugger"`
	Break    float64 `json:"break"`
	Function float64 `json:"function"`
}
type ObjBreakDebuggerFunctionIfWhile struct {
	If       float64 `json:"if"`
	While    float64 `json:"while"`
	Debugger float64 `json:"debugger"`
	Break    float64 `json:"break"`
	Function float64 `json:"function"`
}

func main() {
	obj := &ObjBreakDebuggerFunctionIf{If: 0, Debugger: 2, Break: 3, Function: 4}
	_ = obj
	obj2 := &ObjBreakDebuggerFunctionIfWhile{If: 0, While: 1, Debugger: 2, Break: 3, Function: 4}
	_ = obj2
}
