// Code generated by bento ts-compat from resolveTypeAliasWithSameLetDeclarationName1.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func main() {
	var baz *C
	_ = baz
}
