// Code generated by bento ts-compat from resolveInterfaceNameWithSameLetDeclarationName1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var bar value.Value
	_ = bar
}
