// Code generated by bento ts-compat from restParameterWithBindingPattern2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_val_val struct {
	E0 value.Value
	E1 value.Value
}

func A(__0 Tuple_val_val) {
}
func main() {
}
