// Code generated by bento ts-compat from restElementAssignable.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjABC struct {
	A float64    `json:"a"`
	B bool       `json:"b"`
	C value.BStr `json:"c"`
}

func main() {
	{
		_bt0 := value.NewObject()
		props := _bt0.ObjectRest()
		t1 := props
		_ = t1
		t2 := value.NewObject()
		_ = t2
	}
	{
		_bt1 := &ObjABC{A: 1, B: false, C: value.FromGoString("str")}
		props := &ObjABC{A: _bt1.A, B: _bt1.B, C: _bt1.C}
		t1 := props
		_ = t1
		t2 := value.NewObject().Set(value.FromGoString("a"), value.Number(1)).Set(value.FromGoString("b"), value.Bool(false)).Set(value.FromGoString("c"), value.StringValue(value.FromGoString("str")))
		_ = t2
	}
}
