// Code generated by bento ts-compat from restParameterNoTypeAnnotation.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(rest *value.Array[value.Value]) float64 {
	x := value.ToNumber(rest.At(0))
	return x
}
func main() {
}
