// Code generated by bento ts-compat from shorthandOfExportedEntity02_targetES5_CommonJS.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjTest struct {
	Test value.BStr `json:"test"`
}

var test value.BStr = value.FromGoString("test")

func Foo() {
	x := &ObjTest{Test: test}
	_ = x
}
func main() {
}
