// Code generated by bento ts-compat from shouldNotPrintNullEscapesIntoOctalLiterals.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("use strict")
	_ = value.FromGoString("\x001")
	_ = value.FromGoString("\x001")
	_ = value.FromGoString("\x001")
	_ = value.FromGoString("\x001")
	_ = value.FromGoString("\x001")
}
