// Code generated by bento ts-compat from simpleArrowFunctionParameterReferencedInObjectLiteral1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.Value `json:"X"`
}

func main() {
	value.MapArray[value.Value, *value.Array[*ObjX]](value.NewArray[value.Value](), func(_ value.Value) *value.Array[*ObjX] {
		return value.MapArray[value.Value, *ObjX](value.NewArray[value.Value](), func(p value.Value) *ObjX {
			return (&ObjX{X: p})
		})
	})
}
