// Code generated by bento ts-compat from sourceMapValidationVarInDownLevelGenerator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() *value.Gen[value.Value] {
	return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
		var (
			x float64 = 1
			y value.Value
		)
		_ = x
		_ = y
		return value.Undefined
	})
}
func main() {
}
