// Code generated by bento ts-compat from sourceMapValidationFunctionExpressions.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	greetings := 0.0
	greet := func(greeting value.BStr) float64 {
		greetings++
		return greetings
	}
	greet(value.FromGoString("Hello"))
	incrGreetings := func() float64 {
		return func() float64 {
			prev := greetings
			greetings++
			return prev
		}()
	}
	_ = incrGreetings
}
