// Code generated by bento ts-compat from sourceMapValidationTryCatchFinally.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	defer value.ReportUncaught()
	x := 10.0
	func() {
		defer func() {
			x *= 10
		}()
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
				x--
			}
		}()
		x++
	}()
	func() {
		defer func() {
			x *= 10
		}()
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
				x--
			}
		}()
		x++
		value.Throw(value.NewError(value.FromGoString("")))
	}()
}
