// Code generated by bento ts-compat from sourceMapValidationVariables.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := 10.0
	_ = a
	var b value.Value
	_ = b
	var (
		c float64 = 10
		d value.Value
		e value.Value
	)
	_ = c
	_ = d
	_ = e
	var (
		c2 value.Value
		d2 float64 = 10
	)
	_ = c2
	_ = d2
}
