// Code generated by bento ts-compat from sourceMap-Comments2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(str value.BStr, num float64) {
	return
}
func Bar(str value.BStr, num float64) {
	return
}
func Baz(str value.BStr, num float64) {
	return
}
func Qat(str value.BStr, num float64) {
	return
}
func main() {
}
