// Code generated by bento ts-compat from sourceMapValidationDestructuringVariableStatementArrayBindingPattern4.ts. DO NOT EDIT.

package main

type Tuple_num_num struct {
	E0 float64
	E1 float64
}

func main() {
	_bt0 := Tuple_num_num{E0: 1, E1: 2}
	x := _bt0.E0
	_ = x
}
