// Code generated by bento ts-compat from sourceMapValidationDestructuringVariableStatementObjectBindingPattern1.ts. DO NOT EDIT.

package main

type ObjX struct {
	X float64 `json:"x"`
}

func main() {
	_bt0 := &ObjX{X: 20}
	x := _bt0.X
	_ = x
}
