// Code generated by bento ts-compat from sourceMapValidationFunctions.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

var greetings float64 = 0

func Greet(greeting value.BStr) float64 {
	greetings++
	return greetings
}
func Greet2(greeting value.BStr, n float64, x value.Opt[value.BStr], restParams *value.Array[value.BStr]) float64 {
	greetings++
	return greetings
}
func Foo(greeting value.BStr, n float64, x value.Opt[value.BStr], restParams *value.Array[value.BStr]) {
	return
}
func main() {
}
