// Code generated by bento ts-compat from sourceMapValidationDo.ts. DO NOT EDIT.

package main

func main() {
	i := 0.0
	for {
		i++
		if i >= 10 {
			break
		}
	}
	for {
		i++
		if i >= 20 {
			break
		}
	}
}
