// Code generated by bento ts-compat from staticInterfaceAssignmentCompat.ts. DO NOT EDIT.

package main

type ObjCreate struct {
	Create func() *Shape `json:"create"`
}
type Shape struct {
}

func NewShape() *Shape {
	return &Shape{}
}
func ShapeCreate() *Shape {
	return NewShape()
}

type ShapeClass struct {
}

var ShapeClassValue = ShapeClass{}

func main() {
	x := ShapeClassValue
	_ = x
}
