// Code generated by bento ts-compat from stringPropCodeGen.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarFoo struct {
	Foo func()  `json:"foo"`
	Bar float64 `json:"bar"`
}

func main() {
	a := &ObjBarFoo{Foo: func() {
	}, Bar: 5}
	a.Foo()
	value.NumberToString(a.Bar)
}
