// Code generated by bento ts-compat from superCallWithCommentEmit01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	Text value.BStr `json:"text"`
}

func NewA(text value.BStr) *A {
	return &A{Text: text}
}

type B struct {
	A
}

func NewB(text value.BStr) *B {
	return &B{A: *NewA(text)}
}
func main() {
}
