// Code generated by bento ts-compat from targetTypeCalls.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	fra1 := func() func(value.BStr) value.BStr {
		return func(v value.BStr) value.BStr {
			return v
		}
	}()
	_ = fra1
	fra2 := func() func() float64 {
		return func() float64 {
			return 0
		}
	}()
	_ = fra2
	fra3 := func() func(value.Value) value.Value {
		return func() func(value.Value) value.Value {
			return func(v value.Value) value.Value {
				return v
			}
		}()
	}()
	_ = fra3
	fra4 := func() func(value.Value) value.Value {
		return func() func(value.Value) value.Value {
			return func(v value.Value) value.Value {
				return v
			}
		}()
	}()
	_ = fra4
}
