// Code generated by bento ts-compat from targetTypingOnFunctions.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	fu := func(s value.BStr) value.BStr {
		return s.ToLowerCase()
	}
	zu := func() func(value.BStr) value.BStr {
		fu = func(s value.BStr) value.BStr {
			return s.ToLowerCase()
		}
		return fu
	}()
	_ = zu
}
