// Code generated by bento ts-compat from targetTypeTest2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func Func1(stuff *value.Array[value.Value]) *value.Array[value.Value] {
	return stuff
}
func Func2(stuff1 value.BStr, stuff2 float64, stuff3 float64) *value.Array[value.Value] {
	return Func1(value.NewArray[value.Value](value.StringValue(stuff1), value.Number(stuff2), value.Number(stuff3)))
}
func main() {
	a := value.NewArray[value.Value](value.Number(1), value.Number(2), value.StringValue(value.FromGoString("3")))
	_ = a
}
