// Code generated by bento ts-compat from templateLiteralsSourceMap.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	s := _sb0.Reset().Lit("a", 1).Num(0).Lit("b", 1).Num(1).Lit("c", 1).Num(2).Done()
	_ = s
}
