// Code generated by bento ts-compat from templateExpressionNoInlininingOfConstantBindingWithInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjValue struct {
	Value NumOrStrOrUndef `json:"value"`
}
type NumOrStrOrUndefTag uint8

const (
	NumOrStrOrUndefNum NumOrStrOrUndefTag = iota
	NumOrStrOrUndefStr
	NumOrStrOrUndefUndef
)

type NumOrStrOrUndef struct {
	tag NumOrStrOrUndefTag
	num float64
	str value.BStr
}

func NumOrStrOrUndefOfNum(v float64) NumOrStrOrUndef {
	return NumOrStrOrUndef{tag: NumOrStrOrUndefNum, num: v}
}
func NumOrStrOrUndefOfStr(v value.BStr) NumOrStrOrUndef {
	return NumOrStrOrUndef{tag: NumOrStrOrUndefStr, str: v}
}
func NumOrStrOrUndefOfUndef() NumOrStrOrUndef {
	return NumOrStrOrUndef{tag: NumOrStrOrUndefUndef}
}
func (u NumOrStrOrUndef) JSONArm() any {
	switch u.tag {
	case NumOrStrOrUndefNum:
		return u.num
	case NumOrStrOrUndefStr:
		return u.str
	case NumOrStrOrUndefUndef:
		return nil
	}
	return nil
}

type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func (u NumOrStr) ToString() value.BStr {
	switch u.tag {
	case NumOrStrNum:
		return value.NumberToString(u.num)
	case NumOrStrStr:
		return u.str
	}
	return value.FromGoString("")
}
func Example(parameters *ObjValue) bool {
	var value_ NumOrStr
	switch _bt0 := parameters.Value; _bt0.tag {
	case NumOrStrOrUndefNum:
		value_ = NumOrStrOfNum(_bt0.num)
	case NumOrStrOrUndefStr:
		value_ = NumOrStrOfStr(_bt0.str)
	case NumOrStrOrUndefUndef:
		value_ = NumOrStrOfStr(value.FromGoString("123"))
	}
	return value.FromGoString("").ConcatN(value_.ToString(), value.FromGoString("")).Equal(value.FromGoString("345"))
}
func Example2(parameters *ObjValue) value.BStr {
	var value_ NumOrStr
	switch _bt1 := parameters.Value; _bt1.tag {
	case NumOrStrOrUndefNum:
		value_ = NumOrStrOfNum(_bt1.num)
	case NumOrStrOrUndefStr:
		value_ = NumOrStrOfStr(_bt1.str)
	case NumOrStrOrUndefUndef:
		value_ = NumOrStrOfStr(value.FromGoString("123"))
	}
	b := value.FromGoString("").ConcatN(value_.ToString(), value.FromGoString(""))
	return b
}
func main() {
}
