// Code generated by bento ts-compat from typeOfOperator1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := 1.0
	_ = x
	y := value.FromGoString("number")
	_ = y
	var z float64
	_ = z
}
