// Code generated by bento ts-compat from typeofUsedBeforeBlockScoped.ts. DO NOT EDIT.

package main

type ObjN struct {
	N float64 `json:"n"`
}
type C struct {
}

var cS float64 = 2

func NewC() *C {
	return &C{}
}
func main() {
	var o2 *ObjN
	_ = o2
	o := &ObjN{N: 12}
	_ = o
}
