// Code generated by bento ts-compat from typeOfYieldWithUnionInContextualReturnType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	syncFactory := func() *value.Gen[value.BStr] {
		return value.NewGen[value.BStr](func(_bt0 *value.GenCo[value.BStr]) value.Value {
			name := value.FromGoString("")
			for !(name.Length() > 0) {
				name = value.ToString(_bt0.Yield(value.FromGoString("What is your name?")))
			}
			return value.StringValue(value.FromGoString("That's the end of the game, ").ConcatN(name, value.FromGoString("")))
		})
	}
	_ = syncFactory
	asyncFactory := func() *value.AsyncGen[value.BStr] {
		return value.NewAsyncGen[value.BStr](func(_bt1 *value.AsyncGenCo[value.BStr]) value.Value {
			name := value.FromGoString("")
			for !(name.Length() > 0) {
				name = value.ToString(_bt1.Yield(value.FromGoString("What is your name?")))
			}
			return value.StringValue(value.FromGoString("That's the end of the game, ").ConcatN(name, value.FromGoString("")))
		})
	}
	_ = asyncFactory
	looserSyncFactory := func() *value.Gen[value.BStr] {
		return value.NewGen[value.BStr](func(_bt2 *value.GenCo[value.BStr]) value.Value {
			name := value.FromGoString("")
			for !(name.Length() > 0) {
				name = value.ToString(_bt2.Yield(value.FromGoString("What is your name?")))
			}
			return value.StringValue(value.FromGoString("That's the end of the game, ").ConcatN(name, value.FromGoString("")))
		})
	}
	_ = looserSyncFactory
	looserAsyncFactory := func() *value.AsyncGen[value.BStr] {
		return value.NewAsyncGen[value.BStr](func(_bt3 *value.AsyncGenCo[value.BStr]) value.Value {
			name := value.FromGoString("")
			for !(name.Length() > 0) {
				name = value.ToString(_bt3.Yield(value.FromGoString("What is your name?")))
			}
			return value.StringValue(value.FromGoString("That's the end of the game, ").ConcatN(name, value.FromGoString("")))
		})
	}
	_ = looserAsyncFactory
}
