// Code generated by bento ts-compat from typeGuardNarrowsIndexedAccessOfKnownProperty3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foo := value.Some[*value.Array[value.Opt[float64]]](value.NewArray[value.Opt[float64]](value.Some[float64](1), value.Some[float64](2), value.Some[float64](3)))
	var index int32 = 1
	if !foo.IsUndefined() && !foo.Get().AtI(int(index)).IsUndefined() && foo.Get().AtI(int(index)).Get() >= 0 {
		_ = foo.Get().AtI(int(index)).Get()
	}
}
