// Code generated by bento ts-compat from typeofInterface.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjA struct {
	A value.BStr `json:"a"`
}
type ObjFooI struct {
	I   float64 `json:"I"`
	Foo *ObjA   `json:"foo"`
}

func main() {
	var I *ObjA
	_ = I
	var k *ObjFooI
	_ = k
	j := &ObjA{A: value.FromGoString("hello")}
	_ = j
}
