// Code generated by bento ts-compat from typeGuardNarrowsIndexedAccessOfKnownProperty4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Foo struct {
	X value.Opt[float64] `json:"x"`
}

func NewFoo() *Foo {
	f := &Foo{}
	f.X = value.Some[float64](5)
	_ = f.X
	_ = f.X
	key := value.FromGoString("x")
	_ = key
	_ = f.X
	return f
}
func main() {
}
