// Code generated by bento ts-compat from typeGuardNarrowsIndexedAccessOfKnownProperty2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjKey struct {
	Key value.Opt[float64] `json:"key"`
}

func main() {
	foo := &ObjKey{Key: value.None[float64]()}
	key := value.FromGoString("key")
	_ = key
	if !foo.Key.IsUndefined() && (foo.Key.Get() != 0 && foo.Key.Get() == foo.Key.Get()) {
		_ = foo.Key
		_ = foo.Key.Get()
	}
}
