// Code generated by bento ts-compat from unaryPlus.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	ESome  float64 = 0
	EThing float64 = 1
)

func main() {
	a := 1.0
	_ = a
	b := value.ToNumber((value.StringValue(value.FromGoString(""))))
	_ = b
	c := ESome
	_ = c
	x := value.StringToNumber(value.FromGoString("3"))
	_ = x
	y := -value.StringToNumber(value.FromGoString("3"))
	_ = y
	z := float64(^value.ToInt32(value.StringToNumber(value.FromGoString("3"))))
	_ = z
}
