// Code generated by bento ts-compat from unmatchedParameterPositions.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_ struct {
}

func main() {
	var s func(*value.Array[value.Value]) *value.Array[value.Value]
	t1 := s
	_ = t1
	t2 := s
	_ = t2
}
