// Code generated by bento ts-compat from unreachableFlowAfterFinally.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() float64 {
	x := 100.0
	if ret, done := func() (ret float64, done bool) {
		defer func() {
			ret, done = x, true
			return
		}()
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
			}
		}()
		value.Throw(value.ThrownString(value.FromGoString("WAT")))
		return
	}(); done {
		return ret
	}
	panic("unreachable")
}
func main() {
	defer value.ReportUncaught()
}
