// Code generated by bento ts-compat from unusedParameterInCatchClause.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() {
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				ex := value.Caught(rec)
				_ = ex
			}
		}()
	}()
}
func main() {
}
