// Code generated by bento ts-compat from unusedMultipleParameter2InContructor.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Dummy struct {
}

func NewDummy(person value.BStr, person2 value.BStr, person3 value.BStr) *Dummy {
	d := &Dummy{}
	unused := 20.0
	_ = unused
	person2 = value.FromGoString("Dummy value")
	return d
}
func main() {
}
