// Code generated by bento ts-compat from unusedSingleParameterInFunctionExpression.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	func_ := func(person value.BStr) {
		unused := 20.0
		_ = unused
	}
	_ = func_
}
