// Code generated by bento ts-compat from useStrictLikePrologueString01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
}
func main() {
	_ = value.FromGoString("hey!")
	_ = value.FromGoString(" use strict ")
}
