// Code generated by bento ts-compat from validUseOfThisInSuper.ts. DO NOT EDIT.

package main

type Base struct {
	B *Base `json:"b"`
}

func NewBase(b *Base) *Base {
	return &Base{B: b}
}

type Super struct {
	Base
}

func NewSuper() *Super {
	s := &Super{}
	s.Base = *NewBase(&(func() *Super {
		return s
	})().Base)
	return s
}
func main() {
}
