// Code generated by bento ts-compat from voidIsInitialized.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.Undefined
	y := value.Undefined
	if value.FromGoString("undefined").Equal(value.FromGoString("undefined")) {
		_ = x
	}
	if !value.FromGoString("undefined").Equal(value.FromGoString("undefined")) {
		_ = y
	}
}
