// Code generated by bento ts-compat from voidReturnLambdaValue.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(arg1 value.Value, arg2 value.Value, callback func(value.Value, value.Value, value.Value)) {
	{
		callback(arg1, arg2, arg2)
		return
	}
}
func main() {
}
