// Code generated by bento ts-compat from voidFunctionAssignmentCompat.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func ExecAny(callback func(value.Value) value.Value) value.Value {
	return callback(value.Number(0))
}
func ExecVoid(callback func(value.Value)) {
	callback(value.Number(0))
}
func main() {
	fa := func() value.Value {
		return value.Number(3)
	}
	_ = fa
	fa = func() value.Value {
		func() {
		}()
		return value.Undefined
	}
	fv := func() {
	}
	_ = fv
	fv = func() {
		func() float64 {
			return 0
		}()
	}
	ExecAny(func(_bt0 value.Value) value.Value {
		func(_ value.Value) {
		}(_bt0)
		return value.Undefined
	})
	ExecVoid(func(_bt1 value.Value) {
		func(_ value.Value) float64 {
			return 0
		}(_bt1)
	})
	fra := func() func() {
		return func() {
		}
	}
	_ = fra
	frv := func() func() float64 {
		return func() float64 {
			return 0
		}
	}
	_ = frv
	fra3 := (func() func(value.BStr) value.BStr {
		return func(v value.BStr) value.BStr {
			return v
		}
	})()
	_ = fra3
	frv3 := (func() func() float64 {
		return func() float64 {
			return 0
		}
	})()
	_ = frv3
}
