// Code generated by bento ts-compat from widenedTypes1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.Value `json:"x"`
}
type ObjX_2 struct {
	X value.Value `json:"x"`
}

func main() {
	a := value.Null
	_ = a
	b := value.Undefined
	_ = b
	c := &ObjX{X: value.Null}
	_ = c
	d := value.NewArray[*ObjX](&ObjX{X: value.Null})
	_ = d
	f := value.NewArray[value.Value](value.Null, value.Null)
	_ = f
	g := value.NewArray[value.Value](value.Undefined, value.Undefined)
	_ = g
	h := value.NewArray[*ObjX_2](&ObjX_2{X: value.Undefined})
	_ = h
}
