// Code generated by bento ts-compat from objectLiteralWidened.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarFoo struct {
	Foo value.Value `json:"foo"`
	Bar value.Value `json:"bar"`
}
type ObjBarFoo_2 struct {
	Foo value.Value `json:"foo"`
	Bar *ObjBazBoo  `json:"bar"`
}
type ObjBazBoo struct {
	Baz value.Value `json:"baz"`
	Boo value.Value `json:"boo"`
}

func main() {
	x1 := &ObjBarFoo{Foo: value.Null, Bar: value.Undefined}
	_ = x1
	y1 := &ObjBarFoo_2{Foo: value.Null, Bar: &ObjBazBoo{Baz: value.Null, Boo: value.Undefined}}
	_ = y1
	u := value.Undefined
	n := value.Null
	x2 := &ObjBarFoo{Foo: n, Bar: u}
	_ = x2
	y2 := &ObjBarFoo_2{Foo: n, Bar: &ObjBazBoo{Baz: n, Boo: u}}
	_ = y2
}
