// Code generated by bento ts-compat from ES3For-ofTypeCheck2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for range value.NewArray[bool](true).Elems() {
	}
}
