// Code generated by bento ts-compat from ES5For-ofTypeCheck10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjDoneValue struct {
	Done  bool       `json:"done"`
	Value value.BStr `json:"value"`
}
type MyStringIterator struct {
}

func NewMyStringIterator() *MyStringIterator {
	return &MyStringIterator{}
}
func (m *MyStringIterator) Next() *ObjDoneValue {
	return &ObjDoneValue{Done: true, Value: value.FromGoString("")}
}
func (m *MyStringIterator) SymbolIterator() *MyStringIterator {
	return m
}
func main() {
	{
		_bt0 := NewMyStringIterator().SymbolIterator()
		for {
			_bt1 := _bt0.Next()
			if _bt1.Done {
				break
			}
		}
	}
}
