// Code generated by bento ts-compat from ES5For-of21.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for range value.NewArray[value.Value]().Elems() {
		for range value.NewArray[value.Value]().Elems() {
		}
	}
}
