// Code generated by bento ts-compat from ES5For-of14.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, v := range value.NewArray[value.Value]().Elems() {
		x := v
		_ = x
	}
}
