// Code generated by bento ts-compat from ES5For-of5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, _a := range value.NewArray[value.Value]().Elems() {
		x := _a
		_ = x
	}
}
