// Code generated by bento ts-compat from ES5For-of25.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.NewArray[float64](1, 2, 3)
	for _, v := range a.Elems() {
		_ = v
		_ = a
	}
}
