// Code generated by bento ts-compat from ES5For-ofTypeCheck1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for range value.FromGoString("").CodePoints() {
	}
}
