// Code generated by bento ts-compat from ES5For-of13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, v := range value.NewArray[value.BStr](value.FromGoString("a"), value.FromGoString("b"), value.FromGoString("c")).Elems() {
		x := v
		_ = x
	}
}
