// Code generated by bento ts-compat from ES5For-ofTypeCheck13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	strSet := value.NewStringSet()
	strSet.Add(value.FromGoString("Hello"))
	strSet.Add(value.FromGoString("World"))
	for range strSet.Members() {
	}
}
