// Code generated by bento ts-compat from ES5For-of37.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	defer value.ReportUncaught()
	for _, i := range value.NewArray[float64](0, 1, 2, 3, 4).Elems() {
		func() {
			defer func() {
				if rec := recover(); rec != nil {
					err := value.Caught(rec)
					_ = err
					value.ConsoleLog(value.FromGoString("E %s %s"), value.NumberToString(i), err.ToBStr())
				}
			}()
			for range value.NewArray[float64](1, 2, 3).Elems() {
				if i == 2 {
					value.Throw(value.NewError(value.FromGoString("ERR")))
				}
			}
			value.ConsoleLog(value.NumberToString(i))
		}()
	}
}
