// Code generated by bento ts-compat from ES5For-of24.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.NewArray[float64](1, 2, 3)
	for range a.Elems() {
		a := 0.0
		_ = a
	}
}
