// Code generated by bento ts-compat from ES5For-of6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, w := range value.NewArray[value.Value]().Elems() {
		for _, v := range value.NewArray[value.Value]().Elems() {
			x := value.NewArray[value.Value](w, v)
			_ = x
		}
	}
}
