// Code generated by bento ts-compat from MemberFunctionDeclaration1_es6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Foo() *value.Gen[value.Value] {
	return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
		return value.Undefined
	})
}
func main() {
}
