// Code generated by bento ts-compat from allowUnescapedParagraphAndLineSeparatorsInStringLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	stringContainingUnescapedLineSeparator1 := value.FromGoString("\u2028STRING_CONTENT\u2028")
	_ = stringContainingUnescapedLineSeparator1
	stringContainingUnescapedParagraphSeparator1 := value.FromGoString("\u2029STRING_CONTENT\u2029")
	_ = stringContainingUnescapedParagraphSeparator1
	stringContainingUnescapedLineSeparator2 := value.FromGoString("\u2028STRING_CONTENT\u2028")
	_ = stringContainingUnescapedLineSeparator2
	stringContainingUnescapedParagraphSeparator2 := value.FromGoString("\u2029STRING_CONTENT\u2029")
	_ = stringContainingUnescapedParagraphSeparator2
	stringContainingUnescapedLineSeparator3 := value.FromGoString("\u2028STRING_CONTENT\u2028")
	_ = stringContainingUnescapedLineSeparator3
	stringContainingUnescapedParagraphSeparator3 := value.FromGoString("\u2029STRING_CONTENT\u2029")
	_ = stringContainingUnescapedParagraphSeparator3
	arr := value.NewArray[value.BStr](value.FromGoString("\u2029\u2028STRING_CONTENT\u2028\u2029"), value.FromGoString("\u2028\u2029\u2029STRING_CONTENT\u2029\u2029\u2028"), value.FromGoString("STRING_CONTENT\u2029"), value.FromGoString("\u2028STRING_CONTENT"), value.FromGoString(""), value.FromGoString("\u2028"))
	_ = arr
}
