// Code generated by bento ts-compat from emitClassDeclarationWithPropertyAssignmentInES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	X value.BStr `json:"x"`
}

func NewC() *C {
	return &C{X: value.FromGoString("Hello world")}
}

type D struct {
	X value.BStr `json:"x"`
	Y float64    `json:"y"`
}

func NewD() *D {
	return &D{X: value.FromGoString("Hello world"), Y: 10}
}

type E struct {
	D
	Z bool `json:"z"`
}

func NewE() *E {
	return &E{D: *NewD(), Z: true}
}

type F struct {
	D
	Z bool       `json:"z"`
	J value.BStr `json:"j"`
}

func NewF() *F {
	return &F{D: *NewD(), Z: true, J: value.FromGoString("HI")}
}
func main() {
}
