// Code generated by bento ts-compat from emitClassDeclarationWithStaticPropertyAssignmentInES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var cZ value.BStr = value.FromGoString("Foo")

func NewC() *C {
	return &C{}
}

type D struct {
	X float64 `json:"x"`
}

var dB bool = true

func NewD() *D {
	return &D{X: 20000}
}
func main() {
}
