// Code generated by bento ts-compat from parserClassDeclaration26.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	Var    value.Value `json:"var"`
	Public value.Value `json:"public"`
}

func NewC() *C {
	return &C{}
}
func main() {
}
