// Code generated by bento ts-compat from parserCommaInTypeMemberList1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjWidthWorkItem struct {
	WorkItem value.Value `json:"workItem"`
	Width    value.BStr  `json:"width"`
}

func main() {
	var v *ObjWidthWorkItem
	_ = v
}
