// Code generated by bento ts-compat from validBooleanAssignments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjValueOf struct {
	ValueOf func() bool `json:"valueOf"`
}

func main() {
	x := true
	a := value.Bool(x)
	_ = a
	b := x
	_ = b
	c := x
	_ = c
	d := x
	_ = d
}
