// Code generated by bento ts-compat from emitClassDeclarationWithSuperMethodCall01.ts. DO NOT EDIT.

package main

import (
	"unsafe"
)

type parentVTable struct {
	foo func(p *Parent)
}
type Parent struct {
	vtable *parentVTable
}

var parentBaseVTable = parentVTable{foo: (*Parent).fooImpl}

func NewParent() *Parent {
	p := &Parent{}
	p.vtable = &parentBaseVTable
	return p
}
func (p *Parent) Foo() {
	p.vtable.foo(p)
}
func (p *Parent) fooImpl() {
}

type Foo struct {
	Parent
}

var fooVTable = parentVTable{foo: func(p *Parent) {
	(*Foo)(unsafe.Pointer(p)).fooImpl()
}}

func NewFoo() *Foo {
	f := &Foo{}
	f.vtable = &fooVTable
	return f
}
func (f *Foo) fooImpl() {
	x := func() {
		f.Parent.fooImpl()
	}
	_ = x
}
func main() {
}
