// Code generated by bento ts-compat from emitClassDeclarationWithThisKeywordInES6.ts. DO NOT EDIT.

package main

type B struct {
	X_ float64 `json:"x"`
}

func NewB() *B {
	return &B{X_: 10}
}
func (b *B) Foo() {
	BLog(b.X_)
}
func (b *B) X() float64 {
	return b.X_
}
func (b *B) SetBX(y float64) {
	b.X_ = y
}
func BLog(a float64) {
}
func main() {
}
