// Code generated by bento ts-compat from anyPropertyAccess.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	a := x.Get(value.FromGoString("foo"))
	_ = a
	b := x.Get(value.FromGoString("foo"))
	_ = b
	c := x.Get(value.FromGoString("fn")).Call()
	_ = c
	d := x.Get(value.FromGoString("bar")).Get(value.FromGoString("baz"))
	_ = d
	e := x.GetIndex(0).Get(value.FromGoString("foo"))
	_ = e
	f := x.Get(value.FromGoString("0")).Get(value.FromGoString("bar"))
	_ = f
}
