// Code generated by bento ts-compat from asyncFunctionDeclaration14_es5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		return
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
