// Code generated by bento ts-compat from jsDeclarationsConstsAsNamespacesWithReferences.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjRoyalBlue struct {
	RoyalBlue value.BStr `json:"royalBlue"`
}
type ObjPurple struct {
	Purple value.BStr `json:"purple"`
}

func main() {
	colors := &ObjRoyalBlue{RoyalBlue: value.FromGoString("#6400e4")}
	brandColors := &ObjPurple{Purple: colors.RoyalBlue}
	_ = brandColors
}
