// Code generated by bento ts-compat from jsDeclarationsReusesExistingNodesMappingJSDocTypes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.Null
	_ = a
	b := value.Null
	_ = b
	c := value.Null
	_ = c
	d := value.Null
	_ = d
	e := value.Null
	_ = e
	f := value.Null
	_ = f
	g := value.Null
	_ = g
	h := value.Null
	_ = h
}
