// Code generated by bento ts-compat from jsDeclarationsMissingGenerics.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func X(x value.Value) {
}
func Y(x value.Value) {
}
func main() {
}
