// Code generated by bento ts-compat from jsDeclarationsOptionalTypeLiteralProps1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(__0 value.Value) value.Value {
	a := __0.Get(value.FromGoString("a"))
	b := __0.Get(value.FromGoString("b"))
	c := __0.Get(value.FromGoString("c"))
	return value.Add(value.Add(a, b), c)
}
func main() {
}
