// Code generated by bento ts-compat from jsDeclarationsClassLikeHeuristic.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	var A value.Value
	A = value.NewObject()
	value.MissingProperty(A).Set(value.FromGoString("b"), value.NewObject())
}
