// Code generated by bento ts-compat from jsDeclarationsOptionalTypeLiteralProps2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(__0 value.Value) value.Value {
	a := __0.Get(value.FromGoString("a"))
	b := __0.Get(value.FromGoString("b"))
	c := __0.Get(value.FromGoString("c"))
	return value.Add(value.Add(a, (value.Coalesce(b, value.Number(0)))), (value.Coalesce(c, value.Number(0))))
}
func main() {
}
