// Code generated by bento ts-compat from TupleType2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_str struct {
	E0 float64
	E1 value.BStr
}

func main() {
	var v Tuple_num_str
	_ = v
}
