// Code generated by bento ts-compat from forInContinueStatements.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for range value.NewObject().ForInKeys().Elems() {
		continue
	}
ONE:
	for range value.NewObject().ForInKeys().Elems() {
		continue ONE
	}
THREE:
	for range value.NewObject().ForInKeys().Elems() {
		continue THREE
	}
FOUR:
	for range value.NewObject().ForInKeys().Elems() {
		for range value.NewObject().ForInKeys().Elems() {
			continue FOUR
		}
	}
	for range value.NewObject().ForInKeys().Elems() {
	SIX:
		for range value.NewObject().ForInKeys().Elems() {
			continue SIX
		}
	}
SEVEN:
	for range value.NewObject().ForInKeys().Elems() {
		for range value.NewObject().ForInKeys().Elems() {
			for range value.NewObject().ForInKeys().Elems() {
				continue SEVEN
			}
		}
	}
EIGHT:
	for range value.NewObject().ForInKeys().Elems() {
		fn := func() {
		}
		_ = fn
		continue EIGHT
	}
}
