// Code generated by bento ts-compat from whileContinueStatements.ts. DO NOT EDIT.

package main

func main() {
	for true {
		continue
	}
	for true {
		if true {
			continue
		}
	}
ONE:
	for true {
		continue ONE
	}
THREE:
	for true {
		continue THREE
	}
FOUR:
	for true {
		for true {
			continue FOUR
		}
	}
	for true {
	SIX:
		for true {
			continue SIX
		}
	}
SEVEN:
	for true {
		for true {
			for true {
				continue SEVEN
			}
		}
	}
EIGHT:
	for true {
		fn := func() {
		}
		_ = fn
		continue EIGHT
	}
NINE:
	for true {
		if true {
			continue NINE
		}
	}
}
