// Code generated by bento ts-compat from unicodeExtendedEscapesInTemplates01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\x00")
	_ = x
}
