// Code generated by bento ts-compat from unicodeExtendedEscapesInStrings13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\U000ddddd")
	_ = x
}
