// Code generated by bento ts-compat from unicodeExtendedEscapesInTemplates10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromUTF16([]uint16{0xd800})
	_ = x
}
