// Code generated by bento ts-compat from unicodeExtendedEscapesInTemplates08.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\uffff")
	_ = x
}
