// Code generated by bento ts-compat from unicodeExtendedEscapesInRegularExpressions11.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x *value.RegExp
	_ = x
}
