// Code generated by bento ts-compat from tupleElementTypes3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_undef struct {
	E0 float64
	E1 value.Value
}

func main() {
	_bt0 := Tuple_num_undef{E0: 0, E1: value.Undefined}
	a := _bt0.E0
	_ = a
	b := _bt0.E1
	_ = b
}
