// Code generated by bento ts-compat from tupleElementTypes4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num_undef struct {
	E0 float64
	E1 value.Value
}

func F(__0 Tuple_num_undef) {
	a := __0.E0
	_ = a
	b := __0.E1
	_ = b
}
func main() {
}
