// Code generated by bento ts-compat from intersectionOfUnionOfUnitTypes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x0 value.BStr
	_ = x0
	var x1 value.BStr
	_ = x1
	var x2 value.BStr
	_ = x2
	var x3 value.Value
	_ = x3
	var x4 value.BStr
	_ = x4
	var x5 value.Value
	_ = x5
	var y0 float64
	_ = y0
	var y1 float64
	_ = y1
	var y2 float64
	_ = y2
	var y3 value.Value
	_ = y3
	var y4 float64
	_ = y4
	var y5 value.Value
	_ = y5
	var z0 float64
	_ = z0
	var z1 float64
	_ = z1
	var z2 float64
	_ = z2
	var z3 value.Value
	_ = z3
	var z4 float64
	_ = z4
	var z5 value.Value
	_ = z5
}
