// Code generated by bento ts-compat from declarationEmitIdentifierPredicatesWithPrivateName01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(x value.Value) bool {
	return x.Get(value.FromGoString("a")).TypeOf().Equal(value.FromGoString("number"))
}
func main() {
}
