// Code generated by bento ts-compat from parserGreaterThanTokenAmbiguity1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = float64(value.ToInt32(1) >> (value.ToUint32(2) & 31))
}
