// Code generated by bento ts-compat from generatorTypeCheck4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func G1() *value.Gen[value.Value] {
	return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
		return value.Undefined
	})
}
func main() {
}
