// Code generated by bento ts-compat from generatorTypeCheck11.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func G() *value.Gen[float64] {
	return value.NewGen[float64](func(_bt0 *value.GenCo[float64]) value.Value {
		return value.Number(0)
	})
}
func main() {
}
