// Code generated by bento ts-compat from nullishCoalescingOperator8.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjMP struct {
	P value.Opt[value.BStr]        `json:"p"`
	M func() value.Opt[value.BStr] `json:"m"`
}

func main() {
	var a *ObjMP
	var b *ObjMP
	n1 := a.P.Or(value.FromGoString("default"))
	_ = n1
	n2 := a.M().Or(value.FromGoString("default"))
	_ = n2
	n3 := func() value.Opt[value.BStr] {
		_bt1 := func() value.Opt[value.BStr] {
			_bt0 := a.M()
			if _bt0.IsUndefined() {
				return b.P
			}
			return _bt0
		}()
		if _bt1.IsUndefined() {
			return b.M()
		}
		return _bt1
	}().Or(value.FromGoString("default"))
	_ = n3
}
