// Code generated by bento ts-compat from parserX_ArrowFunction4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := func(a value.Value, b value.Value) {
	}
	_ = v
}
