// Code generated by bento ts-compat from spreadContextualTypedBindingPattern.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAgeNaam struct {
	Naam value.BStr `json:"naam"`
	Age  float64    `json:"age"`
}

func main() {
	var bob *ObjAgeNaam
	_ = bob
	var alice *ObjAgeNaam
	_bt0 := &ObjAgeNaam{Naam: alice.Naam, Age: alice.Age}
	naam := _bt0.Naam
	_ = naam
	age := _bt0.Age
	_ = age
}
