// Code generated by bento ts-compat from spreadUnion4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X func() `json:"x"`
}
type ObjX_2 struct {
	X value.Opt[func()] `json:"x"`
}

func main() {
	var a *ObjX
	_ = a
	var b *ObjX_2
	c := &ObjX{X: b.X.Or(a.X)}
	_ = c
}
