// Code generated by bento ts-compat from privateNameComputedPropertyName4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C1 struct {
}

var c1_p_qux value.Value = value.Number(42)

func NewC1() *C1 {
	return &C1{}
}
func (c *C1) Bar() {
}

type C2 struct {
}

var c2_p_qux value.Value = value.Number(42)

func NewC2() *C2 {
	return &C2{}
}
func C2Bar() {
}

type C3 struct {
}

var c3_p_qux value.Value = value.Number(42)
var c3Bar value.BStr = value.FromGoString("test")

func NewC3() *C3 {
	return &C3{}
}
func main() {
}
