// Code generated by bento ts-compat from privateNameField.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	p_name value.BStr `json:"-"`
}

func NewA(name value.BStr) *A {
	return &A{p_name: name}
}
func main() {
}
