// Code generated by bento ts-compat from privateNamesAndkeyof.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	p_fooField float64 `json:"-"`
	Bar        float64 `json:"bar"`
	Baz        float64 `json:"baz"`
}

func NewA() *A {
	return &A{p_fooField: 3, Bar: 3, Baz: 3}
}
func (a *A) p_fooMethod() {
}
func (a *A) p_fooProp() float64 {
	return 1
}
func (a *A) p_set_fooProp(value_ float64) {
}
func main() {
	k := value.FromGoString("bar")
	_ = k
	k = value.FromGoString("baz")
	k = value.FromGoString("#fooField")
	k = value.FromGoString("#fooMethod")
	k = value.FromGoString("#fooProp")
	k = value.FromGoString("fooField")
	k = value.FromGoString("fooMethod")
	k = value.FromGoString("fooProp")
}
