// Code generated by bento ts-compat from privateNameMethodInStaticFieldInit.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

var cS float64

func NewC() *C {
	return &C{}
}
func (c *C) p_method() float64 {
	return 42
}
func staticInitC() {
	cS = NewC().p_method()
}
func main() {
	staticInitC()
	value.ConsoleLog(value.NumberToString(cS))
}
