// Code generated by bento ts-compat from privateNameStaticAndStaticInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
}

var a_p_foo value.Value = value.Number(1)
var a_p_prop value.Value = value.Number(2)

func NewA() *A {
	return &A{}
}
func main() {
}
