// Code generated by bento ts-compat from privateNameStaticFieldInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
}

var a_p_field value.Value = value.Number(10)
var a_p_uninitialized value.Value

func NewA() *A {
	return &A{}
}
func main() {
}
