// Code generated by bento ts-compat from typeFromPrivatePropertyAssignmentJs.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	p_a value.Value `json:"-"`
	p_b value.Value `json:"-"`
}

func NewC() *C {
	return &C{}
}
func (c *C) M() {
	a := func() value.Value {
		_bt0 := c.p_a
		if value.ToBoolean(_bt0) {
			return _bt0
		}
		return value.NewObject()
	}()
	_ = a
	c.p_b = func() value.Value {
		_bt1 := c.p_b
		if value.ToBoolean(_bt1) {
			return _bt1
		}
		return value.NewObject()
	}()
}
func main() {
}
