// Code generated by bento ts-compat from validUndefinedValues.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	_ = x
	x = value.Undefined
}
