// Code generated by bento ts-compat from esnextSharedMemory.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	value.AtomicPause()
	value.AtomicPause(1)
}
