// Code generated by bento ts-compat from parserNotRegex2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var A value.Value
	var B value.Value
	var C value.Value
	x := (value.ToNumber(A) / 2)
	_ = x
	B.Call(C.Call(), value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}), value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
}
