// Code generated by bento ts-compat from forContinueStatements.ts. DO NOT EDIT.

package main

func main() {
	for {
		continue
	}
ONE:
	for {
		continue ONE
	}
THREE:
	for {
		continue THREE
	}
FOUR:
	for {
		for {
			continue FOUR
		}
	}
	for {
	SIX:
		for {
			continue SIX
		}
	}
SEVEN:
	for {
		for {
			for {
				continue SEVEN
			}
		}
	}
EIGHT:
	for {
		fn := func() {
		}
		_ = fn
		continue EIGHT
	}
}
