// Code generated by bento ts-compat from parser.numericSeparators.decimal.ts. DO NOT EDIT.

package main

func main() {
	_ = 1000000000
	_ = 1.10001
	_ = 1e10
	_ = 1e+10
	_ = 1e-10
	_ = 1.1e100
	_ = 1.1e+100
	_ = 1.1e-100
	_ = 123456
	_ = 122333
	_ = 12.34
	_ = 12.34e56
	_ = 12.34e+56
	_ = 12.34e-56
}
