// Code generated by bento ts-compat from es6modulekindWithES5Target6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1(d float64) {
}
func F2(arg *value.Array[value.Value]) {
}
func Default(d float64) {
}
func main() {
}
