// Code generated by bento ts-compat from destructuringTypeAssertionsES5_5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_bt0 := value.Number(0)
	x := _bt0.Get(value.FromGoString("x"))
	_ = x
}
