// Code generated by bento ts-compat from destructuringCatch.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	defer value.ReportUncaught()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt0 := value.Caught(rec).ToValue()
				a := _bt0.GetIndex(0)
				b := _bt0.GetIndex(1)
				_ = value.Add(a, b)
			}
		}()
		value.Throw(value.NewThrownValue(value.NewArrayValue([]value.Value{value.Number(0), value.Number(1)})))
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt1 := value.Caught(rec).ToValue()
				a := _bt1.Get(value.FromGoString("a"))
				b := _bt1.Get(value.FromGoString("b"))
				_ = value.Add(a, b)
			}
		}()
		value.Throw(value.NewThrownValue(value.NewObject().Set(value.FromGoString("a"), value.Number(0)).Set(value.FromGoString("b"), value.Number(1))))
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt2 := value.Caught(rec).ToValue()
				_bt3 := _bt2.GetIndex(0)
				_bt4 := _bt3.Get(value.FromGoString("x"))
				y := _bt4.GetIndex(0)
				z := _bt3.Get(value.FromGoString("z"))
				_ = value.Add(y, z)
			}
		}()
		value.Throw(value.NewThrownValue(value.NewArrayValue([]value.Value{value.NewObject().Set(value.FromGoString("x"), value.NewArrayValue([]value.Value{value.Number(0)})).Set(value.FromGoString("z"), value.Number(1))})))
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt5 := value.Caught(rec).ToValue()
				a := _bt5.GetIndex(0)
				_ = a
			}
		}()
	}()
}
