// Code generated by bento ts-compat from iterableArrayPattern27.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_str_num struct {
	E0 value.BStr
	E1 float64
}

func TakeFirstTwoEntries(__0 *value.Array[Tuple_str_num]) {
}
func main() {
	TakeFirstTwoEntries(value.ArrayFrom(append([]Tuple_str_num{}, func() []Tuple_str_num {
		_bt2 := func() *value.Map[value.BStr, float64] {
			_bt0 := value.NewStringMap[float64]()
			_bt0.Set(value.FromGoString(""), 0)
			_bt0.Set(value.FromGoString("hello"), 1)
			return _bt0
		}()
		_bt3 := _bt2.Keys()
		_bt4 := _bt2.Values()
		_bt1 := make([]Tuple_str_num, len(_bt3))
		for _bt5, _bt6 := range _bt3 {
			_bt1[_bt5] = Tuple_str_num{E0: _bt6, E1: _bt4[_bt5]}
		}
		return _bt1
	}()...)))
}
