// Code generated by bento ts-compat from objectBindingPatternKeywordIdentifiers06.ts. DO NOT EDIT.

package main

type ObjAs struct {
	As float64 `json:"as"`
}

func main() {
	_bt0 := &ObjAs{As: 1}
	as := _bt0.As
	_ = as
}
