// Code generated by bento ts-compat from computedPropertyNamesContextualType5_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	o := value.NewObject().SetKeyed(value.Number(value.StringToNumber(value.FromGoString("foo"))), value.StringValue(value.FromGoString(""))).SetKeyed(value.Number(value.StringToNumber(value.FromGoString("bar"))), value.Number(0))
	_ = o
}
