// Code generated by bento ts-compat from computedPropertyNamesSourceMap1_ES5.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Hello() {
}
func (c *C) Goodbye() float64 {
	return 0
}
func main() {
}
