// Code generated by bento ts-compat from computedPropertyNames47_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjN_0 struct {
	N_0 float64 `json:"0"`
}

const (
	E1X float64 = 0
)
const (
	E2X float64 = 0
)

func main() {
	o := value.NewObject().SetKeyed(value.Number(func() float64 {
		if E1X != 0 && E1X == E1X {
			return E1X
		}
		return E2X
	}()), value.Number(0))
	_ = o
}
