// Code generated by bento ts-compat from parserAccessibilityAfterStatic3.ts. DO NOT EDIT.

package main

type Outer struct {
}

var outerPublic float64 = 1

func NewOuter() *Outer {
	return &Outer{}
}
func main() {
}
