// Code generated by bento ts-compat from parser596700.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	regex2 := value.NewRegExpLiteral("[a-z/]$", "i")
	_ = regex2
}
