// Code generated by bento ts-compat from parser645484.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjNew struct {
	New value.Opt[func() value.Value] `json:"new"`
}

func main() {
	var c *ObjNew
	_ = c
}
