// Code generated by bento ts-compat from constEnum3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1(f float64) {
}
func F2(f value.BStr) {
}
func main() {
	F1(0)
	F1(1)
	F2(value.FromGoString("foo"))
	F2(value.FromGoString("bar"))
}
