// Code generated by bento ts-compat from parserInterfaceKeywordInEnum1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	BarInterface float64 = 0
)

func main() {
	_ = value.FromGoString("use strict")
}
