// Code generated by bento ts-compat from parserAccessibilityAfterStatic11.ts. DO NOT EDIT.

package main

type Outer struct {
}

func NewOuter() *Outer {
	return &Outer{}
}
func OuterPublic() {
}
func main() {
}
