// Code generated by bento ts-compat from parserAccessibilityAfterStatic2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Outer struct {
}

var outerPublic value.Value

func NewOuter() *Outer {
	return &Outer{}
}
func main() {
}
