// Code generated by bento ts-compat from stringLiteralsAssertionsInEqualityComparisons01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.FromGoString("foo").Equal(value.FromGoString("bar"))
	_ = a
	b := !value.FromGoString("foo").Equal((value.FromGoString("bar")))
	_ = b
	c := value.LooseEquals(value.StringValue(value.FromGoString("foo")), (value.StringValue(value.FromGoString("bar"))))
	_ = c
}
