// Code generated by bento ts-compat from stringLiteralsWithEqualityChecks02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.BStr
	var y value.BStr
	var b bool
	_ = b
	b = value.LooseEquals(value.StringValue(x), value.StringValue(y))
	b = value.LooseEquals(value.StringValue(value.FromGoString("foo")), value.StringValue(y))
	b = value.LooseEquals(value.StringValue(y), value.StringValue(value.FromGoString("foo")))
	b = value.LooseEquals(value.StringValue(value.FromGoString("foo")), value.StringValue(value.FromGoString("bar")))
	b = value.LooseEquals(value.StringValue(value.FromGoString("bar")), value.StringValue(x))
	b = value.LooseEquals(value.StringValue(x), value.StringValue(value.FromGoString("bar")))
	b = value.LooseEquals(value.StringValue(y), value.StringValue(value.FromGoString("bar")))
	b = value.LooseEquals(value.StringValue(value.FromGoString("bar")), value.StringValue(y))
	b = !value.LooseEquals(value.StringValue(x), value.StringValue(y))
	b = !value.LooseEquals(value.StringValue(value.FromGoString("foo")), value.StringValue(y))
	b = !value.LooseEquals(value.StringValue(y), value.StringValue(value.FromGoString("foo")))
	b = !value.LooseEquals(value.StringValue(value.FromGoString("foo")), value.StringValue(value.FromGoString("bar")))
	b = !value.LooseEquals(value.StringValue(value.FromGoString("bar")), value.StringValue(x))
	b = !value.LooseEquals(value.StringValue(x), value.StringValue(value.FromGoString("bar")))
	b = !value.LooseEquals(value.StringValue(y), value.StringValue(value.FromGoString("bar")))
	b = !value.LooseEquals(value.StringValue(value.FromGoString("bar")), value.StringValue(y))
}
