// Code generated by bento ts-compat from templateLiteralTypesPatternsPrefixSuffixAssignability.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	s1 := value.FromGoString(":")
	_ = s1
	s2 := value.FromGoString("::")
	_ = s2
	s3 := value.FromGoString("::")
	_ = s3
	s4 := value.FromGoString(":::")
	_ = s4
}
