// Code generated by bento ts-compat from abstractIdentifierNameStrict.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() {
	_ = value.FromGoString("use strict")
	abstract := true
	_ = abstract
}
func main() {
	abstract := true
	_ = abstract
}
