// Code generated by bento ts-compat from accessorWithLineTerminator.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) X() float64 {
	return 1
}
func (c *C) SetX(v float64) {
}
func main() {
}
