// Code generated by bento ts-compat from aliasOfGenericFunctionWithRestBehavedSameAsUnaliased.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	check := value.FromGoString("y")
	_ = check
	check1 := value.FromGoString("y")
	_ = check1
	check2 := value.FromGoString("y")
	_ = check2
	check3 := value.FromGoString("y")
	_ = check3
}
