// Code generated by bento ts-compat from alwaysStrictAlreadyUseStrict.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
	a := value.NewArray[value.Value]()
	_ = a
}
func main() {
	_ = value.FromGoString("use strict")
}
