// Code generated by bento ts-compat from arrayLiteralInNonVarArgParameter.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Panic(val *value.Array[value.BStr], opt *value.Array[value.BStr]) {
}
func main() {
	Panic(value.NewArray[value.BStr](), value.NewArray[value.BStr](value.FromGoString("one"), value.FromGoString("two")))
}
