// Code generated by bento ts-compat from asyncArrowInClassES5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Test struct {
}

var testMember func(value.BStr) *value.Promise[value.Unit]

func NewTest() *Test {
	return &Test{}
}
func staticInitTest() {
	testMember = func(x value.BStr) *value.Promise[value.Unit] {
		return value.AsyncVoid(func() {
		})
	}
}
func main() {
	staticInitTest()
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
