// Code generated by bento ts-compat from asyncFunctionWithForStatementNoInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Test1() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		i := 0.0
		limit := 10.0
		for ; i < limit; i++ {
		}
	})
}
func Test2() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		i := 0.0
		limit := 10.0
		for i = 1; i < limit; i++ {
		}
	})
}
func Test3() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		i := 0.0
		for ; ; i++ {
		}
	})
}
func Test4() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		for {
		}
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
