// Code generated by bento ts-compat from asyncIIFE.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() {
	(func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
			_ = value.AwaitValue[float64](_bt0, 10)
			value.Throw(value.NewError(value.FromGoString("")))
		})
	})()
	x := 1.0
	_ = x
}
func main() {
	defer value.ReportUncaught()
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
