// Code generated by bento ts-compat from awaitExpressionInnerCommentEmit.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
		_ = value.AwaitValue[float64](_bt0, 1)
		_ = value.AwaitValue[float64](_bt0, 2)
		_ = value.AwaitValue[float64](_bt0, 3)
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
