// Code generated by bento ts-compat from bigIntWithTargetES2016.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"math/big"
)

func main() {
	defer value.ReportUncaught()
	_ = value.BigIntPow(big.NewInt(1), big.NewInt(1))
	num := big.NewInt(2)
	num = value.BigIntPow(num, big.NewInt(2))
}
