// Code generated by bento ts-compat from bigIntWithTargetLessThanES2016.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"math/big"
)

func main() {
	defer value.ReportUncaught()
	_ = value.BigIntPow(big.NewInt(1), big.NewInt(1))
	foo := big.NewInt(2)
	foo = value.BigIntPow(foo, big.NewInt(2))
}
