// Code generated by bento ts-compat from bindingPatternInParameter01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	nestedArray := value.NewArray[*value.Array[*value.Array[float64]]](value.NewArray[*value.Array[float64]](value.NewArray[float64](1, 2)), value.NewArray[*value.Array[float64]](value.NewArray[float64](3, 4)))
	nestedArray.ForEach(func(__0 *value.Array[*value.Array[float64]]) {
		_bt0 := __0.AtI(0)
		a := _bt0.AtI(0)
		b := _bt0.AtI(1)
		value.ConsoleLog(value.NumberToString(a), value.NumberToString(b))
	})
}
