// Code generated by bento ts-compat from blockScopedBindingsInDownlevelGenerator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func A() *value.Gen[float64] {
	return value.NewGen[float64](func(_bt0 *value.GenCo[float64]) value.Value {
		for _, i := range value.NewArray[float64](1, 2, 3).Elems() {
			(func() float64 {
				return i
			})()
			_ = _bt0.Yield(i)
		}
		return value.Undefined
	})
}
func main() {
}
