// Code generated by bento ts-compat from capturedLetConstInLoop10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
}

func NewA() *A {
	return &A{}
}
func (self *A) Foo() {
	for _, x := range value.NewArray[float64](0).Elems() {
		f := func() float64 {
			return x
		}
		self.Bar(f())
	}
}
func (self *A) Bar(a float64) {
}
func (self *A) Baz() {
	for _, x := range value.NewArray[float64](1).Elems() {
		a := func() float64 {
			return x
		}
		for _, y := range value.NewArray[float64](1).Elems() {
			b := func() float64 {
				return y
			}
			self.Bar(b())
		}
		self.Bar(a())
	}
}
func (self *A) Baz2() {
	for _, x := range value.NewArray[float64](1).Elems() {
		a := func() float64 {
			return x
		}
		self.Bar(a())
		for _, y := range value.NewArray[float64](1).Elems() {
			b := func() float64 {
				return y
			}
			self.Bar(b())
		}
	}
}

type B struct {
}

func NewB() *B {
	return &B{}
}
func (b *B) Foo() {
	a := func() {
		for _, x := range value.NewArray[float64](0).Elems() {
			f := func() float64 {
				return x
			}
			b.Bar(f())
		}
	}
	_ = a
}
func (b *B) Bar(a float64) {
}
func main() {
}
