// Code generated by bento ts-compat from castNewObjectBug.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	xx := value.NewObject()
	_ = xx
}
