// Code generated by bento ts-compat from checkJsObjectLiteralHasCheckedKeyof.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

func main() {
	obj := &ObjXY{X: 1, Y: 2}
	_ = obj
	selected := value.FromGoString("x")
	_ = selected
	selected = value.FromGoString("z")
}
