// Code generated by bento ts-compat from ClassDeclarationWithInvalidConstOnPropertyDeclaration2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	Const value.Value `json:"const"`
	X     float64     `json:"x"`
}

func NewC() *C {
	return &C{X: 10}
}
func main() {
}
