// Code generated by bento ts-compat from classDeclarationCheckUsedBeforeDefinitionInFunctionDeclaration.ts. DO NOT EDIT.

package main

type C2 struct {
}

func NewC2() *C2 {
	return &C2{}
}
func F() {
	_ = NewC2()
}
func main() {
}
