// Code generated by bento ts-compat from collisionSuperAndParameter1.ts. DO NOT EDIT.

package main

type Foo struct {
}

func NewFoo() *Foo {
	return &Foo{}
}

type Foo2 struct {
	Foo
}

func NewFoo2() *Foo2 {
	return &Foo2{Foo: *NewFoo()}
}
func (f *Foo2) X() {
	lambda := func(_super float64) {
	}
	_ = lambda
}
func main() {
}
