// Code generated by bento ts-compat from collisionSuperAndLocalVarInConstructor.ts. DO NOT EDIT.

package main

type Foo struct {
}

func NewFoo() *Foo {
	f := &Foo{}
	_super := 10.0
	_ = _super
	return f
}

type B struct {
	Foo
}

func NewB() *B {
	self := &B{}
	self.Foo = *NewFoo()
	_super := 10.0
	_ = _super
	return self
}

type C struct {
	Foo
}

func NewC() *C {
	self := &C{}
	self.Foo = *NewFoo()
	x := func() {
		_super := 10.0
		_ = _super
	}
	_ = x
	return self
}
func main() {
	_super := 10.0
	_ = _super
}
