// Code generated by bento ts-compat from collisionSuperAndLocalFunctionInAccessors.ts. DO NOT EDIT.

package main

type Foo struct {
}

func NewFoo() *Foo {
	return &Foo{}
}
func (f *Foo) Prop1() float64 {
	_super := func() {
	}
	_ = _super
	return 10
}
func (f *Foo) SetProp1(val float64) {
	_super := func() {
	}
	_ = _super
}

type B struct {
	Foo
}

func NewB() *B {
	return &B{Foo: *NewFoo()}
}
func (self *B) Prop2() float64 {
	_super := func() {
	}
	_ = _super
	return 10
}
func (self *B) SetProp2(val float64) {
	_super := func() {
	}
	_ = _super
}

type C struct {
	Foo
}

func NewC() *C {
	return &C{Foo: *NewFoo()}
}
func (self *C) Prop2() float64 {
	x := func() {
		_super := func() {
		}
		_ = _super
	}
	_ = x
	return 10
}
func (self *C) SetProp2(val float64) {
	x := func() {
		_super := func() {
		}
		_ = _super
	}
	_ = x
}
func _super() {
}
func main() {
}
