// Code generated by bento ts-compat from commentOnStaticMember1.ts. DO NOT EDIT.

package main

type Greeter struct {
}

func NewGreeter() *Greeter {
	return &Greeter{}
}
func GreeterFoo() {
}
func main() {
}
