// Code generated by bento ts-compat from commentsArgumentsOfCallExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.Value) {
}
func main() {
	Foo(value.Number(1))
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
		})()
		return value.Undefined
	}))
}
