// Code generated by bento ts-compat from commentsOnObjectLiteral5.ts. DO NOT EDIT.

package main

type ObjP0P1P2 struct {
	P0 float64 `json:"p0"`
	P1 float64 `json:"p1"`
	P2 float64 `json:"p2"`
}

func main() {
	a := &ObjP0P1P2{P0: 0, P1: 0, P2: 0}
	_ = a
}
