// Code generated by bento ts-compat from commentsEnums.ts. DO NOT EDIT.

package main

const (
	ColorsCornflower float64 = 0
	ColorsFancyPink  float64 = 1
)

func main() {
	x := ColorsCornflower
	_ = x
	x = ColorsFancyPink
}
