// Code generated by bento ts-compat from commentOnClassAccessor1.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Bar() float64 {
	return 1
}
func main() {
}
