// Code generated by bento ts-compat from commentOnParameter3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func CommentedParameters(a value.Value, b value.Value) {
}
func main() {
}
