// Code generated by bento ts-compat from commentsCommentParsing.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type NoQuickInfoClass struct {
}

func NewNoQuickInfoClass() *NoQuickInfoClass {
	return &NoQuickInfoClass{}
}
func Simple() {
}
func MultiLine() {
}
func JsDocSingleLine() {
}
func JsDocMultiLine() {
}
func JsDocMultiLineMerge() {
}
func JsDocMixedComments1() {
}
func JsDocMixedComments2() {
}
func JsDocMixedComments3() {
}
func JsDocMixedComments4() {
}
func JsDocMixedComments5() {
}
func JsDocMixedComments6() {
}
func NoHelpComment1() {
}
func NoHelpComment2() {
}
func NoHelpComment3() {
}
func Sum(a float64, b float64) float64 {
	return a + b
}
func Multiply(a float64, b float64, c value.Opt[float64], d value.Value, e value.Value) {
}
func F1(aOrb value.Value, opt value.Value) value.Value {
	return aOrb
}
func Subtract(a float64, b float64, c value.Opt[func() value.BStr], d value.Opt[func() value.BStr], e value.Opt[func() value.BStr], f value.Opt[func() value.BStr]) {
}
func Square(a float64) float64 {
	return a * a
}
func Divide(a float64, b float64) {
}
func JsDocParamTest(a float64, b float64, c float64, d float64) float64 {
	return a + b + c + d
}
func main() {
	Simple()
	MultiLine()
	JsDocSingleLine()
	JsDocMultiLine()
	JsDocMultiLineMerge()
	JsDocMixedComments1()
	JsDocMixedComments2()
	JsDocMixedComments3()
	JsDocMixedComments4()
	JsDocMixedComments5()
	JsDocMixedComments6()
	NoHelpComment1()
	NoHelpComment2()
	NoHelpComment3()
	Sum(10, 20)
}
