// Code generated by bento ts-compat from commentsAfterFunctionExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjFGH struct {
	F func(value.Value) float64 `json:"f"`
	G func(value.Value) float64 `json:"g"`
	H func(value.Value) float64 `json:"h"`
}

func main() {
	v := &ObjFGH{F: func(a value.Value) float64 {
		return 0
	}, G: (func(a value.Value) float64 {
		return 0
	}), H: (func(a value.Value) float64 {
		return 0
	})}
	_ = v
}
