// Code generated by bento ts-compat from conditionalAnyCheckTypePicksBothBranches.ts. DO NOT EDIT.

package main

func main() {
	var x float64
	_ = x
	x = 1
	x = 0
	var y float64
	_ = y
	y = 1
	y = 0
}
