// Code generated by bento ts-compat from constDeclarationShadowedByVarDeclaration2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Outer() {
	x := 0.0
	_ = x
	inner := func() {
		x := value.FromGoString("inner")
		_ = x
	}
	_ = inner
}
func main() {
}
