// Code generated by bento ts-compat from constDeclarations-es5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	z7 := false
	_ = z7
	z8 := 23.0
	_ = z8
	var (
		z9  float64     = 0
		z10 value.BStr  = value.FromGoString("")
		z11 value.Value = value.Null
	)
	_ = z9
	_ = z10
	_ = z11
}
