// Code generated by bento ts-compat from contextualTyping22.ts. DO NOT EDIT.

package main

func main() {
	foo := func(a float64) float64 {
		return a
	}
	_ = foo
	foo = func(b float64) float64 {
		return b
	}
}
