// Code generated by bento ts-compat from continueInLoopsWithCapturedBlockScopedBindings1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() {
	for _, i := range value.NewArray[float64](0, 1).Elems() {
		if i == 0 {
			continue
		}
		(func() float64 {
			return i
		})()
	}
}
func main() {
}
