// Code generated by bento ts-compat from contextualTypeOnYield2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	g := func() *value.Gen[value.Value] {
		return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
			return value.NewFunc(func(__a []value.Value) value.Value {
				(func(num float64) {
					value.ConsoleLog(value.NumberToString(num))
				})(value.ToNumber(value.Arg(__a, 0)))
				return value.Undefined
			})
		})
	}
	_ = g
}
