// Code generated by bento ts-compat from controlFlowBreakContinueWithLabel.ts. DO NOT EDIT.

package main

const (
	UserA float64 = 0
	UserB float64 = 1
)

func main() {
	user := UserA
label:
	for true {
		switch user {
		case UserA:
			user = UserB
			continue label
		case UserB:
			break label
		}
	}
	_ = user
}
