// Code generated by bento ts-compat from contextualTyping38.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foo := func(a value.Value) value.Value {
		return a
	}
	_ = foo
}
