// Code generated by bento ts-compat from controlFlowFinallyNoCatchAssignments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x float64
	x = value.MathRandom()
	var a float64
	func() {
		defer func() {
			value.ConsoleLog(value.NumberToString(x))
		}()
		if x != 0 && x == x {
			a = 1
		} else {
			a = 2
		}
	}()
	value.ConsoleLog(value.NumberToString(a))
}
