// Code generated by bento ts-compat from contextualTyping35.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjId struct {
	Id float64 `json:"id"`
}
type ObjIdName struct {
	Id   float64    `json:"id"`
	Name value.BStr `json:"name"`
}

func main() {
	foo := &ObjIdName{Id: 4, Name: value.FromGoString("as")}
	_ = foo
}
