// Code generated by bento ts-compat from controlFlowManyCallExpressionStatementsPerf.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Test(x bool) bool {
	return x
}
func main() {
	state := true
	if state {
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
		Test(value.ToBoolean(value.And(value.Bool(state), value.Bool(state))))
	}
}
