// Code generated by bento ts-compat from declarationQuotedMembers.ts. DO NOT EDIT.

package main

type ObjAU2D_bU2D_c struct {
	AU2D_bU2D_c float64 `json:"a-b-c"`
}

func main() {
	var mapped *ObjAU2D_bU2D_c
	example := mapped
	_ = example
}
