// Code generated by bento ts-compat from declarationEmitOptionalMethod.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.Opt[func()] `json:"a"`
	B value.Opt[func()] `json:"b"`
}
type ObjCD struct {
	C value.Opt[func()] `json:"c"`
	D value.Opt[func()] `json:"d"`
}
type ObjEmpty struct {
}

func main() {
	Foo := func(opts *ObjAB) *ObjEmpty {
		return (&ObjEmpty{})
	}
	_ = Foo
}
