// Code generated by bento ts-compat from declarationEmitTypeAliasWithTypeParameters1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_val_str struct {
	E0 value.Value
	E1 value.BStr
}

func main() {
	y := func(x func() Tuple_val_str) float64 {
		return 1
	}
	_ = y
}
