// Code generated by bento ts-compat from declarationEmitDefaultExport3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Default() value.BStr {
	return value.FromGoString("")
}
func main() {
}
