// Code generated by bento ts-compat from destructureCatchClause.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt0 := value.Caught(rec).ToValue()
				x := _bt0.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt1 := value.Caught(rec).ToValue()
				x := _bt1.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt2 := value.Caught(rec).ToValue()
				_bt3 := _bt2.Get(value.FromGoString("a"))
				x := _bt3.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt4 := value.Caught(rec).ToValue()
				_bt5 := _bt4.Get(value.FromGoString("a"))
				x := _bt5.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt6 := value.Caught(rec).ToValue()
				_bt7 := _bt6.GetIndex(0)
				x := _bt7.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt8 := value.Caught(rec).ToValue()
				_bt9 := _bt8.GetIndex(0)
				x := _bt9.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt10 := value.Caught(rec).ToValue()
				_bt11 := _bt10.Get(value.FromGoString("a"))
				_bt12 := _bt11.Get(value.FromGoString("b"))
				_bt13 := _bt12.Get(value.FromGoString("c"))
				x := _bt13.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt14 := value.Caught(rec).ToValue()
				x := _bt14.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt15 := value.Caught(rec).ToValue()
				x := _bt15.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt16 := value.Caught(rec).ToValue()
				_bt17 := _bt16.Get(value.FromGoString("a"))
				x := _bt17.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt18 := value.Caught(rec).ToValue()
				_bt19 := _bt18.Get(value.FromGoString("a"))
				x := _bt19.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt20 := value.Caught(rec).ToValue()
				_bt21 := _bt20.GetIndex(0)
				x := _bt21.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt22 := value.Caught(rec).ToValue()
				_bt23 := _bt22.GetIndex(0)
				x := _bt23.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt24 := value.Caught(rec).ToValue()
				_bt25 := _bt24.Get(value.FromGoString("a"))
				_bt26 := _bt25.Get(value.FromGoString("b"))
				_bt27 := _bt26.Get(value.FromGoString("c"))
				x := _bt27.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt28 := value.Caught(rec).ToValue()
				x := _bt28.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt29 := value.Caught(rec).ToValue()
				x := _bt29.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt30 := value.Caught(rec).ToValue()
				_bt31 := _bt30.Get(value.FromGoString("a"))
				x := _bt31.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt32 := value.Caught(rec).ToValue()
				_bt33 := _bt32.Get(value.FromGoString("a"))
				x := _bt33.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt34 := value.Caught(rec).ToValue()
				_bt35 := _bt34.GetIndex(0)
				x := _bt35.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt36 := value.Caught(rec).ToValue()
				_bt37 := _bt36.GetIndex(0)
				x := _bt37.GetIndex(0)
				_ = x
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				_bt38 := value.Caught(rec).ToValue()
				_bt39 := _bt38.Get(value.FromGoString("a"))
				_bt40 := _bt39.Get(value.FromGoString("b"))
				_bt41 := _bt40.Get(value.FromGoString("c"))
				x := _bt41.Get(value.FromGoString("x"))
				_ = x
			}
		}()
	}()
}
