// Code generated by bento ts-compat from destructuringWithNewExpression.ts. DO NOT EDIT.

package main

type ObjX struct {
	X float64 `json:"x"`
}
type C struct {
	X float64 `json:"x"`
}

func NewC() *C {
	return &C{X: 0}
}
func main() {
	_bt0 := NewC()
	x := _bt0.X
	_ = x
}
