// Code generated by bento ts-compat from discriminateObjectTypesOnly.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjToFixed struct {
	ToFixed value.Value `json:"toFixed"`
}
type ObjToString struct {
	ToString value.Value `json:"toString"`
}
type ObjToString_2 struct {
	ToString value.Value `json:"toString"`
}

func main() {
	k := &ObjToFixed{ToFixed: value.Null}
	_ = k
	q := &ObjToFixed{ToFixed: value.Null}
	_ = q
	h := &ObjToString{ToString: value.Null}
	_ = h
	l := &ObjToString_2{ToString: value.Undefined}
	_ = l
}
