// Code generated by bento ts-compat from doNotEmitDetachedCommentsAtStartOfFunctionBody.ts. DO NOT EDIT.

package main

func Foo1() float64 {
	return 42
}
func Foo2() float64 {
	return 42
}
func Foo3() float64 {
	return 42
}
func Foo4() float64 {
	return 42
}
func main() {
}
