// Code generated by bento ts-compat from doNotEmitPinnedDetachedComments.ts. DO NOT EDIT.

package main

func Baz() {
}
func Bar() {
}
func Foo() float64 {
	return 0
}
func main() {
	x := 10.0
	_ = x
}
