// Code generated by bento ts-compat from doubleUnderStringLiteralAssignability.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	shouldBeOk := value.FromGoString("__dunder")
	_ = shouldBeOk
	bad := value.FromGoString("no_dunder")
	_ = bad
	okok := value.FromGoString("___thunder")
	_ = okok
	alsoOk := value.FromGoString("_sunder")
	_ = alsoOk
}
