// Code generated by bento ts-compat from doubleUnderscoreLabels.ts. DO NOT EDIT.

package main

func DoThing() {
__call:
	for true {
	aLabel:
		for i := 0.0; i < 10; i++ {
			if i == 3 {
				break __call
			}
			if i == 5 {
				break aLabel
			}
		}
	}
}
func main() {
	DoThing()
}
