// Code generated by bento ts-compat from downlevelIterationDeprecated.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var log func(value.BStr)
	var arr *value.Array[value.BStr]
	for _, a := range arr.Elems() {
		log(a)
	}
}
