// Code generated by bento ts-compat from emptyArgumentsListComment.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var a value.Value
	a.Call()
	a.Call()
}
