// Code generated by bento ts-compat from emptyThenWithoutWarning.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := 4.0
	if a == 1 || a == 2 || a == 3 {
	} else {
		message := value.FromGoString("Ooops")
		_ = message
	}
}
