// Code generated by bento ts-compat from emptyExpr.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	_ = value.NewArray[*ObjEmpty](&ObjEmpty{})
}
