// Code generated by bento ts-compat from enumKeysQuotedAsObjectPropertiesInDeclarationEmit.ts. DO NOT EDIT.

package main

type ObjN_0N_1N_2N_3N_4U2D_1 struct {
	U2D_1 float64 `json:"-1"`
	N_0   float64 `json:"0"`
	N_1   float64 `json:"1"`
	N_2   float64 `json:"2"`
	N_3   float64 `json:"3"`
	N_4   float64 `json:"4"`
}

const (
	MouseButtonLEFT_BUTTON     float64 = 1
	MouseButtonRIGHT_BUTTON    float64 = 2
	MouseButtonMIDDLE_BUTTON   float64 = 4
	MouseButtonXBUTTON1_BUTTON float64 = 5
	MouseButtonXBUTTON2_BUTTON float64 = 6
	MouseButtonNO_BUTTON       float64 = 0
)

func main() {
	DOMMouseButton := &ObjN_0N_1N_2N_3N_4U2D_1{U2D_1: MouseButtonNO_BUTTON, N_0: MouseButtonLEFT_BUTTON, N_1: MouseButtonMIDDLE_BUTTON, N_2: MouseButtonRIGHT_BUTTON, N_3: MouseButtonXBUTTON1_BUTTON, N_4: MouseButtonXBUTTON2_BUTTON}
	_ = DOMMouseButton
}
