// Code generated by bento ts-compat from es5-commonjs5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Default() value.BStr {
	return value.FromGoString("test")
}
func main() {
}
