// Code generated by bento ts-compat from excessPropertyCheckWithNestedArrayIntersection.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjDataType struct {
	DataType *ObjFields `json:"dataType"`
}
type ObjFields struct {
	Fields *value.Array[*ObjKeyValue] `json:"fields"`
}
type ObjKeyValue struct {
	Key   value.BStr  `json:"key"`
	Value value.Value `json:"value"`
}

func main() {
	repro := &ObjDataType{DataType: &ObjFields{Fields: value.NewArray[*ObjKeyValue](&ObjKeyValue{Key: value.FromGoString("bla"), Value: value.Null})}}
	_ = repro
}
