// Code generated by bento ts-compat from exportedVariable1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjName struct {
	Name value.BStr `json:"name"`
}

func main() {
	foo := &ObjName{Name: value.FromGoString("Bill")}
	upper := foo.Name.ToUpperCase()
	_ = upper
}
