// Code generated by bento ts-compat from exportDefaultInterfaceAndValue.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjA struct {
	A value.BStr `json:"a"`
}

func Default() float64 {
	return 1
}
func main() {
	var x *ObjA
	_ = x
}
