// Code generated by bento ts-compat from extendedUnicodePlaneIdentifiersJSDoc.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(𝑚 value.Value, 𝑀 value.Value) {
	value.ConsoleLog(value.ConsoleValue(value.Add(𝑀, 𝑚)))
}
func main() {
}
