// Code generated by bento ts-compat from extendedUnicodePlaneIdentifiers.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type K struct {
	p_𝑚 float64 `json:"-"`
	p_𝑀 float64 `json:"-"`
}

func NewK() *K {
	return &K{p_𝑚: 4, p_𝑀: 5}
}
func main() {
	𝑚 := 4.0
	𝑀 := 5.0
	value.ConsoleLog(value.NumberToString(𝑀 + 𝑚))
	ၡ := 6.0
	value.ConsoleLog(value.NumberToString(value.Pow(ၡ, ၡ)))
	ဒ := 7.0
	value.ConsoleLog(value.NumberToString(value.Pow(ဒ, ဒ)))
	ဒၡ𝑀 := 7.0
	value.ConsoleLog(value.NumberToString(value.Pow(ဒၡ𝑀, ဒၡ𝑀)))
	ၡ𝑀ဒ := 7.0
	value.ConsoleLog(value.NumberToString(value.Pow(ၡ𝑀ဒ, ၡ𝑀ဒ)))
	𝑀ဒၡ := 7.0
	value.ConsoleLog(value.NumberToString(value.Pow(𝑀ဒၡ, 𝑀ဒၡ)))
	𝓱𝓮𝓵𝓵𝓸 := value.FromGoString("𝔀𝓸𝓻𝓵𝓭")
	_ = 𝓱𝓮𝓵𝓵𝓸
	Ɐⱱ := value.FromGoString("ok")
	_ = Ɐⱱ
	𓀸𓀹𓀺 := value.FromGoString("ok")
	_ = 𓀸𓀹𓀺
	𡚭𡚮𡚯 := value.FromGoString("ok")
	_ = 𡚭𡚮𡚯
	𡚭𓀺ⱱ𝓮 := value.FromGoString("ok")
	_ = 𡚭𓀺ⱱ𝓮
	𓀺ⱱ𝓮𡚭 := value.FromGoString("ok")
	_ = 𓀺ⱱ𝓮𡚭
	ⱱ𝓮𡚭𓀺 := value.FromGoString("ok")
	_ = ⱱ𝓮𡚭𓀺
	𝓮𡚭𓀺ⱱ := value.FromGoString("ok")
	_ = 𝓮𡚭𓀺ⱱ
}
