// Code generated by bento ts-compat from firstMatchRegExpMatchArray.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var match value.Value = value.NewRegExpLiteral(" ", "").MatchStr(value.FromGoString(""))
	if !match.IsNull() {
		foo := value.ToString(match.GetIndex(0))
		_ = foo
		bar := value.ToString(match.GetIndex(1))
		_ = bar
	}
}
