// Code generated by bento ts-compat from fromAsIdentifier2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("use strict")
	var from value.Value
	_ = from
}
