// Code generated by bento ts-compat from functionExpressionWithResolutionOfTypeOfSameName02.ts. DO NOT EDIT.

package main

type ObjEmpty struct {
}

func main() {
	x := func() {
		var x *ObjEmpty
		_ = x
	}
	_ = x
}
