// Code generated by bento ts-compat from functionWithDefaultParameterWithNoStatements16.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a value.Value) {
}
func Bar(a value.Value) {
}
func main() {
	var v *value.Array[value.Value]
	_ = v
}
