// Code generated by bento ts-compat from functionOverloads33.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(bar value.Value) value.Value {
	return bar
}
func main() {
	x := value.ToNumber(Foo(value.Number(5)))
	_ = x
}
