// Code generated by bento ts-compat from functionOverloads12.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() value.Value {
	if true {
		return value.StringValue(value.FromGoString(""))
	} else {
		return value.Number(0)
	}
	return value.Undefined
}
func main() {
}
