// Code generated by bento ts-compat from functionAssignmentError.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	func_ := func() value.BStr {
		return value.FromGoString("ONE")
	}
	_ = func_
	func_ = func() value.BStr {
		return value.FromGoString("ONE")
	}
}
