// Code generated by bento ts-compat from generatorES6_3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := func() *value.Gen[float64] {
		return value.NewGen[float64](func(_bt0 *value.GenCo[float64]) value.Value {
			_ = _bt0.Yield(0)
			return value.Undefined
		})
	}
	_ = v
}
