// Code generated by bento ts-compat from genericIndexedAccessVarianceComparisonResultCorrect.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.BStr `json:"x"`
}
type A struct {
	X value.BStr `json:"x"`
	Y float64    `json:"y"`
}

func NewA() *A {
	return &A{X: value.FromGoString("A"), Y: 0}
}

type B struct {
	X value.BStr `json:"x"`
	Z bool       `json:"z"`
}

func NewB() *B {
	return &B{X: value.FromGoString("B"), Z: true}
}
func main() {
	var a *ObjX
	var b *ObjX
	_ = b
	var c *ObjX
	_ = c
	var d *ObjX
	b = a
	c = d
}
