// Code generated by bento ts-compat from generics1NoError.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X *ObjA   `json:"x"`
	Y *ObjABC `json:"y"`
}
type ObjA struct {
	A value.BStr `json:"a"`
}
type ObjABC struct {
	C value.BStr `json:"c"`
	A value.BStr `json:"a"`
	B value.BStr `json:"b"`
}
type ObjXY_2 struct {
	X *ObjXY_3 `json:"x"`
	Y *ObjABC  `json:"y"`
}
type ObjXY_3 struct {
	X *ObjA  `json:"x"`
	Y *ObjAB `json:"y"`
}
type ObjAB struct {
	B value.BStr `json:"b"`
	A value.BStr `json:"a"`
}

func main() {
	var v1 *ObjXY
	_ = v1
	var v2 *ObjXY
	_ = v2
	var v4 *ObjXY_2
	_ = v4
}
