// Code generated by bento ts-compat from getAndSetNotIdenticalType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) X() float64 {
	return 1
}
func (c *C) SetX(v value.BStr) {
}
func main() {
}
