// Code generated by bento ts-compat from indexedAccessImplicitlyAny.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjFoof struct {
	Foof float64 `json:"foof"`
}

func main() {
	var i *ObjFoof
	_ = value.MissingProperty(i)
	_ = value.MissingProperty(i)
}
