// Code generated by bento ts-compat from indexedAccessRetainsIndexSignature.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjB struct {
	B value.BStr `json:"b"`
}

func main() {
	o := &ObjB{B: value.FromGoString("")}
	_ = o
}
