// Code generated by bento ts-compat from inferTypeArgumentsInSignatureWithRestParameters.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F_num(array *value.Array[float64], args *value.Array[value.Value]) {
}
func G(array *value.Array[float64], args *value.Array[value.Value]) {
}
func H_arr_num(nonarray *value.Array[float64], args *value.Array[value.Value]) {
}
func I_num(array *value.Array[float64], opt value.Opt[*value.Array[value.Value]]) {
}
func main() {
	a := value.NewArray[float64](1, 2, 3, 4, 5)
	F_num(a, value.NewArray[value.Value]())
	G(a, value.NewArray[value.Value]())
	H_arr_num(a, value.NewArray[value.Value]())
	I_num(a, value.None[*value.Array[value.Value]]())
}
