// Code generated by bento ts-compat from infinitelyExpandingTypes5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func From(arg value.Value) value.Value {
	return value.Undefined
}
func main() {
}
