// Code generated by bento ts-compat from inheritanceStaticFuncOverridingMethod.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
}

func NewA() *A {
	return &A{}
}
func AX() value.BStr {
	return value.FromGoString("10")
}

type B struct {
	A
}

func NewB() *B {
	return &B{A: *NewA()}
}
func BX() value.BStr {
	return value.FromGoString("20")
}
func main() {
}
