// Code generated by bento ts-compat from inOperatorWithFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	fn := func(val bool) bool {
		return val
	}
	fn(value.InOperator(value.StringValue(value.FromGoString("a")), value.NewObject().Set(value.FromGoString("a"), value.Bool(true))))
}
