// Code generated by bento ts-compat from invalidTypeNames.ts. DO NOT EDIT.

package main

type Illegal_name_here struct {
}

func NewIllegal_name_here() *Illegal_name_here {
	return &Illegal_name_here{}
}
func main() {
}
