// Code generated by bento ts-compat from isolatedModulesNonAmbientConstEnum.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	e := 100.0
	_ = e
	var x value.Value
	_ = x
}
