// Code generated by bento ts-compat from jsdocTypeCast.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(x value.Value) {
	a := (x)
	_ = a
	b := (x)
	_ = b
	c := (x)
	_ = c
}
func main() {
}
