// Code generated by bento ts-compat from jsdocParameterParsingInvalidName.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (self *C) Method(foo value.Value) {
}
func main() {
}
