// Code generated by bento ts-compat from jsFileCompilationWithoutJsExtensions.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var v value.Value
	_ = v
}
