// Code generated by bento ts-compat from jsFileCompilationAwaitModifier.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Foo struct {
	B func() *value.Promise[value.Unit] `json:"b"`
}

func NewFoo() *Foo {
	f := &Foo{}
	f.B = func() *value.Promise[value.Unit] {
		return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
			_ = value.Await(_bt0, value.Resolved[float64](1))
		})
	}
	return f
}
func (f *Foo) A() *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt1 *value.AsyncCo) {
		_ = value.Await(_bt1, value.Resolved[float64](1))
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
