// Code generated by bento ts-compat from jsFileAlternativeUseOfOverloadTag.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjConstructor struct {
	Constructor func(value.Value, value.Value) `json:"constructor"`
}
type ObjConstructor_2 struct {
	Constructor func() `json:"constructor"`
}
type ObjEvaluate struct {
	Evaluate func(value.Value, value.Value) `json:"evaluate"`
}

func main() {
	example1 := &ObjConstructor{Constructor: func(value_ value.Value, options value.Value) {
	}}
	_ = example1
	example2 := &ObjConstructor_2{Constructor: func() {
	}}
	_ = example2
	example3 := &ObjEvaluate{Evaluate: func(options value.Value, callback value.Value) {
	}}
	_ = example3
}
