// Code generated by bento ts-compat from jsFileCompilationPublicParameterModifier.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	X value.Value `json:"x"`
}

func NewC(x value.Value) *C {
	return &C{X: x}
}
func main() {
}
