// Code generated by bento ts-compat from keywordField.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjIf struct {
	If value.BStr `json:"if"`
}

func main() {
	obj := value.NewObject()
	obj.Set(value.FromGoString("if"), value.Number(1))
	a := &ObjIf{If: value.FromGoString("test")}
	n := a.If
	_ = n
	q := a.If
	_ = q
}
