// Code generated by bento ts-compat from lambdaASIEmit.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.Value) {
}
func main() {
	Foo(value.NewFunc(func(__a []value.Value) value.Value {
		return value.Number((func() float64 {
			return 127
		})())
	}))
}
