// Code generated by bento ts-compat from letShadowedByNameInNestedScope.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() {
	x := 0.0
	(func() {
		_x := 1.0
		_ = _x
		value.ConsoleLog(value.NumberToString(x))
	})()
}
func main() {
	var x value.Value
	_ = x
}
