// Code generated by bento ts-compat from literalIntersectionYieldsLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjType struct {
	Type value.BStr `json:"type"`
}

func main() {
	x := &ObjType{Type: value.FromGoString("string")}
	_ = x
}
