// Code generated by bento ts-compat from literals1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := 42.0
	_ = a
	var b float64 = 0xFA34
	_ = b
	c := 0.1715
	_ = c
	d := 3.14e5
	_ = d
	e := 8.14e-5
	_ = e
	f := true
	_ = f
	g := false
	_ = g
	h := value.FromGoString("")
	_ = h
	i := value.FromGoString("hi")
	_ = i
	j := value.FromGoString("")
	_ = j
	k := value.FromGoString("q\tq")
	_ = k
	m := value.NewRegExpLiteral("q", "")
	_ = m
	n := value.NewRegExpLiteral("\\d+", "g")
	_ = n
	o := value.NewRegExpLiteral("[3-5]+", "i")
	_ = o
}
