// Code generated by bento ts-compat from modifierParenCast.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	readonly := value.Undefined
	override := value.Undefined
	out := value.Undefined
	declare := value.Undefined
	a := (value.ToNumber(readonly))
	_ = a
	b := (value.ToNumber(override))
	_ = b
	c := (value.ToNumber(out))
	_ = c
	d := (value.ToNumber(declare))
	_ = d
}
