// Code generated by bento ts-compat from namedFunctionExpressionAssignedToClassProperty.ts. DO NOT EDIT.

package main

type Foo struct {
	A func() `json:"a"`
}

func NewFoo() *Foo {
	f := &Foo{}
	f.A = func() {
	}
	return f
}
func main() {
}
