// Code generated by bento ts-compat from narrowUnknownByTypeofObject.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.Value) {
	if x.TypeOf().Equal(value.FromGoString("object")) {
		_ = x
	}
}
func main() {
}
