// Code generated by bento ts-compat from nestedBlockScopedBindings13.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for false {
		var x value.Value
		_ = func() value.Value {
			return x
		}
	}
	for false {
		var y value.Value
		_ = y
		y = value.Number(1)
	}
}
