// Code generated by bento ts-compat from nestedBlockScopedBindings14.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	_ = x
	for false {
		var x value.Value
		_ = func() value.Value {
			return x
		}
	}
	var y value.Value
	_ = y
	for false {
		var y value.Value
		_ = y
		y = value.Number(1)
	}
}
