// Code generated by bento ts-compat from nestedBlockScopedBindings15.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for false {
		{
			var x value.Value
			_ = func() value.Value {
				return x
			}
		}
	}
	for false {
		{
			var y value.Value
			_ = y
			y = value.Number(1)
		}
	}
	for false {
		switch 1 {
		case 1:
			var z0 value.Value
			_ = func() value.Value {
				return z0
			}
		}
	}
	for false {
		switch 1 {
		case 1:
			var z value.Value
			_ = z
			z = value.Number(1)
		}
	}
}
