// Code generated by bento ts-compat from nestedBlockScopedBindings16.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	_ = x
	for false {
		{
			var x value.Value
			_ = func() value.Value {
				return x
			}
		}
	}
	var y value.Value
	_ = y
	for false {
		{
			var y value.Value
			_ = y
			y = value.Number(1)
		}
	}
	var z0 value.Value
	_ = z0
	for false {
		switch 1 {
		case 1:
			var z0 value.Value
			_ = func() value.Value {
				return z0
			}
		}
	}
	var z value.Value
	_ = z
	for false {
		switch 1 {
		case 1:
			var z value.Value
			_ = z
			z = value.Number(1)
		}
	}
}
