// Code generated by bento ts-compat from nestedBlockScopedBindings1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func A0() {
	{
		x := 1.0
		_ = x
	}
	{
		x := 1.0
		_ = x
	}
}
func A1() {
	{
		var x value.Value
		_ = x
	}
	{
		x := 1.0
		_ = x
	}
}
func A2() {
	{
		x := 1.0
		_ = x
	}
	{
		var x value.Value
		_ = x
	}
}
func A3() {
	{
		x := 1.0
		_ = x
	}
	switch 1 {
	case 1:
		var x value.Value
		_ = x
	}
}
func A4() {
	{
		var x value.Value
		_ = x
	}
	switch 1 {
	case 1:
		x := 1.0
		_ = x
	}
}
func main() {
}
