// Code generated by bento ts-compat from noCollisionThisExpressionAndLocalVarInAccessors.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjDoStuff struct {
	DoStuff func(value.Value) func() value.Value `json:"doStuff"`
}
type Class1 struct {
}

func NewClass1() *Class1 {
	return &Class1{}
}
func (c *Class1) A() float64 {
	x2 := &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			_this := 2.0
			return callback.Call(value.Number(_this))
		}
	}}
	_ = x2
	return 10
}
func (c *Class1) SetA(val float64) {
	x2 := &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			_this := 2.0
			return callback.Call(value.Number(_this))
		}
	}}
	_ = x2
}

type Class2 struct {
}

func NewClass2() *Class2 {
	return &Class2{}
}
func (c *Class2) A() float64 {
	_this := 2.0
	x2 := &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			return callback.Call(value.Number(_this))
		}
	}}
	_ = x2
	return 10
}
func (c *Class2) SetA(val float64) {
	_this := 2.0
	x2 := &ObjDoStuff{DoStuff: func(callback value.Value) func() value.Value {
		return func() value.Value {
			return callback.Call(value.Number(_this))
		}
	}}
	_ = x2
}
func main() {
}
