// Code generated by bento ts-compat from noCrashOnNoLib.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func F() {
	e := value.NewArray[*ObjEmpty]()
	_ = e
	for true {
		e = value.ArrayFrom(append([]*ObjEmpty{}, (e).Elems()...))
	}
}
func main() {
}
