// Code generated by bento ts-compat from noImplicitReturnsInAsync1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Test(isError bool) *value.Promise[value.Unit] {
	return value.RunAsyncVoid(func(_bt0 *value.AsyncCo) {
		if isError == true {
			return
		}
		x := value.Await(_bt0, value.Resolved[value.BStr](value.FromGoString("The test is passed without an error.")))
		_ = x
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
