// Code generated by bento ts-compat from numberAsInLHS.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.InOperator(value.Number(3), value.NewArrayValue([]value.Value{value.Number(0), value.Number(1)}))
}
