// Code generated by bento ts-compat from objectLiteralIndexerNoImplicitAny.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}
type ObjP struct {
	P value.Value `json:"p"`
}

func main() {
	x := &ObjP{P: value.Null}
	_ = x
}
