// Code generated by bento ts-compat from objectLiteralComputedNameNoDeclarationError.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBANANA struct {
	BANANA value.BStr `json:"BANANA"`
}
type ObjBanana struct {
	Banana float64 `json:"banana"`
}

func main() {
	Foo := &ObjBANANA{BANANA: value.FromGoString("banana")}
	Baa := value.NewObject().SetKeyed(value.StringValue(Foo.BANANA), value.Number(1))
	_ = Baa
}
