// Code generated by bento ts-compat from objectLiteral1.ts. DO NOT EDIT.

package main

type ObjAB struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
}

func main() {
	v30 := &ObjAB{A: 1, B: 2}
	_ = v30
}
