// Code generated by bento ts-compat from objectLiteralEnumPropertyNames.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.BStr `json:"a"`
	B value.BStr `json:"b"`
}
type ObjN_0N_1 struct {
	N_0 float64 `json:"0"`
	N_1 float64 `json:"1"`
}

var (
	StrsA = value.FromGoString("a")
	StrsB = value.FromGoString("b")
)

const (
	NumsA float64 = 0
	NumsB float64 = 1
)

func main() {
	x := value.NewObject().SetKeyed(value.StringValue(StrsA), value.StringValue(value.FromGoString("xo"))).SetKeyed(value.StringValue(StrsB), value.StringValue(value.FromGoString("xe")))
	_ = x
	ux := value.NewObject().SetKeyed(value.StringValue(StrsA), value.StringValue(value.FromGoString("xo"))).SetKeyed(value.StringValue(StrsB), value.StringValue(value.FromGoString("xe")))
	_ = ux
	y := &ObjAB{A: value.FromGoString("yo"), B: value.FromGoString("ye")}
	_ = y
	a := value.FromGoString("a")
	b := value.FromGoString("b")
	z := value.NewObject().SetKeyed(value.StringValue(a), value.StringValue(value.FromGoString("zo"))).SetKeyed(value.StringValue(b), value.StringValue(value.FromGoString("ze")))
	_ = z
	uz := value.NewObject().SetKeyed(value.StringValue(a), value.StringValue(value.FromGoString("zo"))).SetKeyed(value.StringValue(b), value.StringValue(value.FromGoString("ze")))
	_ = uz
	n := value.NewObject().SetKeyed(value.Number(NumsA), value.Number(1)).SetKeyed(value.Number(NumsB), value.Number(2))
	_ = n
	un := value.NewObject().SetKeyed(value.Number(NumsA), value.Number(3)).SetKeyed(value.Number(NumsB), value.Number(4))
	_ = un
	an := 0.0
	bn := 1.0
	m := value.NewObject().SetKeyed(value.Number(an), value.Number(5)).SetKeyed(value.Number(bn), value.Number(6))
	_ = m
	um := value.NewObject().SetKeyed(value.Number(an), value.Number(7)).SetKeyed(value.Number(bn), value.Number(8))
	_ = um
}
