// Code generated by bento ts-compat from omitTypeTestErrors01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.BStr `json:"a"`
	B float64    `json:"b"`
}
type ObjA struct {
	A value.BStr `json:"a"`
}

func GetBarC(bar *ObjAB) value.Value {
	return value.MissingProperty(bar)
}
func GetBazB(baz *ObjA) value.Value {
	return value.MissingProperty(baz)
}
func main() {
}
