// Code generated by bento ts-compat from omitTypeTests01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.BStr `json:"a"`
	B float64    `json:"b"`
}
type ObjA struct {
	A value.BStr `json:"a"`
}

func GetBarA(bar *ObjAB) value.BStr {
	return bar.A
}
func GetBazA(baz *ObjA) value.BStr {
	return baz.A
}
func main() {
}
