// Code generated by bento ts-compat from optionsStrictPropertyInitializationStrictNullChecks.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	_ = x
}
