// Code generated by bento ts-compat from overloadOnConstDuplicateOverloads1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a value.Value, x value.Value) {
}
func Foo2(a value.Value, x value.Value) {
}
func main() {
}
