// Code generated by bento ts-compat from overloadOnConstInObjectLiteralImplementingAnInterface.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX1 struct {
	X1 func(float64, func(value.BStr) float64) value.Value `json:"x1"`
}
type ObjX1_2 struct {
	X1 func(float64, func(value.BStr) float64) `json:"x1"`
}

func main() {
	i2 := &ObjX1_2{X1: func(a float64, cb func(value.BStr) float64) {
	}}
	_ = i2
}
