// Code generated by bento ts-compat from overloadOnConstAsTypeAnnotation.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	f := func(x value.BStr) float64 {
		return 1
	}
	_ = f
}
