// Code generated by bento ts-compat from parameterPropertyInConstructorWithPrologues.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}

type Foo1 struct {
	A value.BStr `json:"A"`
}

func NewFoo1(A value.BStr) *Foo1 {
	f := &Foo1{}
	f.A = A
	_ = value.FromGoString("ngInject1")
	return f
}

type Foo2 struct {
	A value.BStr `json:"A"`
	B value.BStr `json:"B"`
}

func NewFoo2(A value.BStr, B value.BStr) *Foo2 {
	f := &Foo2{}
	f.A = A
	f.B = B
	_ = value.FromGoString("ngInject1")
	_ = value.FromGoString("ngInject2")
	return f
}

type Foo3 struct {
	A value.BStr `json:"A"`
	B value.BStr `json:"B"`
	C value.BStr `json:"C"`
}

func NewFoo3(A value.BStr, B value.BStr, C value.BStr) *Foo3 {
	f := &Foo3{}
	f.A = A
	f.B = B
	f.C = C
	_ = value.FromGoString("ngInject1")
	_ = value.FromGoString("ngInject2")
	return f
}

type Foo4 struct {
	A value.BStr `json:"A"`
}

func NewFoo4(A value.BStr) *Foo4 {
	f := &Foo4{}
	f.A = A
	_ = value.FromGoString("ngInject1")
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}

type Foo5 struct {
	A value.BStr `json:"A"`
	B value.BStr `json:"B"`
}

func NewFoo5(A value.BStr, B value.BStr) *Foo5 {
	f := &Foo5{}
	f.A = A
	f.B = B
	_ = value.FromGoString("ngInject1")
	_ = value.FromGoString("ngInject2")
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}

type Foo6 struct {
	A value.BStr `json:"A"`
	B value.BStr `json:"B"`
	C value.BStr `json:"C"`
}

func NewFoo6(A value.BStr, B value.BStr, C value.BStr) *Foo6 {
	f := &Foo6{}
	f.A = A
	f.B = B
	f.C = C
	_ = value.FromGoString("ngInject1")
	_ = value.FromGoString("ngInject2")
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}

type Foo7 struct {
	C
	Member bool `json:"member"`
}

func NewFoo7(member bool) *Foo7 {
	f := &Foo7{}
	_ = value.FromGoString("ngInject1")
	f.C = *NewC()
	f.Member = member
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}

type Foo8 struct {
	C
	Member bool `json:"member"`
}

func NewFoo8(member bool) *Foo8 {
	f := &Foo8{}
	_ = value.FromGoString("ngInject1")
	f.C = *NewC()
	f.Member = member
	f.M()
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}
func (f *Foo8) M() {
}

type Foo9 struct {
	C
}

func NewFoo9() *Foo9 {
	f := &Foo9{}
	_ = value.FromGoString("ngInject1")
	_ = value.FromGoString("ngInject2")
	f.C = *NewC()
	f.M()
	value.ConsoleLog(value.FromGoString("hi"))
	return f
}
func (f *Foo9) M() {
}
func main() {
}
