// Code generated by bento ts-compat from parseArrowFunctionWithFunctionReturnType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	fn := func() value.Value {
		return value.Null
	}
	_ = fn
}
