// Code generated by bento ts-compat from parseReplacementCharacter.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("oops �� oops")
	_ = value.FromGoString("oops �� oops")
	_ = value.FromGoString("oops �� oops")
	_ = value.FromGoString("").ConcatN(value.FromGoString("oops �� oops"), value.FromGoString(""))
}
