// Code generated by bento ts-compat from pickOfLargeObjectUnionWorks.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjId struct {
	Id value.BStr `json:"id"`
}

func main() {
	xyz := &ObjId{Id: value.FromGoString("id")}
	_ = xyz
}
