// Code generated by bento ts-compat from quotedAccessorName1.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Foo() float64 {
	return 0
}
func main() {
}
