// Code generated by bento ts-compat from quotedPropertyName3.ts. DO NOT EDIT.

package main

type Test struct {
	Prop1 float64 `json:"prop1"`
}

func NewTest() *Test {
	return &Test{}
}
func (t *Test) Foo() {
	x := func() float64 {
		return t.Prop1
	}
	y := x()
	_ = y
}
func main() {
}
