// Code generated by bento ts-compat from quotedPropertyName2.ts. DO NOT EDIT.

package main

type Test1 struct {
}

var test1Prop1 float64 = 0

func NewTest1() *Test1 {
	return &Test1{}
}
func main() {
}
