// Code generated by bento ts-compat from recursiveConditionalEvaluationNonInfinite.ts. DO NOT EDIT.

package main

type ObjArray struct {
	Array *ObjNotArray `json:"array"`
}
type ObjNotArray struct {
	NotArray float64 `json:"notArray"`
}

func main() {
	var x *ObjArray
	y := x
	_ = y
	var a *ObjNotArray
	b := a
	_ = b
}
