// Code generated by bento ts-compat from regExpWithSlashInCharClass.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foo1 := value.NewRegExpLiteral(".[/]", "").ReplaceStr(value.FromGoString("a/"), value.FromGoString(""))
	_ = foo1
	foo2 := value.NewRegExpLiteral(".[//]", "g").ReplaceStr(value.FromGoString("a//"), value.FromGoString(""))
	_ = foo2
	foo3 := value.NewRegExpLiteral(".[/no sleep /till/]", "").ReplaceStr(value.FromGoString("a/"), value.FromGoString("bugfix"))
	_ = foo3
}
