// Code generated by bento ts-compat from requiredInitializedParameter1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1(a value.Value, b float64, c value.Value) {
}
func F2(a value.Value, b float64, c float64) {
}
func F3(a value.Value, b float64, c value.Value) {
}
func F4(a value.Value, b float64, c *value.Array[value.Value]) {
}
func main() {
	F1(value.Number(0), 1, value.Number(2))
	F2(value.Number(0), 1, 2)
	F3(value.Number(0), 1, value.Number(2))
	F4(value.Number(0), 1, value.NewArray[value.Value](value.Number(2)))
	F1(value.Number(0), 1, value.Undefined)
	F2(value.Number(0), 1, 0)
	F3(value.Number(0), 1, value.Undefined)
	F4(value.Number(0), 1, value.NewArray[value.Value]())
	F1(value.Number(0), 0, value.Undefined)
	F2(value.Number(0), 0, 0)
	F3(value.Number(0), 0, value.Undefined)
	F4(value.Number(0), 0, value.NewArray[value.Value]())
}
