// Code generated by bento ts-compat from restParameters.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F18(a value.Opt[value.BStr], b *value.Array[float64]) {
}
func F19(a value.Opt[value.BStr], b value.Opt[float64], c *value.Array[float64]) {
}
func F20(a value.BStr, b value.Opt[value.BStr], c *value.Array[float64]) {
}
func F21(a value.BStr, b value.Opt[value.BStr], c value.Opt[float64], d *value.Array[float64]) {
}
func main() {
}
