// Code generated by bento ts-compat from restParameterWithBindingPattern1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.Value `json:"a"`
	B value.Value `json:"b"`
}

func A(__0 *ObjAB) {
}
func main() {
}
