// Code generated by bento ts-compat from signatureLengthMismatchInOverload.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(callback value.Value) {
}
func main() {
	F(value.NewFunc(func(__a []value.Value) value.Value {
		(func(arg float64, arg2 float64) {
		})(value.ToNumber(value.Arg(__a, 0)), value.ToNumber(value.Arg(__a, 1)))
		return value.Undefined
	}))
}
