// Code generated by bento ts-compat from sourceMapValidationSwitch.ts. DO NOT EDIT.

package main

func main() {
	x := 10.0
	switch x {
	case 5:
		x++
	case 10:
		{
			x--
			break
		}
	default:
		x *= 10
	}
	switch x {
	case 5:
		x++
	case 10:
		{
			x--
			break
		}
	default:
		{
			x *= 10
		}
	}
}
