// Code generated by bento ts-compat from sourceMap-LineBreaks.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	endsWithlineSeparator := 10.0
	_ = endsWithlineSeparator
	endsWithParagraphSeparator := 10.0
	_ = endsWithParagraphSeparator
	endsWithNextLine := 1.0
	_ = endsWithNextLine
	endsWithLineFeed := 1.0
	_ = endsWithLineFeed
	endsWithCarriageReturnLineFeed := 1.0
	_ = endsWithCarriageReturnLineFeed
	endsWithCarriageReturn := 1.0
	_ = endsWithCarriageReturn
	endsWithLineFeedCarriageReturn := 1.0
	_ = endsWithLineFeedCarriageReturn
	endsWithLineFeedCarriageReturnLineFeed := 1.0
	_ = endsWithLineFeedCarriageReturnLineFeed
	stringLiteralWithLineFeed := value.FromGoString("line 1line 2")
	_ = stringLiteralWithLineFeed
	stringLiteralWithCarriageReturnLineFeed := value.FromGoString("line 1line 2")
	_ = stringLiteralWithCarriageReturnLineFeed
	stringLiteralWithCarriageReturn := value.FromGoString("line 1line 2")
	_ = stringLiteralWithCarriageReturn
	stringLiteralWithLineSeparator := value.FromGoString("line 1line 2")
	_ = stringLiteralWithLineSeparator
	stringLiteralWithParagraphSeparator := value.FromGoString("line 1line 2")
	_ = stringLiteralWithParagraphSeparator
	stringLiteralWithNextLine := value.FromGoString("line 1\u0085line 2")
	_ = stringLiteralWithNextLine
}
