// Code generated by bento ts-compat from sourceMapValidationDestructuringVariableStatementObjectBindingPattern2.ts. DO NOT EDIT.

package main

type ObjX struct {
	X float64 `json:"x"`
}
type ObjAB struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
}

func main() {
	_bt0 := &ObjX{X: 20}
	x := _bt0.X
	_ = x
	_bt1 := &ObjAB{A: 30, B: 40}
	a := _bt1.A
	_ = a
	b := _bt1.B
	_ = b
}
