// Code generated by bento ts-compat from sourceMapValidationIfElse.ts. DO NOT EDIT.

package main

func main() {
	i := 10.0
	if i == 10 {
		i++
	} else {
	}
	if i == 10 {
		i++
	} else if i == 20 {
		i--
	} else if i == 30 {
		i += 70
	} else {
		i--
	}
}
