// Code generated by bento ts-compat from spreadTypeRemovesReadonly.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjValue struct {
	Value value.BStr `json:"value"`
}

func main() {
	data := &ObjValue{Value: value.FromGoString("foo")}
	clone := &ObjValue{Value: data.Value}
	clone.Value = value.FromGoString("bar")
}
