// Code generated by bento ts-compat from staticGetterAndSetter.ts. DO NOT EDIT.

package main

type Foo struct {
}

func NewFoo() *Foo {
	return &Foo{}
}
func FooFoo() float64 {
	return 0
}
func FooSetFoo(n float64) {
}
func main() {
}
