// Code generated by bento ts-compat from stripInternal1.ts. DO NOT EDIT.

package main

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) Foo() {
}
func (c *C) Bar() {
}
func main() {
}
