// Code generated by bento ts-compat from stringHasStringValuedNumericIndexer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	str := value.FromGoString("").CharAt(0)
	_ = str
}
