// Code generated by bento ts-compat from stringIncludes.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var includes bool
	_ = includes
	includes = value.FromGoString("abcde").Includes(value.FromGoString("cd"))
	includes = value.FromGoString("abcde").Includes(value.FromGoString("cd"), 2)
}
