// Code generated by bento ts-compat from strictModeEnumMemberNameReserved.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	EStatic float64 = 0
)

func main() {
	_ = value.FromGoString("use strict")
	x1 := EStatic
	_ = x1
}
