// Code generated by bento ts-compat from strictBooleanMemberAssignability.ts. DO NOT EDIT.

package main

type Abc struct {
	Def bool `json:"def"`
}

func NewAbc() *Abc {
	return &Abc{Def: true}
}
func main() {
}
