// Code generated by bento ts-compat from stringLiteralPropertyNameWithLineContinuation1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjText struct {
	Text value.BStr `json:"text"`
}

func main() {
	x := &ObjText{Text: value.FromGoString("hello")}
	x.Text = value.FromGoString("bar")
}
