// Code generated by bento ts-compat from superInCatchBlock1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"unsafe"
)

type aVTable struct {
	m func(a *A)
}
type A struct {
	vtable *aVTable
}

var aBaseVTable = aVTable{m: (*A).mImpl}

func NewA() *A {
	a := &A{}
	a.vtable = &aBaseVTable
	return a
}
func (a *A) M() {
	a.vtable.m(a)
}
func (a *A) mImpl() {
}

type B struct {
	A
}

var bVTable = aVTable{m: func(a *A) {
	(*B)(unsafe.Pointer(a)).mImpl()
}}

func NewB() *B {
	b := &B{}
	b.vtable = &bVTable
	return b
}
func (b *B) mImpl() {
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
				b.A.mImpl()
			}
		}()
	}()
}
func main() {
}
