// Code generated by bento ts-compat from switchFallThroughs.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func R1(index float64) value.BStr {
	switch index {
	case 0, 1, 2:
		a := value.FromGoString("a")
		return a
	case 3, 4:
		{
			return value.FromGoString("b")
		}
	case 5:
		fallthrough
	default:
		return value.FromGoString("c")
	}
}
func main() {
}
