// Code generated by bento ts-compat from systemModuleTrailingComments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	test := value.FromGoString("TEST")
	_ = test
}
