// Code generated by bento ts-compat from targetTypeObjectLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X float64                  `json:"x"`
	Y func(value.BStr) float64 `json:"y"`
}

func main() {
	z := &ObjXY{X: 12, Y: func(w value.BStr) float64 {
		return 0
	}}
	_ = z
}
