// Code generated by bento ts-compat from templateLiteralIntersection.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.FromGoString("a")
	_ = a
}
