// Code generated by bento ts-compat from thisInLambda.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Foo struct {
	X value.BStr `json:"x"`
}

func NewFoo() *Foo {
	return &Foo{X: value.FromGoString("hello")}
}
func (foo *Foo) Bar() {
	_ = foo.X
	f := func() value.BStr {
		return foo.X
	}
	_ = f
}

type MyCls struct {
}

func NewMyCls() *MyCls {
	m := &MyCls{}
	MyFn(value.NewFunc(func(__a []value.Value) value.Value {
		(func() {
			MyFn(value.NewFunc(func(__a []value.Value) value.Value {
				(func() {
					x := m
					_ = x
				})()
				return value.Undefined
			}))
		})()
		return value.Undefined
	}))
	return m
}
func MyFn(a value.Value) {
}
func main() {
}
