// Code generated by bento ts-compat from thisInAccessors.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type GetterOnly struct {
}

func NewGetterOnly() *GetterOnly {
	return &GetterOnly{}
}
func (g *GetterOnly) Value() value.BStr {
	fn := func() *GetterOnly {
		return g
	}
	_ = fn
	return value.FromGoString("")
}
func (g *GetterOnly) SetValue(val value.BStr) {
}

type SetterOnly struct {
}

func NewSetterOnly() *SetterOnly {
	return &SetterOnly{}
}
func (s *SetterOnly) Value() value.BStr {
	return value.FromGoString("")
}
func (s *SetterOnly) SetValue(val value.BStr) {
	fn := func() *SetterOnly {
		return s
	}
	_ = fn
}

type GetterAndSetter struct {
}

func NewGetterAndSetter() *GetterAndSetter {
	return &GetterAndSetter{}
}
func (g *GetterAndSetter) Value() value.BStr {
	fn := func() *GetterAndSetter {
		return g
	}
	_ = fn
	return value.FromGoString("")
}
func (g *GetterAndSetter) SetValue(val value.BStr) {
	fn := func() *GetterAndSetter {
		return g
	}
	_ = fn
}
func main() {
}
