// Code generated by bento ts-compat from toStringOnPrimitives.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	value.BoolToString(true)
	aBool := false
	value.BoolToString(aBool)
	value.NumberToString(1.)
}
