// Code generated by bento ts-compat from transformArrowInBlockScopedLoopVarInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for true {
		local := value.Null
		a := func() value.Value {
			return local
		}
		_ = a
	}
}
