// Code generated by bento ts-compat from tryCatchFinally.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	func() {
		defer func() {
		}()
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
			}
		}()
	}()
	func() {
		defer func() {
		}()
	}()
}
