// Code generated by bento ts-compat from tryStatementInternalComments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	defer value.ReportUncaught()
	func() {
		defer func() {
		}()
		defer func() {
			if rec := recover(); rec != nil {
				e := value.Caught(rec)
				_ = e
			}
		}()
		value.Throw(value.ThrownString(value.FromGoString("no")))
	}()
}
