// Code generated by bento ts-compat from unicodeEscapesInJSDoc.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a value.Value, aa value.Value) {
	value.ConsoleLog(value.ConsoleValue(value.Add(a, aa)))
}
func Bar(a value.Value, aa value.Value) {
	value.ConsoleLog(value.ConsoleValue(value.Add(a, aa)))
}
func main() {
}
