// Code generated by bento ts-compat from unicodeStringLiteral.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	ੳ := value.FromGoString("Ü\u00adਲ\x0eĭ")
	_ = ੳ
}
