// Code generated by bento ts-compat from unionTypeWithIndexedLiteralType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjX struct {
	X value.BStr `json:"x"`
}

func main() {
	u := &ObjX{X: value.FromGoString("lit")}
	_ = u
}
