// Code generated by bento ts-compat from unusedParametersinConstructor2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Greeter struct {
}

func NewGreeter(param1 value.BStr, param2 value.BStr) *Greeter {
	g := &Greeter{}
	param2 = value.Concat(param2, value.FromGoString("dummy value"))
	return g
}
func main() {
}
