// Code generated by bento ts-compat from unusedVariablesinForLoop4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() {
	for _, elem := range value.NewArray[value.BStr](value.FromGoString("a"), value.FromGoString("b"), value.FromGoString("c")).Elems() {
		_ = elem
		x := 20.0
		_ = x
	}
}
func main() {
}
