// Code generated by bento ts-compat from unusedLocalsOnFunctionExpressionWithinFunctionDeclaration2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Greeter(person value.BStr, person2 value.BStr) {
	unused := 20.0
	_ = unused
	maker := func(child value.BStr) {
		unused2 := 22.0
		_ = unused2
	}
	_ = maker
	maker2 := func(child2 value.BStr) {
		unused3 := 23.0
		_ = unused3
	}
	maker2(person2)
}
func main() {
}
