// Code generated by bento ts-compat from unusedLocalsOnFunctionDeclarationWithinFunctionDeclaration1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Greeter(person value.BStr, person2 value.BStr) {
	unused := 20.0
	_ = unused
	maker := func(child value.BStr) {
		unused2 := 22.0
		_ = unused2
	}
	_ = maker
	person2 = value.FromGoString("dummy value")
}
func main() {
}
