// Code generated by bento ts-compat from unusedSingleParameterInContructor.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Dummy struct {
}

func NewDummy(person value.BStr) *Dummy {
	d := &Dummy{}
	unused := 20.0
	_ = unused
	return d
}
func main() {
}
