// Code generated by bento ts-compat from unusedParametersinConstructor1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Greeter struct {
}

func NewGreeter(param1 value.BStr) *Greeter {
	return &Greeter{}
}
func main() {
}
