// Code generated by bento ts-compat from unusedVariablesinForLoop3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() {
	for range value.NewArray[value.BStr](value.FromGoString("a"), value.FromGoString("b"), value.FromGoString("c")).Elems() {
	}
}
func main() {
}
