// Code generated by bento ts-compat from unusedMultipleParameters1InFunctionDeclaration.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Greeter(person value.BStr, person2 value.BStr) {
	unused := 20.0
	_ = unused
	person2 = value.FromGoString("dummy value")
}
func main() {
}
