// Code generated by bento ts-compat from unusedSingleParameterInFunctionDeclaration.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Greeter(person value.BStr) {
	unused := 20.0
	_ = unused
}
func main() {
}
