// Code generated by bento ts-compat from unusedMultipleParameter1InFunctionExpression.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	func_ := func(person value.BStr, person2 value.BStr) {
		unused := 20.0
		_ = unused
		person2 = value.FromGoString("Dummy value")
	}
	_ = func_
}
