// Code generated by bento ts-compat from unusedParameterProperty1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	Used value.BStr `json:"used"`
}

func NewA(used value.BStr) *A {
	a := &A{}
	a.Used = used
	foge := used
	_ = foge
	return a
}
func main() {
}
