// Code generated by bento ts-compat from unusedLocalsinConstructor2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Greeter struct {
}

func NewGreeter() *Greeter {
	g := &Greeter{}
	unused := 20.0
	_ = unused
	used := value.FromGoString("dummy")
	used = value.Concat(used, value.FromGoString("second part"))
	return g
}
func main() {
}
