// Code generated by bento ts-compat from unusedLocalsinConstructor1.ts. DO NOT EDIT.

package main

type Greeter struct {
}

func NewGreeter() *Greeter {
	g := &Greeter{}
	unused := 20.0
	_ = unused
	return g
}
func main() {
}
