// Code generated by bento ts-compat from unusedDestructuringParameters.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_val struct {
	E0 value.Value
}
type ObjA struct {
	A value.Value `json:"a"`
}

func main() {
	f := func(__0 value.Value) {
		a := __0.GetIndex(0)
		_ = a
	}
	f(value.NewArrayValue([]value.Value{value.Number(1)}))
	f2 := func(__0 value.Value) {
		a := __0.Get(value.FromGoString("a"))
		_ = a
	}
	f2(value.NewObject().Set(value.FromGoString("a"), value.Number(10)))
	f3 := func(__0 value.Value) {
		U5F_ := __0.GetIndex(0)
		_ = U5F_
	}
	f3(value.NewArrayValue([]value.Value{value.Number(10)}))
}
