// Code generated by bento ts-compat from useDefineForClassFieldsFlagDefault.ts. DO NOT EDIT.

package main

type Foo struct {
}

var fooX float64 = 1

func NewFoo() *Foo {
	return &Foo{}
}
func main() {
}
