// Code generated by bento ts-compat from varAsID.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Foo struct {
	Var value.Value `json:"var"`
	X   float64     `json:"x"`
}

func NewFoo() *Foo {
	return &Foo{X: 1}
}

type Foo2 struct {
	Var value.Value `json:"var"`
	X   float64     `json:"x"`
}

func NewFoo2() *Foo2 {
	return &Foo2{X: 1}
}
func main() {
	f := NewFoo()
	_ = f
	f2 := NewFoo2()
	_ = f2
}
