// Code generated by bento ts-compat from varInFunctionInVarInitializer.ts. DO NOT EDIT.

package main

func main() {
	var (
		a func() float64 = func() float64 {
			c := 1.0
			return c
		}
		b float64 = 1
	)
	_ = a
	_ = b
}
