// Code generated by bento ts-compat from varianceCantBeStrictWhileStructureIsnt.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjMember struct {
	Member func(value.BStr) `json:"member"`
}

func main() {
	var a *ObjMember
	var b *ObjMember
	var a2 *ObjMember
	var b2 *ObjMember
	a = b
	b = a
	a2 = b2
	b2 = a2
	a = b2
	b = a2
	a2 = b
	b2 = a
}
