// Code generated by bento ts-compat from variableDeclarationInnerCommentEmit.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.Null
	_ = a
	b := value.Null
	_ = b
	c := value.Null
	_ = c
	a = value.Null
}
