// Code generated by bento ts-compat from voidOperator1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Value
	_ = x
	var y value.Value
	_ = y
	var z value.Value
	_ = z
}
