// Code generated by bento ts-compat from yieldInForInInDownlevelGenerator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Gen() *value.Gen[value.BStr] {
	return value.NewGen[value.BStr](func(_bt0 *value.GenCo[value.BStr]) value.Value {
		obj := value.NewObject().Set(value.FromGoString("foo"), value.Number(1)).Set(value.FromGoString("bar"), value.Number(2))
		for _, key := range obj.ForInKeys().Elems() {
			_ = _bt0.Yield(key)
			_ = obj.Delete(value.FromGoString("bar"))
		}
		return value.Undefined
	})
}
func main() {
}
