// Code generated by bento ts-compat from spreadExcessProperty.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjABExtra struct {
	A     value.BStr `json:"a"`
	B     value.BStr `json:"b"`
	Extra value.BStr `json:"extra"`
}
type ObjAB struct {
	A value.BStr `json:"a"`
	B value.BStr `json:"b"`
}

func main() {
	extra1 := &ObjABExtra{A: value.FromGoString("a"), B: value.FromGoString("b"), Extra: value.FromGoString("extra")}
	a1 := &ObjABExtra{A: extra1.A, B: extra1.B, Extra: extra1.Extra}
	_ = a1
}
