// Code generated by bento ts-compat from FunctionExpression1_es6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := func() *value.Gen[value.Value] {
		return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
			return value.Undefined
		})
	}
	_ = v
}
