// Code generated by bento ts-compat from parser509677.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjY struct {
	Y value.BStr `json:"y"`
}

func main() {
	var n *ObjY
	_ = n
}
