// Code generated by bento ts-compat from parserNotHexLiteral1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjE0X0 struct {
	E0 value.BStr `json:"e0"`
	X0 value.BStr `json:"x0"`
}

func main() {
	x := &ObjE0X0{E0: value.FromGoString("cat"), X0: value.FromGoString("dog")}
	value.ConsoleLog(x.X0)
	value.ConsoleLog(x.E0)
}
