// Code generated by bento ts-compat from parser630933.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.FromGoString("Hello")
	var b value.Value = value.NewRegExpLiteral("\\/ver=([^/]+)", "").MatchStr(a)
	_ = b
}
