// Code generated by bento ts-compat from useObjectValuesAndEntries4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
}
type Tuple_str_num struct {
	E0 value.BStr
	E1 float64
}

func main() {
	o := &ObjAB{A: 1, B: 2}
	for _, x := range value.NewArray[float64](o.A, o.B).Elems() {
		y := x
		_ = y
	}
	entries := value.NewArray[Tuple_str_num](Tuple_str_num{E0: value.FromGoString("a"), E1: o.A}, Tuple_str_num{E0: value.FromGoString("b"), E1: o.B})
	_ = entries
}
