// Code generated by bento ts-compat from intersectionMemberOfUnionNarrowsCorrectly.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAKind struct {
	Kind value.Opt[value.BStr] `json:"kind"`
	A    value.BStr            `json:"a"`
}

func main() {
	var x *ObjAKind
	_ = x.A
}
