// Code generated by bento ts-compat from logicalAssignment11.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.Opt[value.BStr]
	var d value.Opt[value.BStr]
	_ = func() value.BStr {
		_bt1 := d
		if _bt1.IsUndefined() {
			return (func() value.BStr {
				var _bt0 value.BStr = x.Or(value.FromGoString("x"))
				d = value.Some[value.BStr](_bt0)
				return _bt0
			}())
		}
		return _bt1.Get()
	}()
	_ = d.Get().Length()
	var e value.Opt[value.BStr]
	if e.IsUndefined() {
		e = value.Some[value.BStr](x.Or(value.FromGoString("x")))
	}
	_ = e.Get().Length()
}
