// Code generated by bento ts-compat from asyncAliasReturnType_es6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
