// Code generated by bento ts-compat from independentPropertyVariance.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A float64    `json:"a"`
	B value.BStr `json:"b"`
}

func main() {
	var x *ObjAB
	var y *ObjAB
	_ = x == y
}
