// Code generated by bento ts-compat from classAbstractAsIdentifier.ts. DO NOT EDIT.

package main

type Abstract struct {
}

func NewAbstract() *Abstract {
	return &Abstract{}
}
func (a *Abstract) Foo() float64 {
	return 1
}
func main() {
	_ = NewAbstract()
}
