// Code generated by bento ts-compat from unicodeExtendedEscapesInStrings05.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("Hello world")
	_ = x
}
