// Code generated by bento ts-compat from unicodeExtendedEscapesInStrings11.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromUTF16([]uint16{0xdc00})
	_ = x
}
