// Code generated by bento ts-compat from unicodeExtendedEscapesInStrings06.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\U0010ffff")
	_ = x
}
