// Code generated by bento ts-compat from unicodeExtendedEscapesInTemplates20.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("Hello").ConcatN(value.FromGoString("    "), value.FromGoString("world"))
	_ = x
}
