// Code generated by bento ts-compat from unicodeExtendedEscapesInTemplates16.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("ꯍ\uef12㑖碐")
	_ = x
}
