// Code generated by bento ts-compat from unicodeExtendedEscapesInStrings23.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("g")
	_ = x
}
