// Code generated by bento ts-compat from nullOrUndefinedTypeGuardIsOrderIndependent.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type StrOrNullTag uint8

const (
	StrOrNullStr StrOrNullTag = iota
	StrOrNullNull
)

type StrOrNull struct {
	tag StrOrNullTag
	str value.BStr
}

func StrOrNullOfStr(v value.BStr) StrOrNull {
	return StrOrNull{tag: StrOrNullStr, str: v}
}
func StrOrNullOfNull() StrOrNull {
	return StrOrNull{tag: StrOrNullNull}
}
func (u StrOrNull) JSONArm() any {
	switch u.tag {
	case StrOrNullStr:
		return u.str
	case StrOrNullNull:
		return nil
	}
	return nil
}
func Test(strOrNull StrOrNull, strOrUndefined value.Opt[value.BStr]) {
	str := value.FromGoString("original")
	_ = str
	var nil value.Value
	_ = nil
	if strOrNull.tag == StrOrNullNull {
		nil = value.Null
	} else {
		str = strOrNull.str
	}
	if !strOrUndefined.IsUndefined() {
		str = strOrUndefined.Get()
	}
}
func main() {
}
