// Code generated by bento ts-compat from templateStringControlCharacterEscapes04.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("   20")
	_ = x
}
