// Code generated by bento ts-compat from templateStringWithEmbeddedTemplateString.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("123").ConcatN(value.FromGoString("456 ").ConcatN(value.FromGoString(" | "), value.FromGoString(" 654")), value.FromGoString("321 123"), value.FromGoString("456 ").ConcatN(value.FromGoString(" | "), value.FromGoString(" 654")), value.FromGoString("321"))
	_ = x
}
