// Code generated by bento ts-compat from templateStringWithCommentsInArrowFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	a := 1.0
	f1 := func() value.BStr {
		return _sb0.Reset().Num(a).Lit("a", 1).Done()
	}
	_ = f1
	f2 := func() value.BStr {
		return _sb1.Reset().Num(a).Done()
	}
	_ = f2
}
