// Code generated by bento ts-compat from templateStringInFunctionExpression.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := func() value.BStr {
		var _sb0 value.StrBuilder
		var _sb1 value.StrBuilder
		_ = _sb0.Reset().Lit("abc", 3).Num(0).Lit("def", 3).Done()
		return _sb1.Reset().Lit("abc", 3).Num(0).Lit("def", 3).Done()
	}
	_ = x
}
