// Code generated by bento ts-compat from templateStringInTypeAssertionES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	x := value.StringValue(_sb0.Reset().Lit("abc", 3).Num(123).Lit("def", 3).Done())
	_ = x
}
