// Code generated by bento ts-compat from templateStringInWhileES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	for value.StringToBool(_sb0.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done()) {
		_ = _sb1.Reset().Lit("def", 3).Num(1).Lit("def", 3).Done()
	}
}
