// Code generated by bento ts-compat from templateStringInConditional.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.BStr
	if value.StringToBool(value.FromGoString("abc").ConcatN(value.FromGoString(" "), value.FromGoString("def"))) {
		x = value.FromGoString("abc").ConcatN(value.FromGoString(" "), value.FromGoString("def"))
	} else {
		x = value.FromGoString("abc").ConcatN(value.FromGoString(" "), value.FromGoString("def"))
	}
	_ = x
}
