// Code generated by bento ts-compat from templateStringPlainCharactersThatArePartsOfEscapes02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("0").ConcatN(value.FromGoString(" "), value.FromGoString("1"), value.FromGoString(" "), value.FromGoString("2"), value.FromGoString(" "), value.FromGoString("3"), value.FromGoString(" "), value.FromGoString("4"), value.FromGoString(" "), value.FromGoString("5"), value.FromGoString(" "), value.FromGoString("6"), value.FromGoString(" "), value.FromGoString("7"), value.FromGoString(" "), value.FromGoString("8"), value.FromGoString(" "), value.FromGoString("9"), value.FromGoString(" "), value.FromGoString("10"), value.FromGoString(" "), value.FromGoString("11"), value.FromGoString(" "), value.FromGoString("12"), value.FromGoString(" "), value.FromGoString("13"), value.FromGoString(" "), value.FromGoString("14"), value.FromGoString(" "), value.FromGoString("15"), value.FromGoString(" "), value.FromGoString("16"), value.FromGoString(" "), value.FromGoString("17"), value.FromGoString(" "), value.FromGoString("18"), value.FromGoString(" "), value.FromGoString("19"), value.FromGoString(" "), value.FromGoString("20"), value.FromGoString(" "), value.FromGoString("2028"), value.FromGoString(" "), value.FromGoString("2029"), value.FromGoString(" "), value.FromGoString("0085"), value.FromGoString(" "), value.FromGoString("t"), value.FromGoString(" "), value.FromGoString("v"), value.FromGoString(" "), value.FromGoString("f"), value.FromGoString(" "), value.FromGoString("b"), value.FromGoString(" "), value.FromGoString("r"), value.FromGoString(" "), value.FromGoString("n"))
}
