// Code generated by bento ts-compat from templateStringInUnaryPlus.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb1 value.StrBuilder
	x := value.StringToNumber(_sb1.Reset().Lit("abc", 3).Num(123).Lit("def", 3).Done())
	_ = x
}
