// Code generated by bento ts-compat from templateStringControlCharacterEscapes02_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\x19\x19 19")
	_ = x
}
