// Code generated by bento ts-compat from templateStringWhitespaceEscapes1_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("\t\n\v\f\r")
}
