// Code generated by bento ts-compat from templateStringWithEmbeddedCommentsES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	_ = _sb0.Reset().Lit("head", 4).Num(10).Lit("\r\nmiddle", 8).Num(20).Lit("\r\ntail", 6).Done()
}
