// Code generated by bento ts-compat from templateStringInArrowFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := func(x value.Value) value.BStr {
		return value.FromGoString("abc").ConcatN(value.ToString(x), value.FromGoString("def"))
	}
	_ = x
}
