// Code generated by bento ts-compat from templateStringInArray.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func main() {
	var _sb0 value.StrBuilder
	x := value.NewArray[NumOrStr](NumOrStrOfNum(1), NumOrStrOfNum(2), NumOrStrOfStr(_sb0.Reset().Lit("abc", 3).Num(123).Lit("def", 3).Done()))
	_ = x
}
