// Code generated by bento ts-compat from templateStringInEqualityChecksES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	var _sb2 value.StrBuilder
	var _sb3 value.StrBuilder
	x := _sb0.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done().Equal(value.FromGoString("abc")) || !value.FromGoString("abc").Equal(_sb1.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done()) && value.LooseEquals(value.StringValue(_sb2.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done()), value.StringValue(value.FromGoString("abc0abc"))) && !value.FromGoString("abc0abc").Equal(_sb3.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done())
	_ = x
}
