// Code generated by bento ts-compat from templateStringWithBackslashEscapes01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	a := value.FromGoString("helloworld")
	_ = a
	b := value.FromGoString("hello\\world")
	_ = b
	c := value.FromGoString("hello\\world")
	_ = c
	d := value.FromGoString("hello\\\\world")
	_ = d
}
