// Code generated by bento ts-compat from templateStringWithEmbeddedUnaryPlus.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"math"
)

func main() {
	var _sb0 value.StrBuilder
	x := _sb0.Reset().Lit("abc", 3).Num(math.Inf(1)).Lit("def", 3).Done()
	_ = x
}
