// Code generated by bento ts-compat from validNumberAssignments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

const (
	EA float64 = 0
)

func main() {
	x := 1.0
	a := value.Number(x)
	_ = a
	b := x
	_ = b
	c := x
	_ = c
	d := x
	_ = d
	e := EA
	_ = e
	e = x
}
