// Code generated by bento ts-compat from checkJsdocTypedefOnlySourceFile.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjEmpty struct {
}

func main() {
	exports := &ObjEmpty{}
	_ = value.MissingProperty(exports)
	myString := value.FromGoString("str")
	_ = myString
}
