// Code generated by bento ts-compat from checkJsdocParamTag1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(n value.Value, s value.Value) {
}
func main() {
	Foo(value.Undefined, value.Undefined)
	Foo(value.Number(1), value.Undefined)
	Foo(value.Number(1), value.StringValue(value.FromGoString("hi")))
}
