// Code generated by bento ts-compat from checkJsdocOptionalParamOrder.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(a value.Value, b value.Value, c value.Value) {
}
func main() {
}
