// Code generated by bento ts-compat from extendsTag2.ts. DO NOT EDIT.

package main

type A struct {
}

func NewA() *A {
	return &A{}
}

type B struct {
	A
}

func NewB() *B {
	return &B{A: *NewA()}
}
func main() {
}
