// Code generated by bento ts-compat from jsdocTemplateTagDefault.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1(a value.Value, b value.Value) {
}
func F2(a value.Value, b value.Value) {
}
func F3(a value.Value, b value.Value) {
}
func main() {
	aDefault1 := value.NewArray[value.BStr](value.FromGoString(""))
	_ = aDefault1
	aDefault2 := value.NewArray[float64](0)
	_ = aDefault2
	aString := value.NewArray[value.BStr](value.FromGoString(""))
	_ = aString
	aNumber := value.NewArray[float64](0)
	_ = aNumber
}
