// Code generated by bento ts-compat from jsdocSignatureOnReturnedFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F1() func(value.Value, value.Value) value.Value {
	return func(a value.Value, b value.Value) value.Value {
		return value.Add(a, b)
	}
}
func F2() func(value.Value, value.Value) value.Value {
	return func(a value.Value, b value.Value) value.Value {
		return value.Add(a, b)
	}
}
func F3() func(value.Value, value.Value) value.Value {
	return func(a value.Value, b value.Value) value.Value {
		return value.Add(a, b)
	}
}
func F4() func(value.Value, value.Value) value.Value {
	return func(a value.Value, b value.Value) value.Value {
		return value.Add(a, b)
	}
}
func main() {
}
