// Code generated by bento ts-compat from jsdocLinkTag6.ts. DO NOT EDIT.

package main

import (
	"unsafe"
)

type aVTable struct {
	foo func(a *A)
}
type A struct {
	vtable *aVTable
}

var aBaseVTable = aVTable{foo: (*A).fooImpl}

func NewA() *A {
	a := &A{}
	a.vtable = &aBaseVTable
	return a
}
func (a *A) Foo() {
	a.vtable.foo(a)
}
func (a *A) fooImpl() {
}

type B struct {
	A
}

var bVTable = aVTable{foo: func(a *A) {
	(*B)(unsafe.Pointer(a)).fooImpl()
}}

func NewB() *B {
	b := &B{}
	b.vtable = &bVTable
	return b
}
func (b *B) fooImpl() {
}
func main() {
}
