// Code generated by bento ts-compat from forInBreakStatements.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for range value.NewObject().ForInKeys().Elems() {
		break
	}
ONE:
	for range value.NewObject().ForInKeys().Elems() {
		break ONE
	}
THREE:
	for range value.NewObject().ForInKeys().Elems() {
		break THREE
	}
FOUR:
	for range value.NewObject().ForInKeys().Elems() {
		for range value.NewObject().ForInKeys().Elems() {
			break FOUR
		}
	}
	for range value.NewObject().ForInKeys().Elems() {
	SIX:
		for range value.NewObject().ForInKeys().Elems() {
			break SIX
		}
	}
SEVEN:
	for range value.NewObject().ForInKeys().Elems() {
		for range value.NewObject().ForInKeys().Elems() {
			for range value.NewObject().ForInKeys().Elems() {
				break SEVEN
			}
		}
	}
EIGHT:
	for range value.NewObject().ForInKeys().Elems() {
		fn := func() {
		}
		_ = fn
		break EIGHT
	}
}
