// Code generated by bento ts-compat from useSharedArrayBuffer3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foge := value.NewSharedArrayBuffer(1024)
	bar := foge.Slice(1, 10)
	_ = bar
	len := foge.ByteLength()
	_ = len
}
