// Code generated by bento ts-compat from typeSatisfaction_contextualTyping1.ts. DO NOT EDIT.

package main

type ObjIsEvenIsOdd struct {
	IsEven func(float64) bool `json:"isEven"`
	IsOdd  func(float64) bool `json:"isOdd"`
}

func main() {
	var p *ObjIsEvenIsOdd
	_ = p
}
