// Code generated by bento ts-compat from typeSatisfaction_ensureInterfaceImpl.ts. DO NOT EDIT.

package main

type ObjMoveStartStop struct {
	Start func()        `json:"start"`
	Move  func(float64) `json:"move"`
	Stop  func()        `json:"stop"`
}

func main() {
	var car *ObjMoveStartStop
	_ = car
}
