// Code generated by bento ts-compat from contextuallyTypeCommaOperator03.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x func(value.BStr) value.BStr
	_ = x
	x = (func() func(value.BStr) value.BStr {
		_ = func(a value.Value) value.Value {
			return a
		}
		return func(b value.BStr) value.BStr {
			return b
		}
	}())
}
