// Code generated by bento ts-compat from parserES5ForOfStatement17.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	{
		var of value.Value
		_ = of
		for {
		}
	}
}
