// Code generated by bento ts-compat from ES5for-of32.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	array := value.NewArray[float64](1, 2, 3)
	sum := 0.0
	for _, num := range array.Elems() {
		if sum == 0 {
			array = value.NewArray[float64](4, 5, 6)
		}
		sum += num
	}
}
