// Code generated by bento ts-compat from ES5For-of22.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, x := range value.NewArray[float64](1, 2, 3).Elems() {
		_a := 0.0
		_ = _a
		value.ConsoleLog(value.NumberToString(x))
	}
}
