// Code generated by bento ts-compat from declarationEmitReadonly.ts. DO NOT EDIT.

package main

type C struct {
	X float64 `json:"x"`
}

func NewC(x float64) *C {
	return &C{X: x}
}
func main() {
}
