// Code generated by bento ts-compat from controlFlowCommaOperator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type NumOrStrOrBoolTag uint8

const (
	NumOrStrOrBoolNum NumOrStrOrBoolTag = iota
	NumOrStrOrBoolStr
	NumOrStrOrBoolBool
)

type NumOrStrOrBool struct {
	tag NumOrStrOrBoolTag
	num float64
	str value.BStr
	bl  bool
}

func NumOrStrOrBoolOfNum(v float64) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolNum, num: v}
}
func NumOrStrOrBoolOfStr(v value.BStr) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolStr, str: v}
}
func NumOrStrOrBoolOfBool(v bool) NumOrStrOrBool {
	return NumOrStrOrBool{tag: NumOrStrOrBoolBool, bl: v}
}
func (u NumOrStrOrBool) JSONArm() any {
	switch u.tag {
	case NumOrStrOrBoolNum:
		return u.num
	case NumOrStrOrBoolStr:
		return u.str
	case NumOrStrOrBoolBool:
		return u.bl
	}
	return nil
}
func F(x NumOrStrOrBool) {
	y := NumOrStrOrBoolOfBool(false)
	z := NumOrStrOrBoolOfBool(false)
	if func() bool {
		_ = func() value.BStr {
			var _bt0 value.BStr = value.FromGoString("")
			y = NumOrStrOrBoolOfStr(_bt0)
			return _bt0
		}()
		return x.tag == NumOrStrOrBoolStr
	}() {
		_ = x.str
		_ = y.str
		_ = z.bl
	} else if func() bool {
		_ = func() float64 {
			var _bt1 float64 = 1
			z = NumOrStrOrBoolOfNum(_bt1)
			return _bt1
		}()
		return x.tag == NumOrStrOrBoolNum
	}() {
		_ = x.num
		_ = y.str
		_ = z.num
	} else {
		_ = x.bl
		_ = y.str
		_ = z.num
	}
	_ = x
	_ = y.str
	_ = z
}
func main() {
}
