// Code generated by bento ts-compat from controlFlowDestructuringDeclaration.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_num struct {
	E0 float64
}
type Tuple_str struct {
	E0 value.BStr
}
type Tuple_undef struct {
	E0 value.Value
}
type ObjX struct {
	X float64 `json:"x"`
}
type ObjY struct {
	Y value.BStr `json:"y"`
}
type ObjZ struct {
	Z value.Value `json:"z"`
}
type NumOrStrTag uint8

const (
	NumOrStrNum NumOrStrTag = iota
	NumOrStrStr
)

type NumOrStr struct {
	tag NumOrStrTag
	num float64
	str value.BStr
}

func NumOrStrOfNum(v float64) NumOrStr {
	return NumOrStr{tag: NumOrStrNum, num: v}
}
func NumOrStrOfStr(v value.BStr) NumOrStr {
	return NumOrStr{tag: NumOrStrStr, str: v}
}
func (u NumOrStr) JSONArm() any {
	switch u.tag {
	case NumOrStrNum:
		return u.num
	case NumOrStrStr:
		return u.str
	}
	return nil
}
func F1() {
	x := NumOrStrOfNum(1)
	_ = x.num
	y := value.Some[value.BStr](value.FromGoString(""))
	_ = y.Get()
}
func F2() {
	_bt0 := Tuple_num{E0: 1}
	x := NumOrStrOfNum(_bt0.E0)
	_ = x
	_bt1 := Tuple_str{E0: value.FromGoString("")}
	y := value.Some[value.BStr](_bt1.E0)
	_ = y
	_ = Tuple_undef{E0: value.Undefined}
	z := value.FromGoString("")
	_ = z
}
func F3() {
	_bt2 := value.NewArray[float64](1)
	x := NumOrStrOfNum(_bt2.AtI(0))
	_ = x
	_bt3 := value.NewArray[value.BStr](value.FromGoString(""))
	y := value.Some[value.BStr](_bt3.AtI(0))
	_ = y
	_ = value.NewArray[value.Value](value.Undefined)
	z := value.FromGoString("")
	_ = z
}
func F4() {
	_bt4 := &ObjX{X: 1}
	x := _bt4.X
	_ = x
	_bt5 := &ObjY{Y: value.FromGoString("")}
	y := _bt5.Y
	_ = y
	_bt6 := &ObjZ{Z: value.Undefined}
	z := _bt6.Z
	_ = z
}
func F5() {
	_bt7 := &ObjX{X: 1}
	x := _bt7.X
	_ = x
	_bt8 := &ObjY{Y: value.FromGoString("")}
	y := _bt8.Y
	_ = y
	_bt9 := &ObjZ{Z: value.Undefined}
	z := _bt9.Z
	_ = z
}
func F6() {
	_bt10 := value.NewObject()
	x := _bt10.Get(value.FromGoString("x"))
	_ = x
	_bt11 := value.NewObject()
	y := _bt11.Get(value.FromGoString("y"))
	_ = y
	_bt12 := value.NewObject()
	z := _bt12.Get(value.FromGoString("z"))
	if z.IsUndefined() {
		z = value.StringValue(value.FromGoString(""))
	}
	_ = z
}
func F7() {
	o := value.NewObject().Set(value.FromGoString("x"), value.Number(1))
	x := o.Get(value.FromGoString("x"))
	_ = x
}
func main() {
}
