// Code generated by bento ts-compat from propertyAssignmentUseParentType1.ts. DO NOT EDIT.

package main

type N struct {
	Call func() bool
	Num  float64 `json:"num"`
}
type UFFFD_type struct {
	Call func() bool
	Nun  float64 `json:"nun"`
}
type UFFFD_function struct {
	Call  func() bool
	Extra float64 `json:"extra"`
}

func main() {
	interfaced := &N{}
	interfaced.Call = func() bool {
		return true
	}
	interfaced.Num = 123
	inlined := &UFFFD_type{}
	inlined.Call = func() bool {
		return true
	}
	inlined.Nun = 456
	ignoreJsdoc := &UFFFD_function{}
	ignoreJsdoc.Call = func() bool {
		return true
	}
	ignoreJsdoc.Extra = 111
}
