// Code generated by bento ts-compat from typeTagOnFunctionReferencesGeneric.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func InJs(l value.Value) value.Value {
	return l
}
func main() {
	InJs(value.Number(1))
	inJsArrow := func(j value.Value) value.Value {
		return j
	}
	inJsArrow(value.Number(2))
}
