// Code generated by bento ts-compat from typeofThisWithImplicitThis.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Test1() {
	x := value.Number(1)
	_ = x
}
func main() {
}
