// Code generated by bento ts-compat from typeQueryWithReservedWords.ts. DO NOT EDIT.

package main

type Controller struct {
}

func NewController() *Controller {
	return &Controller{}
}
func (c *Controller) Create() {
}
func (c *Controller) Delete() {
}
func (c *Controller) Var() {
}
func main() {
}
