// Code generated by bento ts-compat from stringLiteralType.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(x value.Value) {
}
func main() {
	var x value.BStr
	_ = x
}
