// Code generated by bento ts-compat from stringLiteralsWithEqualityChecks01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x value.BStr
	var y value.BStr
	var b bool
	_ = b
	b = x.Equal(y)
	b = value.FromGoString("foo").Equal(y)
	b = y.Equal(value.FromGoString("foo"))
	b = value.FromGoString("foo").Equal(value.FromGoString("bar"))
	b = value.FromGoString("bar").Equal(x)
	b = x.Equal(value.FromGoString("bar"))
	b = y.Equal(value.FromGoString("bar"))
	b = value.FromGoString("bar").Equal(y)
	b = !x.Equal(y)
	b = !value.FromGoString("foo").Equal(y)
	b = !y.Equal(value.FromGoString("foo"))
	b = !value.FromGoString("foo").Equal(value.FromGoString("bar"))
	b = !value.FromGoString("bar").Equal(x)
	b = !x.Equal(value.FromGoString("bar"))
	b = !y.Equal(value.FromGoString("bar"))
	b = !value.FromGoString("bar").Equal(y)
}
