// Code generated by bento ts-compat from emitDefaultParametersFunction.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.BStr, y float64) {
}
func Baz(x value.BStr, y float64, rest *value.Array[value.Value]) {
}
func Bar(y float64) {
}
func Bar1(y float64, rest *value.Array[value.Value]) {
}
func main() {
}
