// Code generated by bento ts-compat from parserMemberAccessorDeclaration5.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
}

func NewC() *C {
	return &C{}
}
func (c *C) SetA(i value.Value) {
}
func main() {
}
