// Code generated by bento ts-compat from objectTypeLiteralSyntax.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjBarFoo struct {
	Foo value.BStr `json:"foo"`
	Bar value.BStr `json:"bar"`
}

func main() {
	var x *ObjBarFoo
	_ = x
	var y *ObjBarFoo
	_ = y
}
