// Code generated by bento ts-compat from scannerStringLiteralWithContainingNullCharacter1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString(" \x00 ")
}
