// Code generated by bento ts-compat from objectTypesIdentityWithComplexConstraints.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo(x value.Value) {
}
func main() {
}
