// Code generated by bento ts-compat from Protected9.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	P value.Value `json:"p"`
}

func NewC(p value.Value) *C {
	return &C{P: p}
}
func main() {
}
