// Code generated by bento ts-compat from comparisonOperatorWithTwoOperandsAreAny.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var a value.Value
	r1 := value.Less(a, a)
	_ = r1
	r2 := value.Greater(a, a)
	_ = r2
	r3 := value.LessEqual(a, a)
	_ = r3
	r4 := value.GreaterEqual(a, a)
	_ = r4
	r5 := value.LooseEquals(a, a)
	_ = r5
	r6 := !value.LooseEquals(a, a)
	_ = r6
	r7 := value.StrictEquals(a, a)
	_ = r7
	r8 := !value.StrictEquals(a, a)
	_ = r8
}
