// Code generated by bento ts-compat from validStringAssignments.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("")
	a := value.StringValue(x)
	_ = a
	b := x
	_ = b
	c := x
	_ = c
	d := x
	_ = d
}
