// Code generated by bento ts-compat from templateStringWithPropertyAccessES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	_sb0.Reset().Lit("abc", 3).Num(0).Lit("abc", 3).Done().IndexOf(value.FromGoString("abc"))
}
