// Code generated by bento ts-compat from templateStringWithEmbeddedInOperator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	x := _sb0.Reset().Lit("abc", 3).Bool(value.InOperator(value.StringValue(value.FromGoString("hi")), value.NewObject().Set(value.FromGoString("hi"), value.Number(10)).Set(value.FromGoString("hello"), value.Number(20)))).Lit("def", 3).Done()
	_ = x
}
