// Code generated by bento ts-compat from templateStringWithEmbeddedTypeOfOperatorES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("abc").ConcatN(value.FromGoString("string"), value.FromGoString("def"))
	_ = x
}
