// Code generated by bento ts-compat from templateStringWithEmbeddedConditional.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type StrOrBoolTag uint8

const (
	StrOrBoolStr StrOrBoolTag = iota
	StrOrBoolBool
)

type StrOrBool struct {
	tag StrOrBoolTag
	str value.BStr
	bl  bool
}

func StrOrBoolOfStr(v value.BStr) StrOrBool {
	return StrOrBool{tag: StrOrBoolStr, str: v}
}
func StrOrBoolOfBool(v bool) StrOrBool {
	return StrOrBool{tag: StrOrBoolBool, bl: v}
}
func (u StrOrBool) JSONArm() any {
	switch u.tag {
	case StrOrBoolStr:
		return u.str
	case StrOrBoolBool:
		return u.bl
	}
	return nil
}
func (u StrOrBool) ToString() value.BStr {
	switch u.tag {
	case StrOrBoolStr:
		return u.str
	case StrOrBoolBool:
		return value.BoolToString(u.bl)
	}
	return value.FromGoString("")
}
func main() {
	x := value.FromGoString("abc").ConcatN(func() StrOrBool {
		if true {
			return StrOrBoolOfBool(false)
		}
		return StrOrBoolOfStr(value.FromGoString(" "))
	}().ToString(), value.FromGoString("def"))
	_ = x
}
