// Code generated by bento ts-compat from templateStringInPropertyAssignment.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjA struct {
	A value.BStr `json:"a"`
}

func main() {
	var _sb0 value.StrBuilder
	x := &ObjA{A: _sb0.Reset().Lit("abc", 3).Num(123).Lit("def", 3).Num(456).Lit("ghi", 3).Done()}
	_ = x
}
