// Code generated by bento ts-compat from templateStringControlCharacterEscapes03_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\x1f\x1f 1F 1f")
	_ = x
}
