// Code generated by bento ts-compat from templateStringWithEmbeddedTypeAssertionOnAddition.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("abc").ConcatN(value.ToString(value.Number((20.0))), value.FromGoString("def"))
	_ = x
}
