// Code generated by bento ts-compat from templateStringWithEmbeddedDivision.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	x := _sb0.Reset().Lit("abc", 3).Num(1.0).Lit("def", 3).Done()
	_ = x
}
