// Code generated by bento ts-compat from templateStringWithEmptyLiteralPortionsES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	var _sb2 value.StrBuilder
	var _sb3 value.StrBuilder
	var _sb4 value.StrBuilder
	var _sb5 value.StrBuilder
	var _sb6 value.StrBuilder
	var _sb7 value.StrBuilder
	var _sb8 value.StrBuilder
	var _sb9 value.StrBuilder
	var _sb10 value.StrBuilder
	var _sb11 value.StrBuilder
	a := value.FromGoString("")
	_ = a
	b := _sb0.Reset().Num(0).Done()
	_ = b
	c := _sb1.Reset().Lit("1", 1).Num(0).Done()
	_ = c
	d := _sb2.Reset().Num(0).Lit("2", 1).Done()
	_ = d
	e := _sb3.Reset().Lit("1", 1).Num(0).Lit("2", 1).Done()
	_ = e
	f := _sb4.Reset().Num(0).Num(0).Done()
	_ = f
	g := _sb5.Reset().Lit("1", 1).Num(0).Num(0).Done()
	_ = g
	h := _sb6.Reset().Num(0).Lit("2", 1).Num(0).Done()
	_ = h
	i := _sb7.Reset().Lit("1", 1).Num(0).Lit("2", 1).Num(0).Done()
	_ = i
	j := _sb8.Reset().Num(0).Num(0).Lit("3", 1).Done()
	_ = j
	k := _sb9.Reset().Lit("1", 1).Num(0).Num(0).Lit("3", 1).Done()
	_ = k
	l := _sb10.Reset().Num(0).Lit("2", 1).Num(0).Lit("3", 1).Done()
	_ = l
	m := _sb11.Reset().Lit("1", 1).Num(0).Lit("2", 1).Num(0).Lit("3", 1).Done()
	_ = m
}
