// Code generated by bento ts-compat from templateStringBinaryOperations.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	var _sb2 value.StrBuilder
	var _sb3 value.StrBuilder
	var _sb4 value.StrBuilder
	var _sb5 value.StrBuilder
	var _sb6 value.StrBuilder
	var _sb7 value.StrBuilder
	var _sb8 value.StrBuilder
	var _sb9 value.StrBuilder
	var _sb10 value.StrBuilder
	var _sb11 value.StrBuilder
	var _sb12 value.StrBuilder
	var _sb13 value.StrBuilder
	var _sb14 value.StrBuilder
	var _sb15 value.StrBuilder
	var _sb16 value.StrBuilder
	var _sb17 value.StrBuilder
	var _sb18 value.StrBuilder
	var _sb19 value.StrBuilder
	var _sb20 value.StrBuilder
	var _sb21 value.StrBuilder
	var _sb22 value.StrBuilder
	var _sb23 value.StrBuilder
	var _sb24 value.StrBuilder
	var _sb25 value.StrBuilder
	var _sb26 value.StrBuilder
	var _sb27 value.StrBuilder
	var _sb28 value.StrBuilder
	var _sb29 value.StrBuilder
	var _sb30 value.StrBuilder
	var _sb31 value.StrBuilder
	var _sb32 value.StrBuilder
	var _sb33 value.StrBuilder
	var _sb34 value.StrBuilder
	var _sb35 value.StrBuilder
	var _sb36 value.StrBuilder
	var _sb37 value.StrBuilder
	var _sb38 value.StrBuilder
	var _sb39 value.StrBuilder
	var _sb40 value.StrBuilder
	var _sb41 value.StrBuilder
	var _sb42 value.StrBuilder
	var _sb43 value.StrBuilder
	var _sb44 value.StrBuilder
	var _sb45 value.StrBuilder
	var _sb46 value.StrBuilder
	var _sb47 value.StrBuilder
	a := value.Concat(value.NumberToString(1), _sb0.Reset().Num(3).Done())
	_ = a
	b := value.Concat(value.NumberToString(1), _sb1.Reset().Lit("2", 1).Num(3).Done())
	_ = b
	c := value.Concat(value.NumberToString(1), _sb2.Reset().Num(3).Lit("4", 1).Done())
	_ = c
	d := value.Concat(value.NumberToString(1), _sb3.Reset().Lit("2", 1).Num(3).Lit("4", 1).Done())
	_ = d
	e := value.Concat(_sb4.Reset().Num(3).Done(), value.NumberToString(5))
	_ = e
	f := value.Concat(_sb5.Reset().Lit("2", 1).Num(3).Done(), value.NumberToString(5))
	_ = f
	g := value.Concat(_sb6.Reset().Num(3).Lit("4", 1).Done(), value.NumberToString(5))
	_ = g
	h := value.Concat(_sb7.Reset().Lit("2", 1).Num(3).Lit("4", 1).Done(), value.NumberToString(5))
	_ = h
	i := value.NumberToString(1).ConcatN(_sb8.Reset().Num(3).Done(), value.NumberToString(5))
	_ = i
	j := value.NumberToString(1).ConcatN(_sb9.Reset().Lit("2", 1).Num(3).Done(), value.NumberToString(5))
	_ = j
	k := value.NumberToString(1).ConcatN(_sb10.Reset().Num(3).Lit("4", 1).Done(), value.NumberToString(5))
	_ = k
	l := value.NumberToString(1).ConcatN(_sb11.Reset().Lit("2", 1).Num(3).Lit("4", 1).Done(), value.NumberToString(5))
	_ = l
	a2 := value.Concat(value.NumberToString(1), _sb12.Reset().Num(-1.0).Done())
	_ = a2
	b2 := value.Concat(value.NumberToString(1), _sb13.Reset().Lit("2", 1).Num(-1.0).Done())
	_ = b2
	c2 := value.Concat(value.NumberToString(1), _sb14.Reset().Num(-1.0).Lit("5", 1).Done())
	_ = c2
	d2 := value.Concat(value.NumberToString(1), _sb15.Reset().Lit("2", 1).Num(-1.0).Lit("5", 1).Done())
	_ = d2
	e2 := value.Concat(_sb16.Reset().Num(-1.0).Done(), value.NumberToString(6))
	_ = e2
	f2 := value.Concat(_sb17.Reset().Lit("2", 1).Num(-1.0).Done(), value.NumberToString(6))
	_ = f2
	g2 := value.Concat(_sb18.Reset().Num(-1.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = g2
	h2 := value.Concat(_sb19.Reset().Lit("2", 1).Num(-1.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = h2
	i2 := value.NumberToString(1).ConcatN(_sb20.Reset().Num(-1.0).Done(), value.NumberToString(6))
	_ = i2
	j2 := value.NumberToString(1).ConcatN(_sb21.Reset().Lit("2", 1).Num(-1.0).Done(), value.NumberToString(6))
	_ = j2
	k2 := value.NumberToString(1).ConcatN(_sb22.Reset().Num(-1.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = k2
	l2 := value.NumberToString(1).ConcatN(_sb23.Reset().Lit("2", 1).Num(-1.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = l2
	a3 := value.Concat(value.NumberToString(1), _sb24.Reset().Num(12.0).Done())
	_ = a3
	b3 := value.Concat(value.NumberToString(1), _sb25.Reset().Lit("2", 1).Num(12.0).Done())
	_ = b3
	c3 := value.Concat(value.NumberToString(1), _sb26.Reset().Num(12.0).Lit("5", 1).Done())
	_ = c3
	d3 := value.Concat(value.NumberToString(1), _sb27.Reset().Lit("2", 1).Num(12.0).Lit("5", 1).Done())
	_ = d3
	e3 := value.Concat(_sb28.Reset().Num(12.0).Done(), value.NumberToString(6))
	_ = e3
	f3 := value.Concat(_sb29.Reset().Lit("2", 1).Num(12.0).Done(), value.NumberToString(6))
	_ = f3
	g3 := value.Concat(_sb30.Reset().Num(12.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = g3
	h3 := value.Concat(_sb31.Reset().Lit("2", 1).Num(12.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = h3
	i3 := value.NumberToString(1).ConcatN(_sb32.Reset().Num(12.0).Done(), value.NumberToString(6))
	_ = i3
	j3 := value.NumberToString(1).ConcatN(_sb33.Reset().Lit("2", 1).Num(12.0).Done(), value.NumberToString(6))
	_ = j3
	k3 := value.NumberToString(1).ConcatN(_sb34.Reset().Num(12.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = k3
	l3 := value.NumberToString(1).ConcatN(_sb35.Reset().Lit("2", 1).Num(12.0).Lit("5", 1).Done(), value.NumberToString(6))
	_ = l3
	a4 := value.Concat(value.NumberToString(1), _sb36.Reset().Num(float64((3)&4)).Done())
	_ = a4
	b4 := value.Concat(value.NumberToString(1), _sb37.Reset().Lit("2", 1).Num(float64((3)&4)).Done())
	_ = b4
	c4 := value.Concat(value.NumberToString(1), _sb38.Reset().Num(float64((3)&4)).Lit("5", 1).Done())
	_ = c4
	d4 := value.Concat(value.NumberToString(1), _sb39.Reset().Lit("2", 1).Num(float64((3)&4)).Lit("5", 1).Done())
	_ = d4
	e4 := value.Concat(_sb40.Reset().Num(float64((3)&4)).Done(), value.NumberToString(6))
	_ = e4
	f4 := value.Concat(_sb41.Reset().Lit("2", 1).Num(float64((3)&4)).Done(), value.NumberToString(6))
	_ = f4
	g4 := value.Concat(_sb42.Reset().Num(float64((3)&4)).Lit("5", 1).Done(), value.NumberToString(6))
	_ = g4
	h4 := value.Concat(_sb43.Reset().Lit("2", 1).Num(float64((3)&4)).Lit("5", 1).Done(), value.NumberToString(6))
	_ = h4
	i4 := value.NumberToString(1).ConcatN(_sb44.Reset().Num(float64((3)&4)).Done(), value.NumberToString(6))
	_ = i4
	j4 := value.NumberToString(1).ConcatN(_sb45.Reset().Lit("2", 1).Num(float64((3)&4)).Done(), value.NumberToString(6))
	_ = j4
	k4 := value.NumberToString(1).ConcatN(_sb46.Reset().Num(float64((3)&4)).Lit("5", 1).Done(), value.NumberToString(6))
	_ = k4
	l4 := value.NumberToString(1).ConcatN(_sb47.Reset().Lit("2", 1).Num(float64((3)&4)).Lit("5", 1).Done(), value.NumberToString(6))
	_ = l4
}
