// Code generated by bento ts-compat from templateStringWithOpenCommentInStringPortionES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	_ = _sb0.Reset().Lit(" /**head  ", 10).Num(10).Lit(" // still middle  ", 18).Num(20).Lit(" /* still tail ", 15).Done()
}
