// Code generated by bento ts-compat from templateStringWhitespaceEscapes2_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	_ = value.FromGoString("\t\v\f \u00a0\ufeff")
}
