// Code generated by bento ts-compat from templateStringInInOperator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.InOperator(value.StringValue(value.FromGoString("").ConcatN(value.FromGoString("hi"), value.FromGoString(""))), value.NewObject().Set(value.FromGoString("hi"), value.Number(10)).Set(value.FromGoString("hello"), value.Number(20)))
	_ = x
}
