// Code generated by bento ts-compat from templateStringControlCharacterEscapes01_ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	x := value.FromGoString("\x00\x00\x00 0 00 0000")
	_ = x
}
