// Code generated by bento ts-compat from privateNameFieldAccess.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	p_myField value.BStr `json:"-"`
}

func NewA() *A {
	a := &A{}
	a.p_myField = value.FromGoString("hello world")
	value.ConsoleLog(a.p_myField)
	return a
}
func main() {
}
