// Code generated by bento ts-compat from privateNameAndStaticInitializer.ts. DO NOT EDIT.

package main

type A struct {
	p_foo  float64 `json:"-"`
	p_prop float64 `json:"-"`
}

var aInst *A

func NewA() *A {
	return &A{p_foo: 1, p_prop: 2}
}
func staticInitA() {
	aInst = NewA()
}
func main() {
	staticInitA()
}
