// Code generated by bento ts-compat from privateNameFieldInitializer.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type A struct {
	p_field         float64     `json:"-"`
	p_uninitialized value.Value `json:"-"`
}

func NewA() *A {
	return &A{p_field: 10}
}
func main() {
}
