// Code generated by bento ts-compat from privateNamesIncompatibleModifiersJs.ts. DO NOT EDIT.

package main

type A struct {
	p_a float64 `json:"-"`
	p_b float64 `json:"-"`
	p_c float64 `json:"-"`
}

func NewA() *A {
	return &A{p_a: 1, p_b: 1, p_c: 1}
}
func (a *A) p_aMethod() float64 {
	return 1
}
func (a *A) p_bMethod() float64 {
	return 1
}
func (a *A) p_cMethod() float64 {
	return 1
}
func (a *A) p_aProp() float64 {
	return 1
}
func (a *A) p_bProp() float64 {
	return 1
}
func (a *A) p_cProp() float64 {
	return 1
}
func (a *A) p_set_aProp(value_ float64) {
}
func (a *A) p_set_bProp(value_ float64) {
}
func (a *A) p_set_cProp(value_ float64) {
}
func main() {
}
