// Code generated by bento ts-compat from emitExponentiationOperator3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	temp := 10.0
	_ = value.Pow((-func() float64 {
		temp++
		return temp
	}()), 3)
	_ = value.Pow((func() float64 {
		temp--
		return temp
	}()), 3)
	_ = value.Pow((-func() float64 {
		prev := temp
		temp++
		return prev
	}()), 3)
	_ = value.Pow((func() float64 {
		prev := temp
		temp--
		return prev
	}()), 3)
	_ = value.Pow((-(value.Pow(1, func() float64 {
		temp++
		return temp
	}()))), 3)
	_ = value.Pow((-(value.Pow(1, func() float64 {
		temp--
		return temp
	}()))), 3)
	_ = value.Pow((-(value.Pow(1, func() float64 {
		prev := temp
		temp++
		return prev
	}()))), 3)
	_ = value.Pow((-(value.Pow(1, func() float64 {
		prev := temp
		temp--
		return prev
	}()))), 3)
	_ = value.Pow((-3), func() float64 {
		prev := temp
		temp++
		return prev
	}())
	_ = value.Pow((-3), func() float64 {
		prev := temp
		temp--
		return prev
	}())
	_ = value.Pow((-3), func() float64 {
		temp++
		return temp
	}())
	_ = value.Pow((-3), func() float64 {
		temp--
		return temp
	}())
	_ = value.Pow((3), func() float64 {
		prev := temp
		temp++
		return prev
	}())
	_ = value.Pow((3), func() float64 {
		prev := temp
		temp--
		return prev
	}())
	_ = value.Pow((3), func() float64 {
		temp++
		return temp
	}())
	_ = value.Pow((3), func() float64 {
		temp--
		return temp
	}())
	_ = value.Pow((-3), value.Pow(func() float64 {
		prev := temp
		temp++
		return prev
	}(), 2))
	_ = value.Pow((-3), value.Pow(func() float64 {
		prev := temp
		temp--
		return prev
	}(), 2))
	_ = value.Pow((-3), value.Pow(func() float64 {
		temp++
		return temp
	}(), 2))
	_ = value.Pow((-3), value.Pow(func() float64 {
		temp--
		return temp
	}(), 2))
	_ = value.Pow((3), value.Pow(func() float64 {
		prev := temp
		temp++
		return prev
	}(), 2))
	_ = value.Pow((3), value.Pow(func() float64 {
		prev := temp
		temp--
		return prev
	}(), 2))
	_ = value.Pow((3), value.Pow(func() float64 {
		temp++
		return temp
	}(), 2))
	_ = value.Pow((3), value.Pow(func() float64 {
		temp--
		return temp
	}(), 2))
	_ = value.Pow(3, -func() float64 {
		prev := temp
		temp++
		return prev
	}())
	_ = value.Pow(3, -func() float64 {
		prev := temp
		temp--
		return prev
	}())
	_ = value.Pow(3, -func() float64 {
		temp++
		return temp
	}())
	_ = value.Pow(3, func() float64 {
		temp--
		return temp
	}())
	_ = value.Pow(3, value.Pow((-func() float64 {
		prev := temp
		temp++
		return prev
	}()), 2))
	_ = value.Pow(3, value.Pow((-func() float64 {
		prev := temp
		temp--
		return prev
	}()), 2))
	_ = value.Pow(3, value.Pow((func() float64 {
		prev := temp
		temp++
		return prev
	}()), 2))
	_ = value.Pow(3, value.Pow((func() float64 {
		prev := temp
		temp--
		return prev
	}()), 2))
	_ = value.Pow(3, value.Pow((-func() float64 {
		temp++
		return temp
	}()), 2))
	_ = value.Pow(3, value.Pow((func() float64 {
		temp--
		return temp
	}()), 2))
}
