// Code generated by bento ts-compat from emitExponentiationOperatorInTemplateString2ES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var _sb0 value.StrBuilder
	var _sb1 value.StrBuilder
	var _sb2 value.StrBuilder
	var _sb3 value.StrBuilder
	var _sb4 value.StrBuilder
	var _sb5 value.StrBuilder
	var _sb6 value.StrBuilder
	var _sb7 value.StrBuilder
	var _sb8 value.StrBuilder
	var _sb9 value.StrBuilder
	var _sb10 value.StrBuilder
	var _sb11 value.StrBuilder
	var _sb12 value.StrBuilder
	var _sb13 value.StrBuilder
	var _sb14 value.StrBuilder
	t1 := 10.0
	t2 := 10.0
	var s value.Value
	_ = s
	_ = _sb0.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2)).Done()
	_ = _sb1.Reset().Lit("hello ", 6).Num(value.Pow(t1, value.Pow(t2, t1))).Done()
	_ = _sb2.Reset().Lit("hello ", 6).Num(t1 + value.Pow(t2, t1)).Done()
	_ = _sb3.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2) + t1).Done()
	_ = _sb4.Reset().Lit("hello ", 6).Num(t1 + value.Pow(t2, t2) + t1).Done()
	_ = value.FromGoString("hello ").ConcatN(value.FromGoString("number"), value.FromGoString(""))
	_ = value.FromGoString("hello ").ConcatN(value.Concat(value.NumberToString(1), value.FromGoString("number")), value.FromGoString(""))
	_ = _sb5.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2)).Num(value.Pow(t1, t2)).Done()
	_ = _sb6.Reset().Lit("hello ", 6).Num(value.Pow(t1, value.Pow(t2, t1))).Num(value.Pow(t1, value.Pow(t2, t1))).Done()
	_ = _sb7.Reset().Lit("hello ", 6).Num(t1 + value.Pow(t2, t1)).Num(t1 + value.Pow(t2, t1)).Done()
	_ = _sb8.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2) + t1).Num(value.Pow(t1, t2) + t1).Done()
	_ = _sb9.Reset().Lit("hello ", 6).Num(t1 + value.Pow(t2, t2) + t1).Num(t1 + value.Pow(t2, t2) + t1).Done()
	_ = value.FromGoString("hello ").ConcatN(value.FromGoString("number"), value.FromGoString(""), value.FromGoString("number"), value.FromGoString(""))
	_ = _sb10.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2)).Lit(" hello world ", 13).Num(value.Pow(t1, t2)).Done()
	_ = _sb11.Reset().Lit("hello ", 6).Num(value.Pow(t1, value.Pow(t2, t1))).Lit(" hello world ", 13).Num(value.Pow(t1, value.Pow(t2, t1))).Done()
	_ = _sb12.Reset().Lit("hello ", 6).Num(t1+value.Pow(t2, t1)).Lit(" hello world ", 13).Num(t1 + value.Pow(t2, t1)).Done()
	_ = _sb13.Reset().Lit("hello ", 6).Num(value.Pow(t1, t2)+t1).Lit(" hello world ", 13).Num(value.Pow(t1, t2) + t1).Done()
	_ = _sb14.Reset().Lit("hello ", 6).Num(t1+value.Pow(t2, t2)+t1).Lit(" hello world ", 13).Num(t1 + value.Pow(t2, t2) + t1).Done()
	_ = value.FromGoString("hello ").ConcatN(value.FromGoString("number"), value.FromGoString(" hello world "), value.FromGoString("number"), value.FromGoString(""))
}
