// Code generated by bento ts-compat from accessorsOverrideProperty5.ts. DO NOT EDIT.

package main

type B struct {
}

func NewB() *B {
	return &B{}
}

type C struct {
	B
}

func NewC() *C {
	return &C{B: *NewB()}
}
func (c *C) P() float64 {
	return 1
}
func (c *C) SetP(value_ float64) {
}
func main() {
}
