// Code generated by bento ts-compat from optionalProperty.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type C struct {
	Prop value.Value `json:"prop"`
}

func NewC() *C {
	return &C{}
}
func main() {
}
