// Code generated by bento ts-compat from staticMemberInitialization.ts. DO NOT EDIT.

package main

type C struct {
}

var cX float64 = 1

func NewC() *C {
	return &C{}
}
func main() {
	c := NewC()
	_ = c
	r := cX
	_ = r
}
