// Code generated by bento ts-compat from iterableArrayPattern2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjDoneValue struct {
	Value value.Value `json:"value"`
	Done  bool        `json:"done"`
}
type SymbolIterator struct {
}

func NewSymbolIterator() *SymbolIterator {
	return &SymbolIterator{}
}
func (s *SymbolIterator) Next() *ObjDoneValue {
	return &ObjDoneValue{Value: value.NewSymbolNoDesc(), Done: false}
}
func (s *SymbolIterator) SymbolIterator() *SymbolIterator {
	return s
}
func main() {
	_bt3 := value.ArrayFrom(func() []value.Value {
		var _bt0 []value.Value
		_bt1 := NewSymbolIterator().SymbolIterator()
		for {
			_bt2 := _bt1.Next()
			if _bt2.Done {
				break
			}
			_bt0 = append(_bt0, _bt2.Value)
		}
		return _bt0
	}())
	a := _bt3.AtI(0)
	_ = a
	b := _bt3.Slice(1)
	_ = b
}
