// Code generated by bento ts-compat from nullishCoalescingOperatorInAsyncGenerator.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjB struct {
	B value.Opt[float64] `json:"b"`
}

func F(a *ObjB) *value.AsyncGen[float64] {
	return value.NewAsyncGen[float64](func(_bt0 *value.AsyncGenCo[float64]) value.Value {
		c := a.B.Or(10)
		for c != 0 && c == c {
			_ = _bt0.Yield(func() float64 {
				prev := c
				c--
				return prev
			}())
		}
		return value.Undefined
	})
}
func main() {
}
