// Code generated by bento ts-compat from optionalProperties02.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjAB struct {
	A value.Opt[value.BStr] `json:"a"`
	B value.BStr            `json:"b"`
}

func main() {
	_ = &ObjAB{A: value.None[value.BStr]()}
}
