// Code generated by bento ts-compat from optionalProperties01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjOptionalRequired1Required2 struct {
	Required1 value.BStr            `json:"required1"`
	Required2 value.BStr            `json:"required2"`
	Optional  value.Opt[value.BStr] `json:"optional"`
}

func main() {
	foo1 := &ObjOptionalRequired1Required2{Required1: value.FromGoString("hello"), Optional: value.None[value.BStr]()}
	_ = foo1
	foo2 := &ObjOptionalRequired1Required2{Required1: value.FromGoString("hello"), Optional: value.Some[value.BStr](value.FromGoString("bar"))}
	_ = foo2
}
