// Code generated by bento ts-compat from iterableContextualTyping1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	iter := value.NewArray[func(value.BStr) float64](func(s value.BStr) float64 {
		return s.Length()
	})
	_ = iter
}
