// Code generated by bento ts-compat from emitExponentiationOperator1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
	"math"
)

func main() {
	_ = value.Pow(1, -2)
	_ = value.Pow(1, 2)
	_ = value.Pow((-1), 2)
	_ = value.Pow(1, value.Pow(2, 3))
	_ = value.Pow(1, value.Pow(2, -3))
	_ = value.Pow(1, -(value.Pow(2, 3)))
	_ = value.Pow((-(value.Pow(1, 2))), 3)
	_ = value.Pow((-(value.Pow(1, 2))), -3)
	_ = value.Pow(1, 2) + 3
	_ = value.Pow(1, 2) - 3
	_ = value.Pow(1, 2) * 3
	_ = value.Pow(1, 2) / 3
	_ = math.Mod(value.Pow(1, 2), 3)
	_ = value.Pow(1, -2) + 3
	_ = value.Pow(1, -2) - 3
	_ = value.Pow(1, -2) * 3
	_ = value.Pow(1, -2) / 3
	_ = math.Mod(value.Pow(1, -2), 3)
	_ = 2 + value.Pow(3, 3)
	_ = 2 - value.Pow(3, 3)
	_ = 2 * value.Pow(3, 3)
	_ = 2 / value.Pow(3, 3)
	_ = math.Mod(2, value.Pow(3, 3))
	_ = value.Pow((5.0), 4)
	_ = value.Pow((-1.0), 4)
	_ = value.Pow((6.0), 4)
	_ = value.Pow((0.6666666666666666), 4)
}
