// Code generated by bento ts-compat from awaitUsingDeclarationsInForOf.2.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Main() *value.Promise[value.Unit] {
	return value.AsyncVoid(func() {
		for range value.NewArray[value.Value]().Elems() {
		}
	})
}
func main() {
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
