// Code generated by bento ts-compat from for-of4.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	for _, v := range value.NewArray[float64](0).Elems() {
		_ = v
	}
}
