// Code generated by bento ts-compat from for-of38.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	map_ := func() *value.Map[value.BStr, bool] {
		_bt0 := value.NewStringMap[bool]()
		_bt0.Set(value.FromGoString(""), true)
		return _bt0
	}()
	{
		_bt1 := map_
		_bt2 := _bt1.Keys()
		_bt3 := _bt1.Values()
		for _bt4, k := range _bt2 {
			v := _bt3[_bt4]
			_ = k
			_ = v
		}
	}
}
