// Code generated by bento ts-compat from for-of41.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X *value.Array[float64] `json:"x"`
	Y *ObjP                 `json:"y"`
}
type ObjP struct {
	P value.BStr `json:"p"`
}

func main() {
	array := value.NewArray[*ObjXY](&ObjXY{X: value.NewArray[float64](0), Y: &ObjP{P: value.FromGoString("")}})
	for _, _bt0 := range array.Elems() {
		_bt1 := _bt0.X
		a := _bt1.AtI(0)
		_bt2 := _bt0.Y
		p := _bt2.P
		_ = a
		_ = p
	}
}
