// Code generated by bento ts-compat from for-of37.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Tuple_str_bool struct {
	E0 value.BStr
	E1 bool
}

func main() {
	map_ := func() *value.Map[value.BStr, bool] {
		_bt0 := value.NewStringMap[bool]()
		_bt0.Set(value.FromGoString(""), true)
		return _bt0
	}()
	{
		_bt1 := map_
		_bt2 := _bt1.Keys()
		_bt3 := _bt1.Values()
		for _bt4, _bt5 := range _bt2 {
			v := Tuple_str_bool{E0: _bt5, E1: _bt3[_bt4]}
			_ = v
		}
	}
}
