// Code generated by bento ts-compat from for-of9.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var v value.BStr
	_ = v
	for _, _bt0 := range value.NewArray[value.BStr](value.FromGoString("hello")).Elems() {
		v = _bt0
	}
	for _, _bt1 := range value.FromGoString("hello").CodePoints() {
		v = _bt1
	}
}
