// Code generated by bento ts-compat from emitRestParametersFunctionES6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Bar(rest *value.Array[value.Value]) {
}
func Foo(x float64, y value.BStr, rest *value.Array[value.Value]) {
}
func main() {
}
