// Code generated by bento ts-compat from parser768531.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	{
		_ = 3
	}
	_ = value.NewRegExpLiteral("x", "")
}
