// Code generated by bento ts-compat from asyncFunctionDeclaration2_es2017.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(await value.Value) {
}
func main() {
}
