// Code generated by bento ts-compat from asyncArrowFunction1_es2017.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	foo := func() *value.Promise[value.Unit] {
		return value.AsyncVoid(func() {
		})
	}
	_ = foo
	value.RunMicrotasks()
	value.ReportUnhandledRejections()
}
