// Code generated by bento ts-compat from declarationEmitIdentifierPredicates01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F(x value.Value) bool {
	return x.TypeOf().Equal(value.FromGoString("number"))
}
func main() {
}
