// Code generated by bento ts-compat from jsDeclarationsMissingTypeParameters.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func X(y value.Value) {
}
func Y(func_ value.Value) {
	return
}
func Z() value.Value {
	return value.Null
}
func W() value.Value {
	return value.Null
}
func main() {
}
