// Code generated by bento ts-compat from parserArrayLiteralExpression10.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := value.NewArray[float64](1, 1)
	_ = v
}
