// Code generated by bento ts-compat from parserArrayLiteralExpression1.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	v := value.NewArray[value.Value]()
	_ = v
}
