// Code generated by bento ts-compat from mixedPropertyElementAccessAssignmentDeclaration.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	arr := value.NewArray[value.Value]()
	arr.At(0).Get(value.FromGoString("prop")).SetIndex(2, value.NewObject())
}
