// Code generated by bento ts-compat from typeFromPropertyAssignment30.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type Combo struct {
	Call func() float64
	P    value.Value `json:"p"`
}

func main() {
	c := &Combo{}
	c.Call = func() float64 {
		return 1
	}
	c.P = value.NewObject()
}
