// Code generated by bento ts-compat from asiPreventsParsingAsNamespace04.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	module := 10.0
	_ = value.InOperator(value.Number(module), value.NewObject())
}
