// Code generated by bento ts-compat from generatorTypeCheck27.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func G() *value.Gen[func(value.BStr) float64] {
	return value.NewGen[func(value.BStr) float64](func(_bt0 *value.GenCo[func(value.BStr) float64]) value.Value {
		_ = _bt0.YieldFrom(func() *value.Gen[func(value.BStr) float64] {
			return value.NewGen[func(value.BStr) float64](func(_bt1 *value.GenCo[func(value.BStr) float64]) value.Value {
				_ = _bt1.Yield(func(x value.BStr) float64 {
					return x.Length()
				})
				return value.Undefined
			})
		}())
		return value.Undefined
	})
}
func main() {
}
