// Code generated by bento ts-compat from generatorTypeCheck3.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func G1() *value.Gen[value.BStr] {
	return value.NewGen[value.BStr](func(_bt0 *value.GenCo[value.BStr]) value.Value {
		return value.Undefined
	})
}
func main() {
}
