// Code generated by bento ts-compat from generatorNoImplicitReturns.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func TestGenerator() *value.Gen[value.BStr] {
	return value.NewGen[value.BStr](func(_bt0 *value.GenCo[value.BStr]) value.Value {
		if value.MathRandom() > 0.5 {
			return value.Undefined
		}
		_ = _bt0.Yield(value.FromGoString("hello"))
		return value.Undefined
	})
}
func main() {
}
