// Code generated by bento ts-compat from YieldExpression3_es6.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func Foo() *value.Gen[value.Value] {
	return value.NewGen[value.Value](func(_bt0 *value.GenCo[value.Value]) value.Value {
		_ = _bt0.Yield(value.Undefined)
		_ = _bt0.Yield(value.Undefined)
		return value.Undefined
	})
}
func main() {
}
