// Code generated by bento ts-compat from contextuallyTypeCommaOperator01.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func main() {
	var x func(value.BStr) value.BStr
	_ = x
	x = (func() func(value.BStr) value.BStr {
		_ = 100
		return func(a value.BStr) value.BStr {
			return a
		}
	}())
}
