// Code generated by bento ts-compat from forBreakStatements.ts. DO NOT EDIT.

package main

func main() {
	for {
		break
	}
ONE:
	for {
		break ONE
	}
THREE:
	for {
		break THREE
	}
FOUR:
	for {
		for {
			break FOUR
		}
	}
	for {
	SIX:
		for {
			break SIX
		}
	}
SEVEN:
	for {
		for {
			for {
				break SEVEN
			}
		}
	}
EIGHT:
	for {
		fn := func() {
		}
		_ = fn
		break EIGHT
	}
}
