// Code generated by bento ts-compat from whileBreakStatements.ts. DO NOT EDIT.

package main

func main() {
	for true {
		break
	}
ONE:
	for true {
		break ONE
	}
THREE:
	for true {
		break THREE
	}
FOUR:
	for true {
		for true {
			break FOUR
		}
	}
	for true {
	SIX:
		for true {
			break SIX
		}
	}
SEVEN:
	for true {
		for true {
			for true {
				break SEVEN
			}
		}
	}
EIGHT:
	for true {
		fn := func() {
		}
		_ = fn
		break EIGHT
	}
}
