// Code generated by bento ts-compat from emitter.noCatchBinding.es2019.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

func F() {
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				value.Caught(rec)
			}
		}()
	}()
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				value.Caught(rec)
				func() {
					defer func() {
						if rec := recover(); rec != nil {
							value.Caught(rec)
						}
					}()
				}()
			}
		}()
	}()
	func() {
		defer func() {
		}()
		defer func() {
			if rec := recover(); rec != nil {
				value.Caught(rec)
			}
		}()
	}()
}
func main() {
}
