// Code generated by bento ts-compat from for-of19.ts. DO NOT EDIT.

package main

type ObjDoneValue struct {
	Value *Foo `json:"value"`
	Done  bool `json:"done"`
}
type Foo struct {
}

func NewFoo() *Foo {
	return &Foo{}
}

type FooIterator struct {
}

func NewFooIterator() *FooIterator {
	return &FooIterator{}
}
func (f *FooIterator) Next() *ObjDoneValue {
	return &ObjDoneValue{Value: NewFoo(), Done: false}
}
func (f *FooIterator) SymbolIterator() *FooIterator {
	return f
}
func main() {
	{
		_bt0 := NewFooIterator().SymbolIterator()
		for {
			_bt1 := _bt0.Next()
			if _bt1.Done {
				break
			}
			v := _bt1.Value
			_ = v
		}
	}
}
