// Code generated by bento ts-compat from for-of42.ts. DO NOT EDIT.

package main

import (
	"github.com/tamnd/bento/pkg/value"
)

type ObjXY struct {
	X value.BStr `json:"x"`
	Y float64    `json:"y"`
}

func main() {
	array := value.NewArray[*ObjXY](&ObjXY{X: value.FromGoString(""), Y: 0})
	for _, _bt0 := range array.Elems() {
		a := _bt0.X
		b := _bt0.Y
		_ = a
		_ = b
	}
}
